### ISSUE TITLE
Missing image_dimensions_from_memory_and_format or similar that allows getting the dimensions from memory

### ISSUE THREAD

**Issue by FSMaxB-dooshop** [image-rs/image#1007]
I would like to be able to read the dimensions of an image in memory without needing to decode all of it. Essentially `image_dimensions` but without requiring a file.

I need this because I want to estimate the size of a decoded image before actually decoding it. I'm currently implementing an image conversion pipeline and need to prevent large (in terms of dimensions) images from being decoded because they can sometimes easily surpass the available RAM.

## Draft

This could either be:

```rust
fn image_dimensions_from_memory_and_format(buffer: &[u8], format: ImageFormat) -> ImageResult<(u32, u32)>
```
or something that takes `impl std::io::Reader`.

**Comment by FSMaxB-dooshop** [comment]
Just to be clear: This functionality is already possible with the current API and I will do that for now, but this essentially requires the duplication of `image_dimension_impl` in my code.

**Comment by fintelia** [comment]
Personally I'd like there to be a function like:
```rust
fn decoder_from_format<R: Read>(reader: Read, format: ImageFormat) -> ImageResult<impl ImageDecoder>;
```
You could then easily get the dimensions by calling `ImageDecoder::dimensions`, but would also have access to all the other image metadata and could decode without having to repeat any work.

**Comment by HeroicKatora** [comment]
I don't like creating even more free functions floating around in the API, there may be a better way to solve this somewhat comprehensively:

```
/// Name bikeshedding.
struct ImageReader<R> {
    reader: R,
    format: Option<ImageFormat>,
}

impl<R: Read> ImageReader<R> {
    /// Construct a reader that will guess the format.
    pub fn new(reader: R) -> Self { … }

    /// Construct a reader with specified format.
    pub fn with_format(reader: R, format: ImageFormat) -> Self { … }

    /// Open a file to read. Format will be guessed.
    /// Note: Failure to guess is not an error. The `Err` is only for `File::open`.
    pub fn with_format(reader: R, format: ImageFormat) -> io::Result<Self> { … }

    /// Get the current format.
    fn format(&self) -> Option<ImageFormat> { … }
}

impl<R: Read + Seek> ImageReader<R> {
    /// Replace the format with a guess based on the content.
    ///
    /// If the guess fails, the format is unchanged. Error is for seek, hence io::Error 
    /// and not ImageError.
    pub fn guess_format(&mut self) -> io::Result<()> { … }
    /// Read the image dimensions.
    /// Uses the current format to construct the correct reader.
    pub fn image_dimensions(self) -> ImageResult<(u32, u32)> { … }
    /// Read the image (replaces `load`).
    /// Uses the current format to construct the correct reader.
    pub fn load(self) -> ImageResult<DynamicImage> { … }
}
```

**Comment by FSMaxB-dooshop** [comment]
@HeroicKatora This would definitely solve my problem and would even simplify some of my other code, since I wouldn't have to pass around the format separately anymore.

And I think you meant:

```rust
/// Open a file to read. Format will be guessed.
/// Note: Failure to guess is not an error. The `Err` is only for `File::open`.
pub fn from_file<P>(path: P) -> std::io::Result<Self> where P: AsRef<Path> { … }
```
or something like that.

Also it would be great to be able to get the reader back out again with something like `pub fn nto_reader(self) -> R`
