### ISSUE TITLE
How to build examples?

### ISSUE THREAD

**Issue by BaoshanPang** [image-rs/image#1017]
Is there a document about how to build the examples?

I am using "cargo new xyz" to create a project then paste the code to the project. Is there a better way to do it? 

Thanks,
Baoshan

**Comment by fintelia** [comment]
You can clone the repository with:
```
git clone https://github.com/image-rs/image && cd image
```
Then you can run the examples with something like:
```
cargo run --example fractal
```
or if you have to pass arguments to the examples:
```
cargo run --example opening -- path/to/image.png
```

**Comment by BaoshanPang** [comment]
@fintelia Thanks for the quick response. I will try them out.
