### ISSUE TITLE
Use rustfmt in CI

### ISSUE THREAD

**Issue by JohnTitor** [image-rs/image#1024]
It's a good idea that we have a common coding style.
In image-rs/imaproc, we use rustfmt on Travis to check formatting code. Should we use it here too?

**Comment by HeroicKatora** [comment]
Agreed. A good target would be to start adding clippy lints to the CI builds, but not fail the build yet, or at least ignore the failure.

**Comment by HeroicKatora** [comment]
Just as a note, here's the officially recommended Travis solution for running rustfmt:

https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server
