### ISSUE TITLE
Cannot open a png file while opencv and PIL can

### ISSUE THREAD

**Issue by Mabinogiysk** [image-rs/image#1027]
I tried to read image files with rust and I got a FormatError("invalid signature") error while open one specified png file. I have tried to read that image with opencv and PIL, but everything is ok.
If someone can help, I can send that image to you.

**Comment by HeroicKatora** [comment]
An `invalid signature` on png occurs only when the file does not start with the expected, fixed [PNG signature](https://tools.ietf.org/html/rfc2083#page-11). The most likely cause without additional information is that the image is not `png` afterall even though the path name to indicates this? Note that format detection of `open` is based on the path name alone and does not inspect the file.

You can attach images to Github issues if there are no IP concerns.

**Comment by Mabinogiysk** [comment]
Can I just send the image to you by email?

**Comment by Mabinogiysk** [comment]
> An `invalid signature` on png occurs only when the file does not start with the expected, fixed [PNG signature](https://tools.ietf.org/html/rfc2083#page-11). The most likely cause without additional information is that the image is not `png` afterall even though the path name to indicates this? Note that format detection of `open` is based on the path name alone and does not inspect the file.
> 
> You can attach images to Github issues if there are no IP concerns.

Can I just send the image to you by email?

**Comment by HeroicKatora** [comment]
I don't prefer it, unless your concern is merely that you yourself can not upload the image to Github or a hoster but I could.

The issue would not be reproducible, it would be hard to find duplicates and much harder for other people to contribute. That makes this entirely non-actionable.

For a `png` you could try to strip the file of the pixel contents, or replace them with constant color, and drop metadata blocks. If that doesn't change the error then it might be a reproduction case free of IP issues?
