### ISSUE TITLE
Is it possible to get an unsafe function like unsafe_get_pixel_mut()?

### ISSUE THREAD

**Issue by arthmis** [image-rs/image#1038]
I would like to be able use something like `unsafe_get_pixel_mut()`.

My specific use case for this functionality is ...
Possibly faster accesses to image when mutating a pixel.

I know there is `unsafe_put_pixel` but I guess it would be nice to benchmark them to see if there are any differences.

**Comment by fintelia** [comment]
I'm not really eager to add more unsafe functions to the library, unless there is strong justification for them. In this case if you really want super fast access to `ImageBuffer`s, you can deref them into a `&[P::Subpixel]` and then use all your favorite unsafe slice methods. For `FlatSamples` the as_slice method gets you the same thing.

**Comment by yvt** [comment]
I'd say it's good to have for orthogonality. Plus, even if we don't have that, the library users would come up with a work-around one way or another, resulting in more obscure, hard-to-validate code when it could have been a single call to `unsafe_get_pixel_mut`.

**Comment by lazypassion** [comment]
For me it's really useful because the iterators provided by `ImageBuffer` aren't particularly useful when it comes to convolution kernels and other image processing algorithms. The limitations of the borrow checker won't allow external pixel accesses So I can't rely on the iterators for performant pixel accesses. 

Also when doing convolution kernels, the bounds checks are done already within the algorithm so bound checking on mutable accesses are redundant.

**Comment by fintelia** [comment]
@lazypassion I strongly suspect that there are ways to convince the optimizer that the bounds checks are redundant and so a version with `get_pixel_mut()` would work just as well. But if you want to avoid checking, you don't have to rely on iterators, rather you can directly access the buffer contents with unsafe code. Something along the lines of:

```rust
fn foo(img: &mut ImageBuffer<Rgba<u8>>) {
    let (w, h) = img.dimensions();
    let buf: &mut [u8] = *img;
   
    unsafe {
         *buf.get_unchecked_mut(37) *= 2;
    }
}
```

**Comment by lazypassion** [comment]
That's fair. I guess i just like the 'cleanliness' of using the api from the image crate rather than changing things around. I'll try the suggested alternatives to see if I can really live without the unsafe `get_pixel_mut`
