### ISSUE TITLE
DXT5 decoding shouldn't decode color block with punch-through alpha

### ISSUE THREAD

**Issue by kubouch** [image-rs/image#1039]
### Problem description 

When decoding DXT5, the color part (DXT1) should be decoded without alpha (i.e. the condition on [this line](https://github.com/image-rs/image/blob/df863b8ea705b6f103937d1c7afb3be2cbc1d582/src/dxt.rs#L318) should take into account whether the format is actually DXT1). If the endpoints of the color block are - for whatever reason - inverted (i.e. min is max and max is min), the decoder outputs incorrect values since it thinks there is a punch-through alpha.

An example of handling the DXT1 decoding can be found in the [squish-rs](https://github.com/jansol/squish-rs/blob/ded7a4b078ced7fecae446d41c780ad14b2da2a9/squish/src/colourblock.rs#L135) library.

### Steps to reproduce:

Put `image = "0.22"` and `squish = "1"` to Cargo.toml.

main.rs:
```rust
use image::{ImageDecoder, dxt::DXTDecoder, dxt::DXTVariant};

fn main() {
    // encoded 16x16 image data with swapped min/max endpoints in the first block
    let data: Vec<u8> = vec![
        98, 90, 173, 13, 141, 18, 169, 166, 33, 196, 65, 196, 95, 235, 224,
        104, 99, 94, 155, 178, 57, 90, 239, 22, 33, 196, 65, 196, 9, 191, 189,
        239, 97, 90, 253, 189, 81, 43, 33, 41, 65, 196, 33, 196, 85, 234, 173,
        221, 99, 86, 36, 39, 109, 128, 159, 156, 65, 204, 33, 188, 171, 170,
        250, 255, 104, 94, 185, 247, 188, 98, 7, 105, 65, 204, 65, 196, 85,
        213, 47, 170, 103, 91, 152, 212, 223, 108, 213, 188, 65, 204, 33, 196,
        255, 223, 170, 215, 106, 93, 35, 145, 231, 180, 235, 178, 33, 204, 65,
        196, 43, 191, 174, 93, 107, 91, 24, 155, 188, 117, 105, 151, 65, 204,
        65, 196, 128, 215, 215, 213, 102, 90, 115, 73, 65, 206, 237, 58, 65,
        204, 33, 188, 170, 170, 255, 255, 101, 85, 146, 182, 1, 108, 155, 219,
        65, 196, 33, 188, 0, 0, 171, 11, 98, 89, 219, 8, 182, 119, 157, 150,
        33, 196, 65, 196, 175, 234, 175, 170, 99, 91, 143, 249, 219, 166, 68,
        244, 65, 196, 33, 196, 170, 42, 175, 242, 95, 87, 142, 59, 140, 19, 71,
        182, 65, 196, 65, 188, 175, 0, 0, 170, 95, 90, 21, 237, 169, 91, 255,
        82, 65, 196, 33, 196, 174, 3, 138, 174, 95, 86, 155, 48, 62, 109, 187,
        213, 65, 204, 33, 188, 175, 255, 255, 255, 96, 87, 146, 240, 231, 36,
        247, 151, 65, 196, 33, 196, 191, 85, 87, 95
    ];

    // image
    let dxt5_dec_image = DXTDecoder::new(
        data.as_slice(), 16, 16, DXTVariant::DXT5
    ).unwrap();
    let dec_buf_image = dxt5_dec_image.read_image().unwrap();

    // squish
    let mut dec_buf_squish = vec![0u8; 16*16*4];
    let format = squish::Format::Bc3;
    format.decompress(data.as_slice(), 16, 16, &mut dec_buf_squish);

    // notice the first two pixels have zero color while squish decodes fine
    for i in 0..16 {
        println!(
            "{}: image: {}, squish-rs: {}",
            i, dec_buf_image[i], dec_buf_squish[i]
        );
    }
}
```

**Comment by jansol** [comment]
I'll take a stab at fixing this. Thanks for the test case!

**Comment by CensoredUsername** [comment]
Hmm, I must've misinterpreted the specs while writing the implementation.

@jansol did you get anywhere with this? I could take a look as well, I authored most of this module.

Also, if this is broken in the decoder the encoder probably has the same bug. I validated them heavily against each other.

**Comment by jansol** [comment]
The encoder has the freedom to put color0 and color1 in whichever order it wants for DXT3 and DXT5, it has no meaning there so that would not be a bug. But I haven't looked at the encoder so no idea if it does something else that causes errors.

**Comment by CensoredUsername** [comment]
>But I haven't looked at the encoder so no idea if it does something else that causes errors.

It would occasionally encode blocks with the punchthrough alpha variant, which if you would decode them without it would cause them to look different.

**Comment by jansol** [comment]
Yeah it shouldn't do it "occasionally" without somehow signaling which choice it made. Or simply have that dictated by the user, which brings us to the other part that was discussed in my PR.

**Comment by CensoredUsername** [comment]
I meant "occasionally" as in when the DXT3/5 encoders would judge the 3 linear colors + black encoding to be more optimal. But yes. DXT3/5 should never use them as that is not actually a thing in that encoding. DXT1 should be split into DXT1 with alpha (punchthrough alpha) and DXT1 without alpha (where punchthrough maps to black).
