### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by icefoxen** [image-rs/image#1042]
`image` is the go-to crate for image loading in the Rust gamedev world, which is a pretty thankless and tedious task a lot of the time.  I got in a Mood and said "If I were to replace this relatively heavy dependency in `ggez` with a lighter-weight one that only did what I need it to, what would it look like?" and gave it a try.  The result was only a couple hundred lines of code... mostly copy-pasted from `image` with minor modifications, very nicely readable, and using the `tiff`, `jpeg-decoder` etc crates which this project also maintains.  It is simpler and compiles faster... but the differences aren't actually big enough to make it worth having a separate crate for this when you can just use `image`'s feature flags to chop out a bunch of the things you don't need and get most of the same benefits.  I've seldom been so happy to have wasted a couple hours on something that turned out unnecessary.

So, yeah, you could totally make a simpler `image` that was geared towards gamedev only, but it's not worth it.  About all I could ask for is have a 1.0 release and split `imageops` into its own crate, and both of those seem to be on the way.  So as a user, all I really want from this project is to keep doing what you're doing.

Thank you for making something so good I can't improve it!

**Comment by HeroicKatora** [comment]
Such kind words are appreciated. Obviously, we'll try not to change this behaviour in future versions so marking this as `wontfix` ;)
