### ISSUE TITLE
TIFF encoder has unique return type

### ISSUE THREAD

**Issue by anyusernameworks** [image-rs/image#1058]
This happens with the encoder for TIFF: image::tiff::TiffEncoder;

## Expected

`encode()` on any other encoder (bmp, ico, jpg, png) returns a `Result<()>`.

## Actual behaviour

`encode()` on the tiff encoder returns so-called `ImageResult<()>`

## Reproduction steps

https://docs.rs/image/0.22.3/image/tiff/struct.TiffEncoder.html
https://docs.rs/image/0.22.3/image/png/struct.PNGEncoder.html

**Comment by fintelia** [comment]
`ImageResult<()>` is actually IMO the right return type. The other encoders should be updated to return that as well. ImageError already implements From<io::Error>, so this should be hard change

**Comment by HeroicKatora** [comment]
This seems to be the interface complement of https://github.com/image-rs/image/issues/921
