### ISSUE TITLE
Is there an easy way to convert Image buffer formats? (RgbImage -> RgbaImage)

### ISSUE THREAD

**Issue by chitalian** [image-rs/image#1065]
Is it easy to convert from RgbImage to an RgbaImage. 

I mainly ran into this issue when creating an image using RbgImage pixels and loading them into a Frame.

**Comment by fintelia** [comment]
The interface is a bit messy, but this should work:
```rust
fn convert(img: RgbImage) -> RgbaImage {
    DynamicImage::ImageRgb8(img).to_rgba()
}

**Comment by chitalian** [comment]
> The interface is a bit messy, but this should work:
> 
> ```rust
> fn convert(img: RgbImage) -> RgbaImage {
>     DynamicImage::ImageRgb8(img).to_rgba()
> }
> ```

Thanks!
