### ISSUE TITLE
Design question: endianness during encoding

### ISSUE THREAD

**Issue by aschampion** [image-rs/image#1076]
I'm close to PRing 16 bit per channel support for colors, image buffers, and dynamic images. The last remaining feature for completeness is endian ordering during image encoding. For decoding, I implemented the byte reordering in formats' `ImageDecoder::read_image` so that it is always returned native endian (as is currently specified in the doc comment but was not implemented). (Reinterpreting the buffer from `u8` bytes to the `u16` type happens later in `decoder_to_vec`.)

However, for encoding, there is no equivalent interface trait. I could change the behavior of each encoder, but this would be a breaking change for people who were already using 16bpc `ColorType`s with the encoders by managing byte order manually.

The alternative would be introducing an `ImageEncoder` trait similar to `ImageDecoder`, whose only meaningful method would be `encode`. For most formats this would be a noop wrapper around the format encoder's `encode`, but for 16b capable formats this would do reordering when appropriate. In this way the format encoders would remain format-specific endianness interfaces, while `ImageEncoder` would provide a native endian input guarantee.

Before I implement this last piece, are there any objections to this design?

I'm only dealing with 16bpc I/O support in PNG and TIFF for this PR.

cc @fintelia since you've done most of the recent color refactoring.

**Comment by fintelia** [comment]
That all sounds reasonable; I like the idea of having an `ImageEncoder` trait
