### ISSUE TITLE
The jpeg encoder hardcodes the pixel density of the image 

### ISSUE THREAD

**Issue by lovasoa** [image-rs/image#1077]
I have a rust application that deals mainly with painting reproductions, for which some people find the density information embedded in JPEG files important.

The JPEG encoder of this crate [contains](https://github.com/image-rs/image/blob/master/src/jpeg/encoder.rs#L582-L584) a hardcoded [JFIF header](https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format#JFIF_APP0_marker_segment) for all the files it produces.

It would be nice if it were possible to customize the information in this header.

I am interested in the pixel density information, but the header can also contain an uncompressed thumbnail. It would be nice if it were possible to set it too.

**Comment by birktj** [comment]
Related to #1045 and #1067.
