### ISSUE TITLE
Encoding huge BMP panics/creates corrupted file

### ISSUE THREAD

**Issue by gralpli** [image-rs/image#1090]
I’m using _image 0.22.3_ with _rustc 1.39_ on 64-bit Windows 10.

```rust
let img = RgbImage::new(40_000, 40_000);
img.save_with_format("image.bmp", ImageFormat::BMP).unwrap();
```

This code panics in debug mode and creates an (assumably corrupted) file in release mode.

`thread 'main' panicked at 'attempt to multiply with overflow', bmp\encoder.rs:36:26`

The BMP format might not be able to store such a large image, but the encoder should at least return an `Err()` in both debug and release modes in such a case.

**Comment by HeroicKatora** [comment]
I agree with the assessment, the corrupted file write should never happen. Do you have the time for and are you interested in mentoring instructions for providing a PR that fixes this problem?
