### ISSUE TITLE
Yank version with "*" deps

### ISSUE THREAD

**Issue by kornelski** [image-rs/image#1092]
An old version of `image` has dependencies specified with `"*"` version requirement (`num = "*"`, `glob = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `image` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.2.0-alpha.1
```

**Comment by fintelia** [comment]
I don't think it is worth going through all the super old releases and yanking them. Version `0.2.0-alpha.1` is from 2014. It was released about _six months before Rust 1.0_ and already didn't compile by then
