### ISSUE TITLE
Convert bytes to image

### ISSUE THREAD

**Issue by Jasperav** [image-rs/image#1108]
[This is a reproduction project](https://github.com/Jasperav/imagebufferrust) (relevant code is also below). I want to convert a Vec<u8> to an image, but I get an error that the image has an unsupported image format.

```
use image::ImageFormat;

fn main() {
    {
        let pixels = image::open("test_image_png.png").unwrap().raw_pixels();
        let converted = image::load_from_memory(&pixels).unwrap();
        let converted_with_format = image::load_from_memory_with_format(&pixels, ImageFormat::Png).unwrap();
    }

    {
        let pixels = image::open("test_image_jpg.jpg").unwrap().raw_pixels();
        let converted = image::load_from_memory(&pixels).unwrap();
        let converted_with_format = image::load_from_memory_with_format(&pixels, ImageFormat::Jpeg).unwrap();
    }
}
```

**Comment by pix64** [comment]
'pixels' are is a vector of raw pixel data.

I believe load_from_memory_with_format(&pixels, ImageFormat::Png) is attempting to read the byte array as if it were a PNG image (e.g. something that starts with a PNG header and contains PNG image data. Not raw pixels.)

**Comment by Jasperav** [comment]
@pix64 ok, so I need to call an other method. I get a Vec<u8> type from a client request, which I want to transform to an image and later on save it on the file system. Do you know a method I can call to do that?

**Comment by fintelia** [comment]
I think [`ImageBuffer::from_raw(width, height, pixels)`](https://docs.rs/image/0.23.0-preview.0/image/struct.ImageBuffer.html#method.from_raw) is what you are looking for.

**Comment by Jasperav** [comment]
@fintelia the rust compiler want me to assign it an explicit type, I don't know which one to use, I just want to convert bytes to an image.

**Comment by aschampion** [comment]
Just use whatever type your image is. If it's RGB, you can use `let converted: ImageBuffer<Rgb<u8>, _> = ImageBuffer::from_raw(weight, height, pixels).unwrap();`, or since you're just converted from a `Vec` it's as simple as `let converted = RgbImage::from_raw(width, height, pixels).unwrap();`. There are types for `Gray`, `RGBA`, etc., too.

**Comment by Jasperav** [comment]
@aschampion Thanks, I think I got it working now :)

**Comment by roj1512** [comment]
How do we do the opposite? Like convert our image to bytes to be used in other places like sending it in an HTTP response?

**Comment by fintelia** [comment]
@roj1512 if you have a new question it is preferable to create a new issue/discussion thread. Though in this case, the second code snippit on the [docs.rs documentation page](https://docs.rs/image/0.24.3/image/index.html) shows how to do what you are trying to implement.

**Comment by roj1512** [comment]
Oh, I didn't notice that. Thanks a lot!
