### ISSUE TITLE
Documentation error in png.rs

### ISSUE THREAD

**Issue by Flobaer** [image-rs/image#1112]
The documentation in [src/png.rs](https://docs.rs/image/0.23.0-preview.0/image/png/struct.PNGReader.html) contains two errors: "posible" should be "possible" and "readed" should be "read". A pull request might be overkill for a small thing like this but I will create one nevertheless.

## Expected

The documentation should read (proposed changes highlighted in bold):
> This reader will try to read the png one row at a time, however for interlaced png files this is not **possible** and these are therefore **read** at once.

## Actual behaviour
The documentation reads (errors highlighted in bold):
> This reader will try to read the png one row at a time, however for interlaced png files this is not **posible** and these are therefore **readed** at once.

## Reproduction steps
Look at the documentation in [src/png.rs](https://github.com/image-rs/image/blob/0aaef55e4ec78c707f905c39e3c3daabc451cd5e/src/png.rs#L19) and see that it's grammatically incorrect.

**Comment by HeroicKatora** [comment]
Thank you for providing a PR right away. It's not really overkill.
