### ISSUE TITLE
WEBP: Excessive memory allocation for small inputs

### ISSUE THREAD

**Issue by dbrgn** [image-rs/image#1138]
When parsing certain WEBP files, the library allocates excessive amounts of memory. This could be misused for denial of service.

Here are a few input files found with the afl fuzzer in this repo:

|File|Input size|Max memory|
|---|---|---|
|[id:000000,sig:06,src:000032,op:flip1,pos:27.tar.gz](https://github.com/image-rs/image/files/4191366/id.000000.sig.06.src.000032.op.flip1.pos.27.tar.gz)|416 B|104.2 MiB|
|[id:000004,sig:06,src:000033,op:havoc,rep:64.tar.gz](https://github.com/image-rs/image/files/4191404/id.000004.sig.06.src.000033.op.havoc.rep.64.tar.gz)|429 B|62.9 MiB|
|[id:000005,sig:06,src:000109,op:havoc,rep:16.tar.gz](https://github.com/image-rs/image/files/4191406/id.000005.sig.06.src.000109.op.havoc.rep.16.tar.gz)|660 B|54.4 MiB|

Memory reports were generated with valgrind / massif:

    $ cd fuzz-afl
    $ cargo afl build --bin reproduce_webp
    $ valgrind --tool=massif --pages-as-heap=yes --massif-out-file=massif.out target/debug/reproduce_webp out/webp/crashes/id\:000000\,sig\:06\,src\:000032\,op\:flip1\,pos\:27

The generated file can be analyzed with tools like `massif-visualizer`.

**Comment by fintelia** [comment]
That decoder currently [decodes the frame at the same time as the file metadata](https://github.com/image-rs/image/blob/848b66735e6bbabae390b35a925e9cd8e881a855/src/webp/decoder.rs#L93). If it delayed until the user provided a buffer to read into (see ImageDecoder::read_image) then these denial of service attacks could be prevented because the amount of memory used would be known up front

**Comment by Shnatsel** [comment]
This no longer reproduces on `next-version-0.25` branch that switched to using `image-webp` for WebP decoding.

I'm not entirely sure why - perhaps the issue is fixed, or perhaps the decoder has diverged too much that these files get rejected for unrelated reasons.

**Comment by fintelia** [comment]
The files here contain headers indicating giant sizes (8224x12336, 3360x12336, and 16160x2386, respectively). The decoder used to allocate space up-front for the full image claimed in the header, which is probably what caused the previous behavior.

However, the WebP lossless format has extremely high compression ratios for solid color images. It only takes a couple dozen bytes to represent an arbitrarily large image. That means that there are entirely valid files even smaller than the examples above that still take a large amount of memory to decode. 

While `image-webp` still doesn't fully enforce memory limits for decoding, when used from `image` it  _does_ enforce image dimension limits. Thus I'm going to go ahead and close this.
