### ISSUE TITLE
WEBP: Excessively slow parsing of certain files

### ISSUE THREAD

**Issue by dbrgn** [image-rs/image#1139]
When running the afl fuzzer, I stumbled over this case. For the following 326 byte input file:

[id:000003,sig:06,src:000033,op:havoc,rep:16.tar.gz](https://github.com/image-rs/image/files/4191434/id.000003.sig.06.src.000033.op.havoc.rep.16.tar.gz)

...running the WEBP reproducer script in debug mode takes about 16 seconds on my machine to complete.

    $ cd fuzz-afl
    $ cargo build --bin reproduce_webp
    $ time target/debug/reproduce_webp \
        out/webp/crashes/id\:000003\,sig\:06\,src\:000033\,op\:havoc\,rep\:16
    
    real	0m15.797s
    user	0m15.620s
    sys	0m0.113s

During that time, according to valgrind+massif, it uses up to 119.6 MiB of heap memory.

This could be misused for denial of service.

Here's a valgrind call trace: [callgrind.out.48216.tar.gz](https://github.com/image-rs/image/files/4191443/callgrind.out.48216.tar.gz)

It can be analyzed with a tool like `kcachegrind`. I generated the trace like this (can take multiple minutes, valgrind is slow):

    $ valgrind --tool=callgrind target/debug/reproduce_webp \
        out/webp/crashes/id\:000003\,sig\:06\,src\:000033\,op\:havoc\,rep\:16

**Comment by kaj** [comment]
If it is slow and/or uses excessive memory in debug mode that can't be used for a denial of service, as the service should no be compiled in debug mode.  I tried it in release mode, and it completes in less than half a second.

According to "file", the image is 12298x4784 pixels, so a few milliseconds (or seconds in debug mode) might be expected.  Or is the file constructed in such a way that it should fail faster?   Firefox fails to display the image.

**Comment by HeroicKatora** [comment]
> 119.6 MiB of heap memory

That's not incredibly excessive (yet) but a good reminder that a general allocation limit across all formats is useful.

**Comment by dbrgn** [comment]
> If it is slow and/or uses excessive memory in debug mode that can't be used for a denial of service, as the service should no be compiled in debug mode.

Not directly, but if a small change in a small file can increase the runtime by a few orders of magnitude, that *might* indicate that a specially crafted file might result in something even worse :slightly_smiling_face:

If the runtime is expected and the underlying issue cannot be misused, then that's great and the issue could be closed. But the slow runtime might indicate a bug.

**Comment by HeroicKatora** [comment]
Pretty sure that `webp` is not specifically protected against resource exhaustion. If it were `png` this would be treated as a bug, other formats mostly used in browsers should probably be treated the same. I'd also fear this to be a bug, masking another bug :worried:

**Comment by fintelia** [comment]
Yeah, the code just parses the header and then [allocates a Vec](https://github.com/image-rs/image/blob/848b66735e6bbabae390b35a925e9cd8e881a855/src/webp/vp8.rs#L1128) large enough to hold an entire frame.

**Comment by HeroicKatora** [comment]
Does it then also initializes that `Vec` even though there is not enough data in the file? We should check if the relevant code might ignore read errors.

**Comment by dbrgn** [comment]
As commented in https://github.com/image-rs/jpeg-decoder/issues/133: If we know the input file size, can we know in advance whether the number of pixels is realistic or not? If yes, maybe two separate APIs could be provided, one streaming API (where it accepts any R: Read plus maybe a size limit) and one function that only accepts data with known size?

Maybe there could be other sanity checks being done before preallocating the buffer?

Unfortunately I'm not familiar with the WEBP internals, so I can't really judge the feasibility of those ideas...

**Comment by fintelia** [comment]
The ImageDecoder/image::Reader APIs already do a lot of that, it is just that the WEBP module is too simple to use take advantage of those protections

**Comment by fintelia** [comment]
I'm pretty sure this is caused by using a poorly optimized BitReader and huffman table implementation: #1956

**Comment by Shnatsel** [comment]
This no longer reproduces on `next-version-0.25` branch that switched to using `image-webp` for WebP decoding. I've also fuzzed the `image-web` crate, so if the issue was still present I would have probably caught it.

**Comment by fintelia** [comment]
This is probably the specific fix: https://github.com/image-rs/image-webp/pull/25
