### ISSUE TITLE
Dynamically disable use of rayon

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image#1153]
The `rayon` methods still panic when trying to create a thread pool on the `wasm` target. An issue  (#879) was previously closed by recommending disabling the feature but it is not always possible or feasible to do this, especially as it is a default feature and features are additive among all dependent of a version of a crate.

## Draft

Two basic alternatives to consider:

* Provide a dynamic flag to enable/disable the use of `rayon` or multi-threading in general. This should probably be exposed as a method so it can be propagated through the decoder crates. Setting the switch would affect all subsequent calls but not necessarily those in-progress. On the flip side, any part of the software might affect this flag and global state is generally discouraged.

* Add a method to `io::Reader` which implements this flag and sets it on every decoder. This does not affect *all* decoding calls and thus might require some interception/changes in those as well. In a scenario where the feature flag can not be disabled, I find it implausible that such a change can be made comprehensively.

**Comment by birktj** [comment]
Could another possibility be to add a feature  flag to explicitly disable `rayon`? Then you wouldn't have problems with additive features.

**Comment by RReverser** [comment]
> The `rayon` methods still panic when trying to create a thread pool on the `wasm` target.

FWIW this has changed nowadays, as Rayon has a single-threaded fallback on Wasm by default (so instead of panicking it now just performs regular single-threaded iteration), as well as has a way to enable proper multithreading on Wasm.

I believe this issue can therefore be closed.
