### ISSUE TITLE
Make a new point release that includes PR #1161

### ISSUE THREAD

**Issue by Aaron1011** [image-rs/image#1163]
See https://github.com/image-rs/image/pull/1161

`image` version 0.23.1 will not compile unless the updated version of `jpeg-decoder` is specified in the downstream crate's `Cargo.toml`. It would be useful to get a new point release of `image` so that this isn't necessary.

**Comment by HeroicKatora** [comment]
I'm slightly confused, the new version is SemVer compatible with the version specified previously and cargo _should_ generally select newest versions. Is your environment such that it does not?

**Comment by HeroicKatora** [comment]
Of course it doesn't really hurt to make the release, so shortly.
