### ISSUE TITLE
How to change image pixel formats?

### ISSUE THREAD

**Issue by kaimast** [image-rs/image#1170]
How does one convert an image in RGB format to one that is in RGBA format (where all alpha values are 1.0)? I feel like this must already be supported by this library somehow, I just cannot figure out how to do it.

At a high level, I am trying to use image to load a texture to be used in wgpu. Wgpu does not support 24-bit colors for various reasons. Ideally I would just convert the image on loading and not modify the image format on disk.

**Comment by HeroicKatora** [comment]
You can do this by going through `DynamicImage`. First, construct it with the variant of your source image and then use the `into_*` method to convert it to your destination format.

```rust
DynamicImage::ImageRgb8(image).into_rgba()
```

**Comment by kaimast** [comment]
Thanks @HeroicKatora !
