### ISSUE TITLE
Why DynamicImage::crop get &mut self?

### ISSUE THREAD

**Issue by mrlogick** [image-rs/image#1199]
```
extern crate image;
fn main() {
    let mut original = image::open("1.png").unwrap();
    let _cropped = original.crop(0, 0, 16, 16);
    original.save("2.png").unwrap();
}
```
Why _original_ needs to be mutable?
Does DynamicImage::**crop** modify _original_?
I'd like to remove the '**mut**':
`let original = image::open("1.png").unwrap();`
_2.png_ is not cropped, it's the same as _1.png_

**Comment by nabijaczleweli** [comment]
This is because `DynamicImage::crop()` uses `imageops::crop()` internally, and that takes a `&mut GenericImageView`. The fix is straightforward (though API-breaking), I'll open a PR soon.

**Comment by nabijaczleweli** [comment]
In current HEAD (3f0552038f3bfdbe00539e7904717381a427c6dc) and the next `0.23.x` release you can now use `DynImage::crop_imm()` instead.

This will be replaced with `DynImage::crop()` taking `&self` in the `0.24` release, just like you described it should've.
