### ISSUE TITLE
How can I implement a trait for `image::dynimage::DynamicImage`

### ISSUE THREAD

**Issue by hyousef-rusty** [image-rs/image#1209]
I'm trying to use [inline-python](https://github.com/fusion-engineering/inline-python) to get a pic from OpenCV camera, then manipulate this image with Rust, so I wrote the below code that catch the photo correctly, but once I try to handle it in Rust using `image` I get the below error:
```bash
error[E0277]: the trait bound `image::dynimage::DynamicImage: pyo3::pyclass::PyClass` is not satisfied
  --> src\main.rs:45:43
   |
45 |                 let img: DynamicImage = c.get("frame");
   |                                           ^^^ the trait `pyo3::pyclass::PyClass` is not implemented for `image::dynimage::DynamicImage`
   |
   = note: required because of the requirements on the impl of `for<'p> pyo3::conversion::FromPyObject<'p>` for `image::dynimage::DynamicImage`


```

The full code is:
```rust
#![feature(proc_macro_hygiene)]
use inline_python::*;

use image::{ImageFormat, GenericImageView, DynamicImage};
use web_view::*;
 
fn main() {
    let c = Context::new();

    web_view::builder()
    .title("Call open CV")
    .content(Content::Html(HTML))
    .size(800, 600)
    .user_data(())
    .invoke_handler(|_, arg| {
        match arg {
            "open" => {
                c.run(python!  {
                            import cv2
                            x = 2
                            cap = cv2.VideoCapture(0)
                            ret, frame = cap.read()
                            cv2.imshow('frame', frame)
                            cv2.waitKey(0)
                    })
            },
            "close" => {
            
                let img: DynamicImage = c.get("frame");

            },
            _ => (),
        }
        Ok(())
    }).run()
    .unwrap();
}

const HTML: &str  = r#"
<!doctype html>
<html>
    <body>
        <button onclick="external.invoke('open')">Run</button>
        <button onclick="external.invoke('close')">Close</button><br>
        <br>

    </body>
</html>
"#;
```

Can you help, Thanks.

**Comment by HeroicKatora** [comment]
The type `imgref::Img` is part of [`imgref`](https://docs.rs/imgref/1.4.3/imgref/), not `image`. And you can not implement a trait for a foreign type. You either need to ask the maintainer to implement that trait or define a small wrapper type and manually implement it for that wrapper.

**Comment by HeroicKatora** [comment]
Wrong button, sorry :smile: Let me know if you need a clarification for defining a wrapper type.

**Comment by hyousef-rusty** [comment]
Actually I was trying both packages, yours and imgref, I fixed my question now, can you help :)
Either implement that trait or guide me how to define a small wrapper type and manually implement it for that wrapper.

**Comment by HeroicKatora** [comment]
Sure. A wrapper type is a simple `struct` with a single member, the type you are wrapping (hence the name). This allows _your_ crate complete control over the trait impls which would not be otherwise possible for a foreign type. In this case, it allows you to annotate it with the proc-macro to automatically derive the desired trait impl (`pyo3::pyclass::PyClass`).

```rust
use pyo3::prelude::*;

#[pyclass]
pub struct YourImage {
    inner: DynamicImage,
}

// Later:
"close" => {
    let img: YourImage = c.get("frame");
    // If you need to access any of image's functions:
    let rgba = img.inner.to_rgba();
},
```

**Comment by HeroicKatora** [comment]
Hope this helps, I'm not an expert on PyO3 nor on the OpenCV bindings.

**Comment by hyousef-rusty** [comment]
Thanks, the code run, but panicked at the output:
```bash
thread 'main' panicked at 'Unable to convert `frame` to `rust_webview::YourImage`',
```

**Comment by HeroicKatora** [comment]
Your code example doesn't clarify what you use as `Context` but where you _set_ that you'll need to pass the wrapper instead of `DynamicImage`. Such as `c.set(YourImage { inner: img })`.

**Comment by hyousef-rusty** [comment]
Now I'm getting:
```bash
 c.set("frame", YourImage { inner: img });
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `pyo3::conversion::ToPyObject` is not implemented for `YourImage`
```

**Comment by HeroicKatora** [comment]
How you actually implement the traits of `pyo3`, you'll have to look up in that library. For example the documentation of [that trait](https://docs.rs/pyo3/0.9.2/pyo3/conversion/trait.ToPyObject.html) named by rustc here. I can only do guesswork here, and it's not very productive for either party.

**Comment by HeroicKatora** [comment]
Have you been able to make it work? Can this issue be closed?

**Comment by hyousef-rusty** [comment]
Hi thanks, sorry for not feedbacking you, yes I found a simpler way to handle it, as the generated output I got is a 3D array, so I handles it as numbers as shown in [#1210 ](https://github.com/image-rs/image/issues/1210)
