### ISSUE TITLE
Invalid TIFF files are produced

### ISSUE THREAD

**Issue by lovasoa** [image-rs/image#1216]
Trying to create a tif file of size 36132 x 44338 generates an invalid file. 

## Expected

An error should be raised when trying to create the file.

## Actual behaviour

It generates a file that is not a valid TIF. ImageMagick's identify, when given the file, returns

```
$ identify myfile.tiff 
identify: Sanity check on directory count failed, this is probably not a valid IFD offset. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/665.
identify: Failed to read directory at offset 2113469904. `TIFFReadDirectory' @ error/tiff.c/TIFFErrors/665.
```

## Reproduction steps

Create a large image buffer and try to save it as TIFF.

**Comment by lovasoa** [comment]
Here are the first 2MB of the corrupted file.

[myfile.tiff-trimmed.bin.zip](https://github.com/image-rs/image/files/4609930/myfile.tiff-trimmed.bin.zip)

**Comment by mdonoughe** [comment]
I'm not getting the same behavior with the latest code. If I create an Rgba8 image with those dimensions, I get `EncodingError { format: 
Exact(Tiff), underlying: Some(IntSizeError) }`. If I use L8 I get no errors and ImageMagick 7.0.10-Q16 says `TIFF 36132x44338 36132x44338+0+0 8-bit Grayscale Gray 1.49233GiB 0.000u 0:00.000`.
