### ISSUE TITLE
raw_pixels alternative?

### ISSUE THREAD

**Issue by jsomedon** [image-rs/image#1218]
How does one get raw pixels in current version? I see that raw_pixels() was there in 0.19.0, and since it's missing in current version, I guess it's deprecated?

Overall, I'm trying to pass vector of pixels to [get_palette() in color-theif](https://github.com/RazrFalcon/color-thief-rs/blob/bb7e77c22cfd1451e99ecbf0c2b11318e3961626/tests/test.rs#L20).

**Comment by fintelia** [comment]
If you match on `DynamicImage` you can get the underlying `ImageBuffer` for your image type. Then you can use the deref implementation to get a `&[u8]` / `&[u16]` or `ImageBuffer::into_raw` to get an owned Vec.

**Comment by julienfouilhe** [comment]
In case this is useful to others, I needed the same thing 3 years after on the day, and this is what I came up with (thanks @fintelia)

```rust
let img = image::load_from_memory(&img_bytes).unwrap();

                        let (buffer, color_format) = match img {
                            image::DynamicImage::ImageRgb8(buffer) => {
                                (buffer.to_vec(), color_thief::ColorFormat::Rgb)
                            }
                            image::DynamicImage::ImageRgba8(buffer) => {
                                (buffer.to_vec(), color_thief::ColorFormat::Rgba)
                            }
                            _ => unreachable!(),
                        };

                        let palette = color_thief::get_palette(&buffer, color_format, 10, 5)
                            .expect("Could not get palette from image");
```

**Comment by TygrisIQ** [comment]
Hi, if anyone is trying to load image in a specific format, you can try converting to that format then collect pixels in a Vector, Vec<u8> in case of rgb8

`let img = image::open(&path).unwrap();
let img = img.to_rgb8();
let data: Vec<u8> = img.pixels().flat_map(|pixel| vec![ pixel[0], pixel[1], pixel[2]])
.collect();
`

**Comment by fintelia** [comment]
At this point, the two relevant methods are:
* [`DynamicImage::as_bytes`](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.as_bytes) which solves the original issue of getting a byte slice from a `DynamicImage`, and
* [`ImageBuffer::into_raw`](https://docs.rs/image/latest/image/struct.ImageBuffer.html#method.into_raw) which returns the underlying `Vec<u8>` / `Vec<u16>` / `Vec<f32>` that stores the pixels. (For instance, `img.to_rgb8().into_raw()` is a more efficient way to get the same result as @TygrisIQ's code)
