### ISSUE TITLE
Resize function producing incorrect output dimensions

### ISSUE THREAD

**Issue by kriti0111** [image-rs/image#1220]
This happens in , when I try using  
   ```
    let img = image::open(input_file).unwrap();
    let scaled = img.resize(299, 299,FilterType:: CatmullRom);
   ```

## Expected

The size should've reduced to 299* 299

## Actual behaviour

![image](https://user-images.githubusercontent.com/30019069/82558510-659bbf80-9ba0-11ea-9538-8bd5be727c91.png)

Instead it's 299*224.  Similar behavior is observed with other images as well

## Reproduction steps
 The file used is the same file added in the example for scaledown. 
Tried using other filters but in vain. 
Provide source code, a repository link, or steps

**Comment by HeroicKatora** [comment]
Did you try encoding the image with a different format? Maybe this is a bug in the `jpeg` encoder.

**Comment by HeroicKatora** [comment]
You should use [`DynamicImage::resize_exact`](https://docs.rs/image/0.23.4/image/enum.DynamicImage.html#method.resize_exact) as `resize` states in its documentation that it preserves the aspect ratio. The coincidental naming similarity with `imageops::resize` which does _not_ preserve aspect ratio is unfortunate.

**Comment by kriti0111** [comment]
Used resize_exact. Works now. Thanks!
