### ISSUE TITLE
Documentation suggests using guess_format() but it's private

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#1231]
This happens in `image` from git, revision 092db1e21b3e8736711e2cbe1d9b5245613756c1

https://docs.rs/image/0.23.4/image/io/struct.Reader.html#method.open suggests using the following code, if I'm reading it right: 
```rust
image::io::Reader::open(path)?.guess_format();
```
but when I try it in image I get an error that the `guess_format()` method is private.

## Reproduction steps

```rust
fn main() -> std::io::Result<()> {
    let path = std::env::args().skip(1).next().unwrap();
    let image = image::io::Reader::open(path)?.guess_format().decode().unwrap();
    Ok(())
}
```

**Comment by HeroicKatora** [comment]
The link and text should be `with_guessed_format`, the exposed method of the builder struct.
