### ISSUE TITLE
"first two bytes is not a SOI marker" error on a valid JPEG

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#1233]
This happens in `image` from git, revision 092db1e21b3e8736711e2cbe1d9b5245613756c1

## Expected

Image decodes successfully

## Actual behaviour

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Decoding(DecodingError { format: Exact(Jpeg), underlying: Some(Format("first two bytes is not a SOI marker")) })', src/main.rs:3:18`

## Reproduction steps

![SarafiCloudLandSm3D](https://user-images.githubusercontent.com/291257/83200988-d1ec6500-a144-11ea-9866-579d7929dedd.jpg)

```rust
fn main() -> std::io::Result<()> {
    let path = std::env::args().skip(1).next().unwrap();
    let image = image::io::Reader::open(path)?.guess_format().decode().unwrap();
    Ok(())
}
```

**Comment by Shnatsel** [comment]
This could be JPEG/PNG format confusion as well since it fails on the first two bytes.

**Comment by Shnatsel** [comment]
Yup, this simply had the wrong extension. Decoding this with contents-based format guess works fine. Apologies for the false alarm.

**Comment by AlexanderProd** [comment]
> Yup, this simply had the wrong extension. Decoding this with contents-based format guess works fine. Apologies for the false alarm.

How did you do the contents-based format guess?

**Comment by fintelia** [comment]
@AlexanderProd Take a look at [`with_guessed_format`](https://docs.rs/image/latest/image/io/struct.Reader.html#method.with_guessed_format).
