### ISSUE TITLE
"no marker found where RST2 was expected" error on decoding a damaged-but-readable JPEG file

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#1235]
This happens in `image` from git, revision 092db1e21b3e8736711e2cbe1d9b5245613756c1

## Expected

Image decodes successfully

## Actual behaviour

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Decoding(DecodingError { format: Exact(Jpeg), underlying: Some(Format("no marker found where RST2 was expected")) })', src/main.rs:3:18

## Reproduction steps

![mountain lion 1](https://user-images.githubusercontent.com/291257/83201653-4378e300-a146-11ea-8632-da3bf730d134.jpg)

```rust
fn main() -> std::io::Result<()> {
    let path = std::env::args().skip(1).next().unwrap();
    let image = image::io::Reader::open(path)?.guess_format().decode().unwrap();
    Ok(())
}
```

**Comment by Shnatsel** [comment]
The image has some artifacts, the file is likely damaged but the C implementation tries to decode this anyway. Since it's an edge case it's probably low priority.

**Comment by VinayValsaraj-at** [comment]
Same issue here, really unclear as to how to debug this. Another example picture: 
![failing_image](https://github.com/image-rs/image/assets/100640618/55f8196c-5a93-480a-a062-80836cb692ad)

**Comment by Shnatsel** [comment]
[`zune-jpeg`](https://crates.io/crates/zune-jpeg) can handle such images instead of panicking, so #1877 will fix this. It is expected to ship in the next semver-breaking release.
