### ISSUE TITLE
"InvalidSignature" error on decoding a valid PNG file

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#1236]
This happens in `image` from git, revision 092db1e21b3e8736711e2cbe1d9b5245613756c1

## Expected

Image decodes successfully

## Actual behaviour

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Decoding(DecodingError { format: Exact(Png), underlying: Some(InvalidSignature) })', src/main.rs:3:18

## Reproduction steps

![1564517673 reallynxgirl_6eef30a0-6e73-41db-bc62-522aed309c61](https://user-images.githubusercontent.com/291257/83201993-f5181400-a146-11ea-9736-cfd7964731dd.png)

```rust
fn main() -> std::io::Result<()> {
    let path = std::env::args().skip(1).next().unwrap();
    let image = image::io::Reader::open(path)?.guess_format().decode().unwrap();
    Ok(())
}
```

**Comment by Shnatsel** [comment]
2 more samples with the same error
![1469884229 jazzlioness_lionking](https://user-images.githubusercontent.com/291257/83202089-2264c200-a147-11ea-8403-7ffac13b33ce.png)
![1462415029 jazzlioness_muffysarabisized](https://user-images.githubusercontent.com/291257/83202087-21339500-a147-11ea-9fbc-78aa9fd641a9.png)

**Comment by HeroicKatora** [comment]
@Shnatsel Whatever source you're using for these images it's not optimal in that, especially this Disney owned content, can't be included as a regular test file distributed with the library. If you're doing web scraping for this, may I suggest trying `https://pixabay.com/` for samples?

**Comment by HeroicKatora** [comment]
`file` identifies those images as `jpeg`. Those are not png files. The content aware format detection also finds that they are jpegs so I would say this is working as expected.

**Comment by HeroicKatora** [comment]
This program detecting the image file type from the file content (and not only its path) works fine:

```rust
fn main() -> std::io::Result<()> {
    let path = std::env::args().skip(1).next().unwrap();
    let _ = image::io::Reader::open(path)?
        .with_guessed_format()
        .unwrap()
        .decode()
        .unwrap();
    Ok(())
}
```

**Comment by Shnatsel** [comment]
Ah, that explains it. Closing then, sorry for the false alarm!
