### ISSUE TITLE
Inconsistent capitalization of PNG

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [image-rs/image#1258]
https://github.com/image-rs/image/blob/ff6c4d9de05bf71385ca043ab8d67ba66760b70f/src/png.rs

Publicly exposed types `PNGReader`, `PngDecoder`, `PNGEncoder` have inconsistent capitalization.

Changelog entry 0.23.0 suggests that the preferred form in this crate would be `Png`.

**Comment by HeroicKatora** [comment]
Good call, we indeed missed renaming some/most of the encoders.. Well, at least for types it would be possible to introduce aliases without a breaking change. Only removing the old, incorrectly capitalized names requires a major version bump. It is even possible to deprecated individual type aliases iirc.

There's also `git::{GifDecoder, Encoder}` which is inconsistent in its own right. We should address that as well.

**Comment by ZackJorquera** [comment]
Could I try to do this issue?

**Comment by HeroicKatora** [comment]
Sure, feel free to give it a shot :)
