### ISSUE TITLE
Rotated images can't be loaded

### ISSUE THREAD

**Issue by Aloso** [image-rs/image#1259]
This happens when trying to load a JPEG image with EXIF orientation metadata.

## Expected

Trying to load a rotated image **succeeds**. It's okay if the image has the wrong orientation, since I can still rotate it afterwards.

## Actual behaviour

Trying to load a rotated image **returns an error**.

## Reproduction steps

Try opening this image file:

![20160824_170638](https://user-images.githubusercontent.com/15658558/84580678-509a0100-add9-11ea-9b7d-f6fc09727b6a.jpg)

**Comment by fintelia** [comment]
Could you indicate what kind of error is returned? Is it some kind of "unsupported" error, or something else?

**Comment by Aloso** [comment]
The error is:

```rust
Decoding(DecodingError { format: Exact(Jpeg), underlying: Some(Format("spectral selection is not allowed in non-progressive scan")) })
```

**Comment by fintelia** [comment]
We've since switched `zune-jpeg`, so I'm going to mark this as closed. If there are still decoding failures, please create issues with that crate
