### ISSUE TITLE
Round-tripping JPEGs makes them darker

### ISSUE THREAD

**Issue by asonix** [image-rs/image#1260]
This happens in image 0.23.5

## Expected
The output JPEGs look like the input JPEGs

## Actual behaviour
The output JPEGs got darker with each round-trip, even with quality 100

## Reproduction steps
```rust
use image::ImageOutputFormat;
use std::{
    fs::File,
    io::{BufWriter, Write},
};

fn main() -> Result<(), anyhow::Error> {
    for i in 1..10 {
        let img = image::open(format!("image{}.jpg", i))?;
        let mut writer = BufWriter::new(File::create(format!("image{}.jpg", i + 1))?);
        img.write_to(&mut writer, ImageOutputFormat::Jpeg(100))?;
        writer.flush()?;
    }

    Ok(())
}
```

![image](https://user-images.githubusercontent.com/5304643/84604771-ee371400-ae5d-11ea-8eeb-860f0979175b.png)

**Comment by VVatashi** [comment]
I came across a similar problem when I tried to create image thumbnails with the image-rs.

Original image:

![1ef4ca43346344d7e69cb62438615c5f](https://user-images.githubusercontent.com/16176764/84916879-d4f5c800-b0e8-11ea-990f-3d5c562cf624.jpg)

Image created with ```Reader::open(src)?.with_guessed_format()?.decode()?.resize(360, 360, FilterType::Lanczos3).save(dst)?;```, which is noticeably darker:

![1ef4ca43346344d7e69cb62438615c5f_360](https://user-images.githubusercontent.com/16176764/84916902-daeba900-b0e8-11ea-8931-da962be323f4.jpg)

**Comment by HeroicKatora** [comment]
Both decoding and encoding perform a color conversion since jpeg uses a different color space than the image buffer requires. So it would be interesting to know which one of the is faulty (or both). Can you try saving it with a different format (`png` or `pnm` require no extra conversion) and view its color? It may be that some form of rounding (to `u8` precision) during the color computation loses luminosity.

**Comment by VVatashi** [comment]
There is no problem converting JPG to PNG, but it occur when converting PNG to JPG, so it looks like a bug in the encoder.

**Comment by HeroicKatora** [comment]
The `rgb->ycbcr` factors are wrong:

https://github.com/image-rs/image/blob/ff6c4d9de05bf71385ca043ab8d67ba66760b70f/src/jpeg/encoder.rs#L808-L810

Those are for digitl encoding _with_ headroom (such as for TV signals) but the JFIF specification uses an encoding that occupies all 256 levels (somewhat obviously). You'll find the correct factors [in this short description](https://www.w3.org/Graphics/JPEG/jfif.pdf) on page 3. It would be a good first PR/issue to address.
