### ISSUE TITLE
Iterators implement Clone

### ISSUE THREAD

**Issue by extrasharp** [image-rs/image#1266]
Iterators such as Rows and Pixels don't currently implement Clone or Debug.
Would be nice!

**Comment by extrasharp** [comment]
Okay I submitted a PR for Clone. https://github.com/image-rs/image/pull/1267
To have Debug for iterators, Subpixel, and thus Primitive, would also have to be Debug.

**Comment by HeroicKatora** [comment]
>  To have Debug for iterators, Subpixel, and thus Primitive, would also have to be Debug.

The `derive(Debug)` does not consider that extra bound but a manual impl could restrict itself to `where Pixel::Subpixel: Debug` without having to require that all primitives are `Debug`.

**Comment by extrasharp** [comment]
Oh cool, I see!
