### ISSUE TITLE
DXT -> BCN?

### ISSUE THREAD

**Issue by Josh015** [image-rs/image#1271]
I was just wondering if it would be a good idea to switch from ```Dxt*``` naming scheme to ```Bcn*``` in order to match Microsoft? Also, are there any plans to support ```BC4``` and ```BC5``` since ```L8``` and ```La8``` would map well to them?

**Comment by fintelia** [comment]
My preference would be to create a new `image-bcn` crate and move all the dxt encoding/decoding to there. We could then deprecate and eventually remove all the `Dxt*` code from `image` and retain only support for the DDS format.

I don't personally have plans to add support for other block compression formats, but PRs are welcome!

**Comment by HeroicKatora** [comment]
Starting the revision from a clean slate in a new crate sounds preferrable for me as well. Note it's possible retro-fit the current implementation to instead use a crate. Basically only implementation that we (sadly) can't readily change is the `DXTVariant` enum as it wasn't defined to be non-exhaustive (quite an oversight tbh). But we could add a _new_ enum instead and provide a converter from the old. That should leave many, if not all, interfaces intact. The DdsEncoder is entirely opaque as well. Also, we can defined _type_ aliases if we truly want to change the names without any major breakage (sadly we can't do the same for enum variants).

A new crate could expose many more internals, as long as it's not a public dependency of `image` the need for a stable interface isn't as large. It could experiment a lot more as well. At some point when format support gets detailed enough, we move them out into separate crates. For example, this happened with `png`, `gif`, `tiff`.

**Comment by Waelwindows** [comment]
I think it's better to map BC5 to R8G8, because not all textures use the "green" channel as alpha. e.g. normal maps

**Comment by fintelia** [comment]
@Waelwindows thanks for catching that! It probably isn't worth adding R8G8 as a format just to handle BC5, given that for decoder output La8 actually just means "a two channel format where even bytes are one channel and odd bytes the other". But you are right that the documentation should say that clearly somewhere so that users don't get confused
