### ISSUE TITLE
Add function to convert raw buffers of pixels

### ISSUE THREAD

**Issue by fintelia** [image-rs/image#1273]
Supporting every pairwise conversion between different `ExtendedColorType`s seems might be excessive, but a more limited set could be quite useful. Perhaps each `ExtendedColorType` variant could support conversion to a single `ColorType`?

For instance, in #1217 there was a request for YUYV -> RGB8 conversions and this would also be a more natural place for our current DXT encoding/decoding logic.

**Comment by HeroicKatora** [comment]
> Perhaps each ExtendedColorType variant could support conversion to a single ColorType?

That was part of the the goal of the orginal differentiation between those two types. However we hadn't gotten to a draft to 'typify' this assumption yet. In particular new `ColorTypes` should come with a type to represent them canonically. I don't think `YuYv->RGB8` is a very good example to start with as it heavily collides with the color space problems that will occur as part of the conversion.  :) However `BC?` to `RGB` should be okay if we assume that information about premultiplied alpha and exact primaries are out-of-band in any case, as this transformation does not perform a _conversion_ and does not rely on a standard color model.

**Comment by fintelia** [comment]
How would you feel about something like this:

```rust
enum ConvertError {
    BadAlignment,
    DestinationTooSmall,
}
trait Converter {
    /// Returns the (source, destination) color types that this converts between.
    fn color_types(&self) -> (ExtendedColorType, ExtendedColorType);
    /// Returns the require alignments for source and destination buffers.
    fn required_alignments(&self) -> (u8, u8);
    /// Perform the conversion.
    fn convert(&self, source: &[u8], destination: &mut [u8]) -> Result<(), ConvertError>;
}
trait InPlaceConverter: Converter {
    /// Perform the conversion in place. The buffer must be aligned to the larger of the alignment
    /// requirements for source and destination.
    fn convert_inplace(&self, buffer: &mut [u8]) -> Result<usize, ConvertError>;
}

/// A naive converter that converts any `ExtendedColorType` into some variant of `ColorType` without
/// considering colorspaces.
struct NormalizeConverter(pub ExtendedColorType);
impl Converter for NormalizeConverter {
    ...
}
```

**Comment by HeroicKatora** [comment]
```
    /// Returns the require alignments for source and destination buffers.
    fn required_alignments(&self) -> (u8, u8);
    /// Perform the conversion.
    fn convert(&self, source: &[u8], destination: &mut [u8]) -> Result<(), ConvertError>;
```

This seems fairly underspecified. The sizes, as width and height, might differ when converting macro pixels to individual ones. Also I think the converter should be informed of those before if the caller wants to allocate a destination buffer based on the dynamic requirements of the conversion. However I do quite like the absence of types. We will want to have some interface with `EncodableLayout` instead but not on the trait itself to keep that object safe.

**Comment by fintelia** [comment]
Good point about missing the width. Because we also have the buffer lengths, the height could in inferred based on `source.len() / bytes_per_row` (assuming that we define formats with to have each row start on a byte boundary even if `bits_per_pixel < 8`, which would be good for everyone's sanity):
```rust
// destination_row_pitch is the number of bytes between the start of successive rows
//  in the destination buffer. Must be divisible by the destination buffer's required alignment.
fn convert(&self, source: &[u8], source_width: usize, 
           destination: &mut [u8], destination_row_pitch: usize) -> Result<...>;
```

For most buffer requirements, I'd prefer if they could actually be defined on `ExtendedColorType` and apply throughout the library. The reason I made alignments an exception is that I could see some converters wanting larger alignments than strictly required for the format, like say RGBA wanting pixels to be 4-byte aligned to make the implementation faster/easier to write.
