### ISSUE TITLE
Adding XPM Decoder/Encoder?

### ISSUE THREAD

**Issue by Josh015** [image-rs/image#1274]
I wanna try my hand at adding an XPM decoder & encoder to this crate, since it's a simple and well-defined old format. Do you think it's worth it?

**Comment by HeroicKatora** [comment]
I would start new decoders as a separate crate. That is, unless you benefit greatly from the existing `ImageFormats` and `ImageBuffer` but given how opinionated (or more bluntly–strange) the format handles colors I wouldn't suppose so. At some point I wanted to move the similar netbpm formats out into their own crate as well but never got to it. You should be able to create new repositories in the organization :slightly_smiling_face:

**Comment by Josh015** [comment]
So I assume that means I need to make "image-xpm" repository? Also, I noticed that crates.io already has an "xpm" crate for some "package manager" project that hasn't been touched in 4 years. Any suggestions on how I should name it?

**Comment by HeroicKatora** [comment]
`image-xpm` seems fine. We can defer the decision until the first release though, if you think there might be a better name.

**Comment by Josh015** [comment]
Well, isn't ```image-<extension>``` the naming convention you guys are using for your compartmentalized image type decoder+encoder crates?

**Comment by HeroicKatora** [comment]
To provide a concrete answer: It has been recently. Most of the older crates started without the prefix since in 2015 names were available plenty. I'd argue there is no reason that would require claiming the global without prefix and this will likely be more consistent going forward.
