### ISSUE TITLE
Placing images into an ImageBuffer?

### ISSUE THREAD

**Issue by kangalioo** [image-rs/image#1277]
Is it possible to place an image into an existing `ImageBuffer`? Ideally, I'm looking for something like `ImageBuffer::insert(&mut self, impl GenericImageView, x: u32, y: u32)`

Overall, I'm trying to assemble multiple small images into one big image.

I've been searching in the docs for the last 5-10 mins but haven't found anything, hence I'm asking here

**Comment by HeroicKatora** [comment]
Looks like you're searching for exactly [`GenericImage::copy_from`](https://docs.rs/image/0.23.6/image/trait.GenericImage.html#method.copy_from).

**Comment by kangalioo** [comment]
That's it, thanks
