### ISSUE TITLE
How to obtain a color from XY coordinate?

### ISSUE THREAD

**Issue by 3NdR1m** [image-rs/image#1281]
I need to obtain an I8 for the R, G & B channel of a pixel at a given xy position.

Which type/trait provide such feature and how can I do it?

**Comment by fintelia** [comment]
There is [`GenericImageView::get_pixel`](https://docs.rs/image/0.23.7/image/trait.GenericImageView.html) which for an 8-bit RGB image should return an [`Rgb<u8>`](https://docs.rs/image/0.23.7/image/struct.Rgb.html). Rgb is a one element struct containing a `[u8; 3]` of the three components in sequence. Thus `pixel.0[0]` would be the red component, `pixel.0[1]` the green component and `pixel.0[2]` the blue component.

**Comment by 3NdR1m** [comment]
Thanks for the reply. That's great, but what if I don't know the color type? Sometime the incoming picture might be Rgba or something else. Is there a way to extract RGB no matter the color type?

**Comment by fintelia** [comment]
If you have a DynamicImage, you can use into_rgb() to convert it to RGB and then use the get_pixel function. Another lighter weight option is to match over the different variants of DynamicImage, grab the pixel for each, and do the appropriate conversion.

**Comment by 3NdR1m** [comment]
That'll do it. Thanks!
