### ISSUE TITLE
Some time will occur `Err` value: Decoding(DecodingError { format: Exact(Png), underlying: Some(Format("unexpected EOF"))

### ISSUE THREAD

**Issue by adminSxs** [image-rs/image#1282]

**Comment by HeroicKatora** [comment]
This error tells you that the library thinks the image is too short to be valid. Without any example of a failing image, this is completely non-actionable.

**Comment by HeroicKatora** [comment]
Closing because it has no reproduction or other information that could allow us to even validate this issue.

**Comment by louy2** [comment]
I have hit this error on an Discord avatar. Unfortunately I neglected to preserve the image due to privacy.
