### ISSUE TITLE
Not found variant in 'image::ColorType'

### ISSUE THREAD

**Issue by murka** [image-rs/image#1287]
error[E0599]: no variant or associated item named `Gray` found for enum `image::ColorType` in the current scope

encoder.encode(&pixels, bounds.0 as u32, bounds.1 as u32, ColorType::Gray(8));

variant or associated item not found in `image::ColorType`

error: aborting due to previous error

**Comment by HeroicKatora** [comment]
This is referring to an outdated variant from version `0.22`. Since `0.23` the corresponding variant is now named [`L8`](https://docs.rs/image/0.23.7/image/enum.ColorType.html#variant.L8). This is a new major version so it shouldn't get implictly updated.
