### ISSUE TITLE
Resource Exhaustion using manipulated header

### ISSUE THREAD

**Issue by mettke** [image-rs/image#1302]
I'm currently testing this library (0.23.8) for possible resource exhaustion vulnerabilities. So far I have the following results (I will test the other formats eventually):

|Format|Prevents Exhaustion|
|---|---|
|PNG|✅|
|JPEG|✘|
|GIF|✅|
|BMP|✅|

## Expected

In my test, I manipulate the header of the image to make the resolution artificially higher than it is (from 512px to 65_500px). This should not lead to increased memory usage to make sure that an attacker is not able to crash a server (OOM) by submitting a malicious image file.

## Actual behaviour

Some formats use significantly more memory then they should opening up the possibility for resource exhaustion when used in infrastructure which allows the user to submit custom image files. 

## Reproduction steps

I cannot provide image files for reproduction to make sure that no one accidentally uses them. There is however a repo here (https://github.com/mettke/sec_tool_belt) which contains the binary `mean_image`. It can create an image for a given format to test resource exhaustion. 

While testing this library I used the `::image::open` function.

## RAM Usage

|Format|Normal|Tampered|
|---|---|---|
|PNG|278M|278M|
|JPEG|291M|10 GB (OOM)|
|GIF|277M|270M|
|BMP|269M|273M|

**Comment by HeroicKatora** [comment]
Thanks for doing these but you may want to recheck your methodology. I'm fairly certain that `gif` is _not_ yet secure against resource exhaustion: see #1052
