### ISSUE TITLE
Add sponsor link in repo

### ISSUE THREAD

**Issue by repi** [image-rs/image#1306]
Would recommend adding a `.github/FUNDING.yml` file to this repo, and the other image-rs repos that link to the [image-rs OpenCollective page](https://opencollective.com/image-rs) so more individuals and organizations can find it and help sponsor development.

This is how rust-analyzer has it set up: https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/FUNDING.yml

Would also enable tools like [cargo-fund](https://github.com/acfoltzer/cargo-fund) to find that this project is seeking sponsorship when devs run it on the project (and a dependency on any of the image crates is found), which would be really nice.

**Comment by fintelia** [comment]
I think the main question to address first is what the funding would be used for. Are there contributors who are interested in being funded to work on image-rs? If so, I see no reason not to indicate that somewhere so that they can connect with sponsors interested in funding development.

**Comment by repi** [comment]
> I think the main question to address first is what the funding would be used for. Are there contributors who are interested in being funded to work on image-rs?

Well, isn't that question already answered as there already is an existing [image-rs OpenCollective sponsorship project](https://opencollective.com/image-rs)? :)

Unless that sponsorship project on OpenCollective is not associated with this project? In that case that should also be pointed out as it sure sounds like it is right now.

My question here was just a recommendation to link to it in the repo as well so it becomes discoverable.

**Comment by HeroicKatora** [comment]
No, i definitely set it up so it is related ;) I'm just afraid I didn't quite have the throughput to plan anything big with any larger amount..

Thanks you for the contribution, it will go towards the costs for the website, domain name.
