### ISSUE TITLE
Provide access to GIF encoding speed parameter

### ISSUE THREAD

**Issue by Rimpampa** [image-rs/image#1309]
This crate depends on the [gif](https://docs.rs/gif/0.10.3/gif/) crate which, in turn, depends on [color_quant](https://docs.rs/color_quant/1.0.1/color_quant/). The latter one is used to generate the best color palette whenever a GIF frame gets encoded, and does that (if I understood correctly) by training a neural-network on the image and the quality of the result depends directly by the time it takes to train it.

Now, the problem is that while the `gif` crate exposes this speed parameter that controls the quality, the `image` crate does not, and, even worse (depends on the point of view), it always uses the best quality (longer training time).

I personally don't see why it shouldn't be accessed and also it shouldn't be that difficult to add: b looking at the code it seems like it could be added either directly to the [Encoder](https://docs.rs/image/0.23.8/image/gif/struct.Encoder.html) struct, as a field that will be initialized with the other parameters when constructing the object;

or, better in my opinion, it could be added in the `encode_*` methods of the `Encoder` struct:

**Note** the use of `from_rgb[a]_speed` instead of `from_rgb[a]`
```
pub fn encode(..., speed: i32) -> ImageResult<()> {
    ...
    match color {
        ColorType::Rgb8 => self.encode_gif(Frame::from_rgb_speed(width, height, data, speed)),
        ColorType::Rgba8 => {
            self.encode_gif(Frame::from_rgba_speed(width, height, &mut data.to_owned(), speed))
        },
        ...
    }
}

pub fn encode_frame(..., speed: i32) -> ImageResult<()> {
    let frame = self.convert_frame(..., speed)?;
    ...
}

pub(crate) fn convert_frame(..., speed: i32) -> ImageResult<Frame<'static>> {
    ...
    let mut frame = Frame::from_rgba_speed(..., speed);
    ...
}
```

Also it could be added another set of functions that end in _speed (as in the gif crate) in order to leave the other one as they are.

## Side Note

The best would be to be able to provide the palette to use (either for the whole gif or for just one frame) as in some cases it is already known.

To give an example, when dithering the color palette is already known as it is used by the algorithm, thus it's a waste of time training a neural-network to generate another one that is the same.

**Comment by Tuetuopay** [comment]
Hi @Rimpampa! Just saw this, and this has just been added by #1394 :)
