### ISSUE TITLE
Unexpected performance when decoding PNG

### ISSUE THREAD

**Issue by eseaflower** [image-rs/image#1312]
I am not sure this is an issue with `image-rs` or somehting more general. My issue is that the decoding performance drops 5-6 times if a do a `thread::sleep` prior to doing the decoding. Here is how to reproduce (test.png is a 512x512 image):
```
use std::{path::Path, thread, time::Duration};

fn main() {
    let p = Path::new(r"test.png");
    let buffer = std::fs::read(p).unwrap();

    for _ in 0..10 {
        let measure = std::time::Instant::now();
        let _ = image::load_from_memory_with_format(&buffer, image::ImageFormat::Png)
            .unwrap()
            .into_rgba();
        println!("Image creation took {} ms", measure.elapsed().as_millis());
    }

    println!("=== Begin thread::sleep in loop ===");

    for _ in 0..10 {
        thread::sleep(Duration::from_millis(100));

        let measure = std::time::Instant::now();
        let _ = image::load_from_memory_with_format(&buffer, image::ImageFormat::Png)
            .unwrap()
            .into_rgba();
        println!("Image creation took {} ms", measure.elapsed().as_millis());
    }
}

```
Sample output:

```
erik@EriksNya /m/e/w/decode_perf> ca r --release
    Finished release [optimized] target(s) in 0.05s
     Running `target\release\decode_perf.exe`
Image creation took 4 ms
Image creation took 4 ms
Image creation took 5 ms
Image creation took 4 ms
Image creation took 5 ms
Image creation took 4 ms
Image creation took 4 ms
Image creation took 4 ms
Image creation took 4 ms
Image creation took 4 ms
=== Begin thread::sleep in loop ===
Image creation took 23 ms
Image creation took 21 ms
Image creation took 30 ms
Image creation took 24 ms
Image creation took 24 ms
Image creation took 23 ms
Image creation took 24 ms
Image creation took 24 ms
Image creation took 24 ms
Image creation took 24 ms
erik@EriksNya /m/e/w/decode_perf>
```

As I said I am not sure this is an issue with `image-rs` or something more general with `thread::sleep`. I am new to Rust so I thought I would ask here, since I encountered the behavior when using this crate.

I am running on Windows 10
```
rustc --version => rustc 1.44.1 (c7087fe00 2020-06-17)
image = "0.23"
```

**Comment by HeroicKatora** [comment]
That is indeed unexpected. I would _guess_ this is something more general, like the scheduler decreasing the process' priority when it notices it doesn't run for a time. Or the default allocator returning unused pages to the OS after a while. Reading png files requires a few allocations, particular one large one very early for the image buffer, which would definitely block if it doesn't complete fast. Can you try changing the allocator to [`jemallocator`](https://crates.io/crates/jemallocator)?

**Comment by eseaflower** [comment]
I will answer myself :-). I actually found an answer on StackOverflow (https://stackoverflow.com/questions/56922289/why-does-sleeping-increase-the-execution-time-of-an-independent-piece-of-code-th/56922611#56922611).
I have just verified that by adding
```
let _ = thread::spawn(|| {
        loop {
            thread::yield_now();
        }
    });
```
the performance is the same regardless of the `thread::sleep`.

Sorry for posting...

**Comment by HeroicKatora** [comment]
@eseaflower No worries.
