### ISSUE TITLE
Content based file type guessing

### ISSUE THREAD

**Issue by jerry73204** [image-rs/image#1318]
The impl of [ImageFormat::from_path](https://docs.rs/image/0.23.10/image/enum.ImageFormat.html#method.from_path) calls an internal method ([code](https://github.com/image-rs/image/blob/6f84d86302e63fdd80899333e5b5aeb6e278354c/src/io/free_functions.rs#L231-L260)) that guesses the file type by filename extension. It could produce false results in case of a PNG file named `xxx.jpg`. The [image::open()](https://docs.rs/image/0.23.10/image/fn.open.html) calls the method and produces error when it guesses the wrong type. Do you consider the content-based method? We already have a [tree\_magic](https://github.com/aahancoc/tree_magic/) crate that does the job.

**Comment by fintelia** [comment]
The [`io::Reader`](https://docs.rs/image/0.23.10/image/io/struct.Reader.html) interface supports guessing the format based on the initial bytes of the file. Is that what you are looking for?

**Comment by jerry73204** [comment]
Yes, I missed it. Sorry for inconvenience.

**Comment by HeroicKatora** [comment]
It appears somewhat common to be classified as a documentation deficiency. Alternatively, I think we could slowly start to deprecate the free functions in the root and nudge people over to `io::Reader`.
