### ISSUE TITLE
JPEG formatted image not getting Resized

### ISSUE THREAD

**Issue by Javeed-JargonHandlers** [image-rs/image#1321]
I am trying to resize the images and i am able to resize PNG formatted files.

But i am unable to resize the JPG formatted images. I have compiled the script using this documents --> https://blog.stackpath.com/image-manipulation/

This page isn’t working "image.flexifunnels.com" is currently unable to handle this request.
HTTP ERROR 500

## Actual behaviour

PNG --> https://image.flexifunnels.com/resize?url=https://img.pngio.com/download-sample-png-image-for-demo-use-natural-landscaping-png-800_500.png&w=450&h=300&exact

JPG -> https://image.flexifunnels.com/resize?url=https://mdkemz.flexifunnels.com/images/LNjr5FIuo5_370_cb2.jpg&w=250&h=150&exact

**Comment by HeroicKatora** [comment]
Can't reproduce, works for me. The error is http, there is no indication that `image` is responsible for it.
