### ISSUE TITLE
About `i32::from` used across the source code

### ISSUE THREAD

**Issue by TianyiShi2001** [image-rs/image#1337]
I saw abundant `i32::from` in the source code. Is there a particular reason to prefer it over the `.. as i32` syntax?

**Comment by HeroicKatora** [comment]
Yes, casts with `as _` are discouraged as they are less type safe. I think clippy even complains about it?
For example you can cast any `0usize as 32` but such a conversion is lossy. To make it clear that the conversion is _not_ of such a class, we use the explicit `From::from` conversion which can never be loss.y

**Comment by TianyiShi2001** [comment]
Thank you for the explanation!
