### ISSUE TITLE
Better API design

### ISSUE THREAD

**Issue by nwin** [image-rs/image#134]
I really don't like our current API. I has a lot  of code-duplication because of this DynamicImage enum and is not very ergonomic. At the moment this is ok but just image what would happen if we finally add 16bit and CYMK image types. This would blow up our enum to at least 20 variants.

Could a trait + associated type help with this?

**Comment by nwin** [comment]
I was thinking about such an approach to generalize the decoders and make them more flexible. I created a Factory trait in oder to be able to provide options and make sure that you set them before you started reading the file. What do you think?

    PNGDecoder::new(File::new(...))
        .set(HasMagic(true))
        .read_info().map(|decoder| decoder.read_image())

Stub implementation:

    use modifier::{Modifier, Set};
    
    trait DecoderFactory: Set {
        type ReaderType;
        /// Contructs the reader factory
        fn new(reader: Self::ReaderType) -> Self;
        
        /// Reads the file metadata an returns an image decoder
        fn read_info(self) -> IoResult<ImageDecoder>;
        
        // The following method make sure that every decoder accepts some minimal
        // properties.
        
        /// Tells the decoder whether the magic bytes have already been read.
        fn has_magic(&self, has_magic: bool);
        
    }
    
    /// Property whether the magic byte have already been read.
    struct HasMagic(bool);
    
    impl Modifier<DecoderFactory> for HasMagic {
        fn modify(self, factory: &mut DecoderFactory) {
            let HasMagic(val) = self;
            factory.has_magic(val);
        }
    }
    
    trait ImageDecoder {
        fn read_image(&self) -> IoResult<DecodingResult>;
    }

**Comment by bvssvni** [comment]
I would prefer a struct `DecoderFactory<T>` instead of a trait, and use [piston-quack](https://github.com/pistondevelopers/quack) which does the same thing, same look (based on rust-modifier) but solves some issues regarding generic constraints and reexported property types.

Implemented directly on the concrete type (replacing `Modifier` with `SetAt`):

```Rust
impl SetAt for (HasMagic, PNGDecoder) {
    fn set_at(HasMagic(val): HasMagic, decoder: &mut PNGDecoder) {
        decoder.has_magic(val);
    }
}
```

Then lift `SetAt` over `DecoderFactory`:

```Rust
impl<T, U> SetAt (T, DecoderFactory<U>) DecoderFactory<T>
     where
         (T, U): Pair<Data = T, Object = U> + SetAt
{
    fn set_at(val: T, obj: &mut DecoderFactory<T>) {
        <(T, U) as SetAt>::set_at(val, &mut obj.decoder);
    }
}
```

Other things:

* `ReaderType` could be a generic parameter (perhaps with `Reader` constraint?)
* Meta data could be a `GetFrom` property
* Rename `read_info` to `image_decoder`, because mixing these two steps is a bit confusing

Otherwise, I think it is good idea, but perhaps we should wait because "quack" is currently experimented with in piston-graphics and Conrod. We don't completely understand all the pros and cons. I wouldn't use rust-modifier though, because it has problems with generics. If we give it some time then we might have a good library that does this properly. If we do something now, the route I would go is to add some builder methods directly that can be replaced afterwards.

**Comment by nwin** [comment]
Decoder factory can’t be a struct because different decoders might have different options (this is especially important for the Encoder equivalent) and thus there is no generic way of creating a ImageDecoder from the Factory.

I didn’t consider quack because it both lacks tests and documentation such that I had no idea how to use it. ;)

**Comment by bvssvni** [comment]
Haha, then it looks like quack needs to pull it stuff together and become a decent library!

I didn't understood what you meant with different options, if those are limited to `DecoderFactory`?

**Comment by nwin** [comment]
It does not make sense to set a compression method for a PNG encoder. You need a factory per de/encoder and for this you need a trait.

**Comment by bvssvni** [comment]
`.set(CompressionMethod)` won't compile with `PNGEncoder` unless the `SetAt` (or `Modifier` in rust-modifier) is implemented on `PNGEncoder`, even if this is lifted over a struct.

**Comment by nwin** [comment]
Yes, I probably should have written PNGDecoderFactory or something like that in my example.

**Comment by bvssvni** [comment]
Ah, now it makes more sense.

**Comment by nwin** [comment]
It sounds complicated but otherwise you would have a set of method you would have to call in the correct order…by this the compiler prevents missuse but we could still provide a convenience method like load_image(Path) -> ImageBuffer…

**Comment by nwin** [comment]
Though I probably our design is not good for streaming images like in a browser…

**Comment by bvssvni** [comment]
Assume we add concrete types for each encoder/decoder like `PNGDecoderFactory` or `PNGEncoderFactory. All properties/modifiers could be implemented directly on those types. If there are properties shared by all encoder/decoder then those could be added as `where` clauses and the methods like `has_magic` can be default trait methods. This would save us for the confusion whether a property is implemented for a trait or for a concrete type.

**Comment by bvssvni** [comment]
I this in piston-graphics https://github.com/PistonDevelopers/graphics/blob/master/src/relative.rs#L162-L165 , but here the traits are auto implemented. For this case, it is kind of interesting that the trait would "inherit" the properties while at the same require the objects to implement the trait.

**Comment by FredrikNoren** [comment]
Any progress on this one? I'm using this library for some OpenGL stuff, in which I use f32 textures for some thing. But since the DynamicImage doesn't support f32s (only u8) I have to write my own DynamicImage enum to wrap everything.

**Comment by nwin** [comment]
No progress yet, but for your issue one wouldn’t need a new API. One could probably just implement

```rust
impl<T:  Pixel> FromColor<T<u8>> for T<f32> {
    ...
}
```
and work on ImageBuffer.

PRs are welcome. ;)

**Comment by birktj** [comment]
Since there hasn't been any discussion on this exact issue since 2015, I am going to close it over the  newer and more specific issues about the api of this library.
