### ISSUE TITLE
Inconsistency with DynamicImage conversion methods

### ISSUE THREAD

**Issue by aloucks** [image-rs/image#1347]
The `as` methods (e.g. `as_rgba8`, `as_luma16`) all contain the component bit depth, while the `into` and `to` method do not. For example, there's no way to unwrap to `Luma<u16>` without a match statement.

I'd like to propose deprecating all of the current `into` and `to` methods in favor of adding new ones with the explicit bit depth (e.g. have both `into_luma8` and `into_luma16`). 

Finally, some signatures return type aliases where as others do not. I think the type aliases are less helpful than just showing that these all return `ImageBuffer` with with different pixel types.

I'd like to put in a PR for these changes but wanted to gather feedback first.

**Comment by fintelia** [comment]
That all sounds reasonable to me
