### ISSUE TITLE
Exposing Raw Decoder Fields

### ISSUE THREAD

**Issue by nickbabcock** [image-rs/image#1353]
I would like to be able to access `BmpDecoder::palette` after decoding a BMP.

My specific use case for this functionality is the BMPs I work with are not self contained. There is an accompanying text file that states "every pixel that references index 0 of the BMP color palette maps to grasslands, index 1 is hills, etc", so knowing what palette index a pixel refers to is critical.

While this use case is esoteric, the notion of exposing the decoder fields seems like it would apply to the other decoders and other fields.

## Draft

Adding getter functions or marking the field as `pub` would be two possible approaches

I'm fine with this issue being closed as being inappropriate for a high level crate like this, but I wanted to create an issue so that thoughts on this issue are known

**Comment by fintelia** [comment]
The approach that many other decoders use is to have a specialized crate for just that format and then provide a common abstraction here.

**Comment by nickbabcock** [comment]
Understood, I ended up writing a bmp decoder that exposed everything to the user, so I'll go ahead and close this.
