### ISSUE TITLE
enumerate_pixels_mut() 100 times slower than for loops

### ISSUE THREAD

**Issue by arnabanimesh** [image-rs/image#1377]
This happens in `image v0.23.12`

## Expected

`for` loop performance and `enumerate_pixels_mut` should have similar performance.

## Actual behavior

`for` loop was 100 times faster than `enumerate_pixels_mut`.

# Hyperfine output

```
Benchmark #1: forloop.exe                            0
  Time (mean ± σ):      16.2 ms ±   0.9 ms    [User: 1.6 ms, System: 3.9 ms]                                           0
  Range (min … max):    15.2 ms …  20.9 ms    111 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Benchmark #2: enumerate.exe
  Time (mean ± σ):      1.558 s ±  0.006 s    [User: 2.7 ms, System: 5.5 ms]                                           0
  Range (min … max):    1.550 s …  1.565 s    10 runs

Summary
  'forloop.exe' ran 96.23 ± 5.14 times faster than 'enumerate.exe'
```

## Reproduction steps

Run [forloop code](https://gist.github.com/arnabanimesh/8d7dc86179a673614cbda0d82515d15a/raw/94b19812fecc54ae20aac092e5805b1980acd2f1/forloop.rs) and [enumerate code](https://gist.github.com/arnabanimesh/8d7dc86179a673614cbda0d82515d15a/raw/94b19812fecc54ae20aac092e5805b1980acd2f1/enumerate.rs), and see for yourself.

**Comment by HeroicKatora** [comment]
In the `enumerate_pixels_mut` code there is an `eprintln` for every single pixel while the for-loop has one for every row instead. I'd expect the syscall overhead to dominate the memory assignment by several orders of magnitude, and removing the print completely indeed brings down the runtime to 5ms on my machine with the same time as the for-loop. I won't benchmark in more details. Also note that the printing is an optimization hazard even in the outer loop. It might cause the eviction of the inner loop from the instruction cache which costs several cycles at the start of every entry into it, costing ~2ms total in my experiment.

**Comment by arnabanimesh** [comment]
How to print progress then? Any ideas?

**Comment by HeroicKatora** [comment]
@arnabanimesh Two ideas:

* In the `enumerate_pixels_mut`, print every nth loop where `n = width`. Then this does an equivalent amount of printing as the other variant.
* Use multithreading, and have a dedicated thread modify a shared atomic to pass progress. This is incredibly cheap comparsed to the system call in the critical loop but requires setting up a second thread. Another advantage is that you control the refresh rate of your status message and control it independent of the pixel iteration loop.

**Comment by arnabanimesh** [comment]
Thanks 😁
