### ISSUE TITLE
API ergonomics for 16bit

### ISSUE THREAD

**Issue by virtualritz** [image-rs/image#1389]
I would like to be able to pass an `[u16]` buffer (`quantized_pixel_data` in the example below) to an encoder; PNG in my case.
There is only one variant of `PngEncoder::encode()` which takes an `[u8]`.

```rust
        image::png::PngEncoder::new(&mut buffer)
            .encode(
                // Woot?
                unsafe {
                    &*core::ptr::slice_from_raw_parts(
                        quantized_pixel_data.as_ptr() as *const u8,
                        quantized_pixel_data.len() * 2,
                    )
                },
                width as _,
                height as _,
                image::ColorType::Rgba16,
            )
            .unwrap();
```

**Comment by HeroicKatora** [comment]
That was a concious decision. Otherwise, introducing any new channel type support would require a breaking change in the interface such as adding a new method. The separate interface would only be callable in a very specific circumstance which honestly isn't that great of an interface. 

Instead, we rely on the fact that all pixel types should in general be inspectable as bytes without padding. You may use [`bytemuck`](https://docs.rs/bytemuck/1.4.1/bytemuck/fn.cast_slice.html) or similar crates to convert your slices to byte slices without all the unsafe.

**Comment by HeroicKatora** [comment]
If you think the documentation could point this out or clarify the reasoning better, then a PR improving it would be greatly appreciated.

**Comment by virtualritz** [comment]
Why not use an enum that encapsulates the type? 
That way you keep the method name and all a user has to do on updating to a new version of the crate is wrapping their `data` in that enum.

E.g. `ChannelWidth::U16(&data)`.

If you improve an API it will sooner or later mean breaking changes. That's what crate versions are for.

**Comment by fintelia** [comment]
We've tried that in other places. It leads to a bunch more boilerplate/code repetition and we've had to make breaking changes a few times as we added more variants to the enum

**Comment by HeroicKatora** [comment]
For a recent example: See `tiff` which still uses that approach, and now has one breaking change everytime we support a new interpretation of colors. There are quite many 'outlandish' types such as `f24` or `xrgb444` for which no channel type is immediately obvious. But we know from C-interfaces that all are byte-compatible so this is a simple forward compatible choice. 
And the enum isn't actually more flexible. Quite the opposite, a `&[u16]` has strictly more alignment requirements and doesn't actually introduce any new invariants that we could rely on. The length must be checked either way.

Keep in mind that `image` is an aggregator. It wouldn't be one breaking change once in a while, the frequence would be at worst multiplied by the number of supported formats. That's totally intractable as an approach to security and only barrs many downstream users from receiving actually _important_ performance and security improvements (look at numbers of crate downloads by version, and then compare to back one year before `0.23`).

**Comment by birktj** [comment]
There is technically no reason that `image-tiff` could not use a non-exhaustive enum for `DecodingResult` other than it being more painful for consumers. This would add the ability to add new sample types without breaking changes. I would guess we could do the same for `image`. `image` also has one advantage in that it provides conversion functions and so any consumers could use those in the `match` fallback.

I think that with the right design some sort of dynamic pixel buffer could be very nice. It could also be integrated into a `PixelRead` / `PixelWrite` trait for use with encoders and decoders.

All of this would of course result in a large number of breaking changes in `image` so the benefits of introducing something like this should be carefully weighed against the drawbacks of introducing a bunch of breaking changes.

I imagine something like this for a dynamic pixel buffer. I don't really if/how `canvas` fits into this, my understanding is that is not really designed for buffers with dynamic types?

```rust
// Not public
enum DynBuffer {
    // Could for example use `Rec` in the future?
    U8(Vec<u8>),
    U16(Vec<u16>),
    // etc..
}

// Not public
enum DynBufferView<'a> {
    U8(&'a [u8]),
    U16(&'a [u16]),
}

pub enum ColorFormat {
    Luma,
    LumaA,
    Rgb,
    Rgba,
    Bgr,
    Bgra,
    // etc..
    #[doc_hidden]
    _non_exhaustive
}

pub enum SampleType {
    U8,
    U16,
    // etc..
    #[doc_hidden]
    _non_exhaustive
}

pub struct PixelType {
    channel_type: SampleType,
    color_format: ColorFormat,
    // possible to extend with colorspace information
}

pub struct PixelBuffer {
    pixel_type: PixelType,
    inner: DynBuffer,
}

impl PixelBuffer {
    pub fn new(pixel_type: PixelType, len: usize) -> PixelBuffer { .. }

    pub fn len(&self) -> usize { .. }

    pub fn pixel_type(&self) -> PixelType { .. }

    pub fn copy_pixels(&mut self, start: usize, buf: PixelBufferView) { .. }
    
    pub fn view(&self, start: usize, len: usize) -> PixelBufferView { .. }

    pub fn view_mut(&mut self, start: usize, len: usize) -> PixelBufferViewMut { .. }

    pub fn convert(&mut self, pixel_type: PixelType) -> PixelBuffer { .. }

    pub fn bytes(&self) -> &[u8] { .. }

    pub fn bytes_mut(&mut self) -> &mut [u8] { .. }

    pub fn slice_u16(&self) -> Option<&[u16]> { .. }

    pub fn slice_u16_mut(&mut self) -> Option<&mut [u16]> { .. }
}
```

**Comment by HeroicKatora** [comment]
> I imagine something like this for a dynamic pixel buffer. I don't really if/how canvas fits into this, my understanding is that is not really designed for buffers with dynamic types?

That would be precisely what `image-canvas` was designed to hypothetically provide. An abstraction around a buffer that can be reinterpreted to whatever 'simple' type is required, i.e. Copy and byte-view safe types such as the basic integer and floating point types and arroes of them etc.
