### ISSUE TITLE
The PnmEncoder is not supported universally in methods for saving images 

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image#1390]
I noticed that `free_functions.rs::save_buffer_with_format_impl` & `free_functions.rs::save_buffer_impl` have different match clauses as in `free_functions.rs::save_buffer_with_format_impl` has no references to `PnmEncoder` is that inteded? Can I fix that in a follow up PR?

_Originally posted by @Mike-Neto in https://github.com/image-rs/image/pull/1388#discussion_r548776206_

**Comment by Mike-Neto** [comment]
Could I make it so `save_buffer_impl` calls into `save_buffer_with_format_impl`? As that would avoid the duplicated/out of sync match clauses.

**Comment by HeroicKatora** [comment]
Yes, probably. I'm not entirely sure why it does not.
