### ISSUE TITLE
Shrinking image causes visual glitch

### ISSUE THREAD

**Issue by saschanaz** [image-rs/image#1402]
This happens in `image::imageops::resize`.

## Expected

Shrinking shouldn't add visual glitch

## Actual behaviour

It does happen

## Reproduction steps

Input image:

![yuno](https://user-images.githubusercontent.com/3396686/104833816-de702a00-589b-11eb-9836-5502360659b5.png)

```rust
// let decoded = raw RGBA buffer
// let xsize = 622;
// let ysize = 622;

let rgba = image::RgbaImage::from_raw(info.xsize, info.ysize, decoded)
    .expect("Failed to consume the decoded RGBA buffer");

rgba.save(&format!("{}\\debug.png", env!("CARGO_MANIFEST_DIR"))).unwrap();

let resized =
    image::imageops::resize(&rgba, 256, 256, image::imageops::Lanczos3);

resized.save(&format!("{}\\debug-resized.png", env!("CARGO_MANIFEST_DIR"))).unwrap();
```

Output image:

![debug](https://user-images.githubusercontent.com/3396686/104833889-58a0ae80-589c-11eb-9a6d-ba69a28245a5.png)

Glitch:

![image](https://user-images.githubusercontent.com/3396686/104834333-eb424d00-589e-11eb-917d-9ef4f5ddc007.png)

Shrinking with image editors e.g. Paint.NET doesn't add such glitches, is this expected here?

**Comment by HeroicKatora** [comment]
Can you be more specific, i.e. give a comparison to Paint?

**Comment by saschanaz** [comment]
I think Paint.NET was already specific, but this is what Paint 3D does: (Paint doesn't support transparency so picked it instead)

![yuno-256](https://user-images.githubusercontent.com/3396686/104846617-b7d1e380-58db-11eb-8fa9-4a1078ba79b4.png)

**Comment by HeroicKatora** [comment]
I don't understand. We don't aim at replicating the exact behavior of a specific tool. What is the problem with the image? Artifacts that I overlook? You need to be specific with regards to the problem, not the expected result.

**Comment by saschanaz** [comment]
I guess you couldn't catch the glitch I uploaded. It's easier to see if you zoom in it with image editors, and this is what I'm saying (emphasized as black dots)

![image](https://user-images.githubusercontent.com/3396686/104852119-23767980-58f9-11eb-853b-f15e00b2cfa9.png)

Now that I see the glitches have `#E5FD5D` while the background color is `#E5FE5E`. Surely hard to see 😅

I recognize a weird visual pattern here.

**Comment by saschanaz** [comment]
Oh, BTW it's much more visible with black background layer because somehow alpha channel is affected. I think it's the reason why I could catch see the glitch in the first place. (Please open your image editor if you still don't see it)

![image](https://user-images.githubusercontent.com/3396686/104852328-b532b680-58fa-11eb-8748-155271b3ee0f.png)

**Comment by fintelia** [comment]
I think this might be caused by using floating point math to do the resampling. In particular, converting individual components back from floats to integers seem to truncate rather than round:
https://github.com/image-rs/image/blob/8de5cb71fa0f35f8a681b7c2abb3c45ac98dbda7/src/imageops/sample.rs#L264-L267

If the value was say 254.9999 then that could be cast to 254, and since there are two iterations of sampling (one horizontal and one vertical) some pixels might get rounded down twice to a final value of 253.
