### ISSUE TITLE
why does rotate90 mangle images?

### ISSUE THREAD

**Issue by d7p** [image-rs/image#1405]
Hi 

I'm trying to roate an image 90' using `DynamicImage.rotate90()` but the images comes out mangled. see bellow. 
`rotate180()` works as expected turning images upside down but `rotate270()` also mangles any images

original image:
![DSC_0847](https://user-images.githubusercontent.com/745957/105485262-86269700-5ca4-11eb-9cc5-0536c392292f.JPG)

after 90' rotation:
![result_image](https://user-images.githubusercontent.com/745957/105399772-fb9a5500-5c1b-11eb-8ea6-32e3d1f10fe5.jpg)

This is how  I'm using trying to rotate the images. 
` let rgba_img: DynamicImage = DynamicImage::ImageRgba8(img_buffer);
  let raw_pixels = rgba_img.rotate90().to_rgba8().to_vec();
  let res = PhotonImage::new(raw_pixels, w1, h1);`

If I remove the `rotate90()` then a image is returned exactly as the original and if i use `roate180()` a unside down version of the image is returned as expected. I have looked at the [srource](https://github.com/image-rs/image/blob/3529ad303148be0a72c9b9385f6b7177130ed1ca/src/imageops/affine.rs#L45) but can't see what i would be doing wrong.

What am i doing wrong with 90' rotation?

**Comment by HeroicKatora** [comment]
The rotated image supposedly having the same width and height as the original is wrong, it should have swapped height and width. That probably means the raw pixel/texel buffer is interpreted incorrectly, also looks like that in the artifact. I don't think that incorrect interpretation happens within `image`.

**Comment by HeroicKatora** [comment]
Is there a fully reproduction repository with sources and dependencies?

**Comment by d7p** [comment]
Hi 

there is now ;) 
[rotate-image-rs-issue-tests](https://github.com/d7p/rotate-image-rs-issue-tests)
there is three images in the `testImages` directory to run it against.

**Comment by d7p** [comment]
> The rotated image supposedly having the same width and height as the original is wrong, it should have swapped height and width. That probably means the raw pixel/texel buffer is interpreted incorrectly, also looks like that in the artifact. I don't think that incorrect interpretation happens within `image`.

I would expect the image to have the changed the hight/width as well but it would be fine if it left extra pixel (max width/ max hight) that could be cropped as a second step. like [raster::rotate](https://kosinix.github.io/raster/docs/raster/transform/fn.rotate.html) [src](https://kosinix.github.io/raster/docs/src/raster/transform.rs.html#139-194)

**Comment by HeroicKatora** [comment]
If you, too, expect swapped height and width then you have a typo in your code. It should be:

`PhotonImage::new(raw_pixels, h1, w1)`

I've validated that with your reproduction setup and it seems to work as expected.

**Comment by d7p** [comment]
Thank you @HeroicKatora  
I should have seen that.
