### ISSUE TITLE
Make it possible to enable just the AvifEncoder or the AvifDecoder

### ISSUE THREAD

**Issue by paolobarbolini** [image-rs/image#1422]
With other formats it doesn't really matter if both the encoder and the decoder are enabled when just one of the two is necessary. 
AVIF is different. The encoder requires NASM because of `rav1e`. The decoder imports a lot of useless dependencies because of `bindgen`, which is a dependency of `dav1d-sys`, and also requires either having dav1d installed or for an environment variable to be set at compile-time to make it build and link to it statically.

Would you be interested in a PR splitting the `avif` feature into something like `avif-encoder` and `avif-decoder`?

**Comment by HeroicKatora** [comment]
The testing in #1421 also needs this, so it was added there. I see it as an endorsement of the idea :) We'll want to be careful not to break any existing use of `features=avif`, which was part of `0.23.12`, so if you could give it a quick review and double check that would be appreciated.
