### ISSUE TITLE
Resizing is very slow

### ISSUE THREAD

**Issue by soadzoor** [image-rs/image#1424]
Hello,

I've created a function with this lib that looks like this:
```
pub fn resize_and_save_image(image: &image::DynamicImage, folder_path: &String, max_dimension: u32) -> image::DynamicImage {
    let filter = image::imageops::FilterType::Lanczos3;

    println!("Resizing file...");
    let new_image = image.resize(max_dimension, max_dimension, filter);
    let new_dimensions = new_image.dimensions();
    println!("Saving resized file...");
    new_image.save(format!("{}/{}_{}.jpg", folder_path, new_dimensions.0, new_dimensions.1)).unwrap();

    new_image
}
```

This is the original image file I'm trying it with (it's a 6000x3000 jpeg, nothing special):
![example1](https://user-images.githubusercontent.com/10392261/106824353-f8bf4b80-6682-11eb-9c95-68540b1b7d22.jpg)

I'm basically downscaling it to 4096x2048 with the function above.
## Expected

I believe this process shouldn't take more than 1-2 seconds. There are webapps that can do it in a blink of an eye (eg.: https://www.imageplayground.net/) with javascript

## Actual behaviour

It's very slow, like ~40-45 seconds on my machine, while keeping my CPU usage pretty high (like 30-35%). And it's most likely the resizing, because I print out "Resizing file..." before the resizing, and it hangs for a lot. The saving process itself is a lot faster, like 1-2 seconds.

Am I missing something, or is it normal that the resizing is so slow? Any option to make it faster?

BTW I'm absolutely happy with the output file, the filesize is very small, while keeping the quality excellent, so that's great.

**Comment by HeroicKatora** [comment]
Without verifying the timings, doesn't seem out of the question though slow, one clarification: The linked page uses WebGL/canvas and not javascript for resizing whereas this crate targets pure CPU operations to minimize dependencies. Feel free to resize with some other crate, e.g. `wgpu` offers similar capabilities as WebGL but you'll need some manual setup. Or stay tuned because and I'll ping this issue when I become aware of any crate that addresses this gap in API.

**Comment by fintelia** [comment]
40-45 seconds seems slow to me for resizing an image that size even if it is running single threaded on the CPU. Are you sure you're compiling in release mode?

**Comment by fintelia** [comment]
I'm pre

**Comment by fintelia** [comment]
I'm pretty sure that the issue was not using a release build. On my machine, the resize takes 30 second with a debug build, but only 700 _milliseconds_ when running in release mode.

**Comment by samdenty** [comment]
maybe it'd make sense to put that somewhere in the docs, as it's nonobvious that theres such extreme differences between release/debug

**Comment by soadzoor** [comment]
Correct, I was using it in debug mode, I had no idea that there's such a difference. I've just tried in release mode and it's much much faster. Could someone explain the reason behind that?

**Comment by kaj** [comment]
Basically, many pixel/channel value accesses in debug mode will call a function that checks that the x and y value are within range for the image.  In release mode, that function will be inlined, and the compiler will be able to tell that all x and y values in the entire loop is within range, so the check will be removed.  So turning on optimizations will, among other optimizations, convert something that is done multiple times for each pixel from one function call, two or four conditionals and one pointer dereferencing to just one pointer dereferencing.

**Comment by soadzoor** [comment]
@kaj  thank you for the explanation!

**Comment by HeroicKatora** [comment]
@soadzoor You seem content with the performance, can this be closed? Unless you have concrete plans to submit a documentation PR addressing the missing information right away, which I'd be happy to receive and review.

**Comment by soadzoor** [comment]
@HeroicKatora I've created a PR, feel free to check and let me know what you think: https://github.com/image-rs/image/pull/1425
