### ISSUE TITLE
Conversion format

### ISSUE THREAD

**Issue by tingfeng-key** [image-rs/image#1441]
Hello, I want to use this library to convert webp format files to PNG, but I don't know how to deal with this problem now. Can this library convert file format now?

**Comment by HeroicKatora** [comment]
You can have a look at the [`convert` example](https://github.com/image-rs/image/blob/master/examples/convert.rs) and [`DynamicImage::write_to`](https://docs.rs/image/0.23.13/image/enum.DynamicImage.html#method.write_to) if you want control over the output format but not write to disk. Do note however that there is a limitiation is in the `webp` decoding support as you can see in [this table](https://github.com/image-rs/image#supported-image-formats). If you need this, then there is an option to try the [`webp` crate](https://docs.rs/webp/0.1.1/webp/) which wraps the C library `libwebp`.

**Comment by tingfeng-key** [comment]
Ok thanks for your reply, i will try

**Comment by fintelia** [comment]
Closing this issue. Feel free to reopen if something isn't working for you
