### ISSUE TITLE
`ImageOutputFormat` is missing tiff

### ISSUE THREAD

**Issue by birktj** [image-rs/image#1446]
[`ImageOutputFormat`](https://docs.rs/image/0.23.14/image/enum.ImageOutputFormat.html) is missing a variant for tiff, however tiff encoding was implemented way back in #922

**Comment by SaiintBrisson** [comment]
Although this crate supports TIFF encoding, adding a variant would require either [`write_to`](https://docs.rs/image/0.23.14/image/enum.DynamicImage.html#method.write_to) to have a Seek bound on its writer or to remove the Seek bound from [`TiffEncoder`](https://docs.rs/image/0.23.14/image/codecs/tiff/struct.TiffEncoder.html) (which I don't think is possible).

**Comment by fintelia** [comment]
The issue seems to be this operation:

https://github.com/image-rs/image-tiff/blob/2cba04dfe70e3fb81e3f3977882c70624895650f/src/encoder/mod.rs#L546-L551

**Comment by birktj** [comment]
That is a very good point. As far as I know it is pretty much impossible to implement the generic `tiff::DirectoryEncoder` without a `Seek` bound, but the `tiff::TiffEncoder::write_image` function could be adapted to work without the `Seek` bound.

Alternatively it would probably be possible to add buffering in the `write_to` function when writing to tiff images. This would of course potentially lead to some unexpected resource use, but the situation would probably be better than without tiff support?

**Comment by fintelia** [comment]
Yeah, at a minimum I think it would be worth adding an implementation that encodes into a `Cursor<Vec<u8>>` and then just writes that into the output all at once.

**Comment by SaiintBrisson** [comment]
Agreed, I can try implementing it if the problem @birktj mentioned isn't a big concern.

**Comment by HeroicKatora** [comment]
I basically agree with buffering being better than no support. In particular, we do not offer an incremental enconding API so that any image needs to reside in memory and encoding of very large images is out-of-scope of the current methods in either case.
