### ISSUE TITLE
Missing Code of Conduct

### ISSUE THREAD

**Issue by BobinMathew** [image-rs/image#1447]
I see that your repo is missing its Code of Conduct. Adding a Code of Conduct improves your community profile
Cant I propose a Code of Conduct?

**Comment by HeroicKatora** [comment]
It should be that of [the organization](https://github.com/image-rs/organization/blob/master/CODE_OF_CONDUCT.md) it appears not to be linked automatically.

**Comment by BobinMathew** [comment]
Do you want [that](https://github.com/image-rs/organization/blob/master/CODE_OF_CONDUCT.md) in this repo?

**Comment by fintelia** [comment]
I don't know if it really needs to be copied here. Seems fine to me to just have centrally in the organization and then linked from somewhere prominent (in the README?) for each of the repositories.
