### ISSUE TITLE
imageops::replace alpha issues

### ISSUE THREAD

**Issue by TomPridham** [image-rs/image#1450]
i am trying to randomly place images on top of another image. all the images being placed have transparent backgrounds. it works exactly as expected when using `overlay` and produces an image like below.
![go](https://user-images.githubusercontent.com/8271228/110590763-75878e80-8135-11eb-95c9-45ca3e4239e5.png)

using `replace` is desirable because it's significantly faster in my benchmark. the underlying pixels are being replaced with the transparent background, however, and it produces an image like this. which has a lot of empty space consisting of that transparent background. is that just how replace is intended to work or is there another way to do it that will essentially ignore that transparent background?
![g](https://user-images.githubusercontent.com/8271228/110591233-08c0c400-8136-11eb-85c2-b1e34e869b0a.png)

**Comment by fintelia** [comment]
I believe that this is working as intended. The reason that `replace` is faster than `overlay` is that it doesn't do alpha blending and just copies over the raw pixel data
