### ISSUE TITLE
Load image from embedded u8 vec instead of file

### ISSUE THREAD

**Issue by schanur** [image-rs/image#1465]
To support single binary applications it is required to embed resource files (in this case images) into the binary and decode it from there.
Can you please add an interface to load from string or u8 vec or something else which is not a file.

Thank you.

**Comment by aschampion** [comment]
From the docs landing page:

```rust
use image::io::Reader as ImageReader;

let img2 = ImageReader::new(Cursor::new(bytes)).decode()?;
```

**Comment by schanur** [comment]
Sorry. I didn't understand that part on my first read and so I overlooked it.

Thank you!
