### ISSUE TITLE
DynamicImage::grayscale does not maintain alpha channel

### ISSUE THREAD

**Issue by Jacherr** [image-rs/image#1466]
When attempting to convert a RGBA image to grayscale, the alpha channel gets deleted/not respected, which results in any transparent or semi-transparent parts of the image to become completely black in the output DynamicImage.

I'm not sure if this is intended or not, but it would be ideal if the alpha channel was respected when converting an image with an alpha channel to grayscale.

**Comment by drahnr** [comment]
I have unit test that used to work (image `0.23.11` -> `0.23.14` )

This unit test now fails:
https://github.com/spearow/juice/blob/master/greenglas/tests/image_spec.rs#L53-L60
