### ISSUE TITLE
Slow Gif Encoding

### ISSUE THREAD

**Issue by daggy1234** [image-rs/image#1467]
So I was experimenting with gifs in rust, and realised that on my machine, encoding gifs and writting them to file takes a really long time. 

I created a minimum reproducible example here: https://github.com/Daggy1234/min-rep-gifrs

As the readme mentions, it took almost 10s for encoding the gif. With release mode.

I have had various others try gif, and it's always been high.

**Comment by HeroicKatora** [comment]
Most of this is spent in `NeuQuant::init`—actually 94% of the time on my machine—called [here](https://github.com/image-rs/image-gif/blob/9206fc40daffa09183975bc0f4a257a0cfcc89a1/src/common.rs#L220-L221).

**Comment by Daggy1234** [comment]
That seems to be another crate from the image-rs team https://github.com/image-rs/color_quant

**Comment by Daggy1234** [comment]
Slight necrobump here, is there anything i can tweak or adjust to impprove encode times?

**Comment by fintelia** [comment]
You might be able to get some improvement by tweaking the speed setting via [`GifEncoder::new_with_speed`](https://docs.rs/image/0.23.14/image/codecs/gif/struct.GifEncoder.html#method.new_with_speed).

However, the main problem is that with GIFs each frame can only contain 256 distinct colors and deciding which would be best isn't easy. If you use the `gif` crate directly then that gives you the option of passing in a palette to directly. Of course that would mean that you'd have to come up with it yourself.

**Comment by Fogapod** [comment]
Unsure if `new_with_speed` works at all. I tried values 1 and 30 on multiple images both in debug and release modes, there is no difference in speed/resulting image quality at all. How much of a difference there should be?
