### ISSUE TITLE
Encoding a JPEG with the wrong ColorType causes an internal panic

### ISSUE THREAD

**Issue by Jacherr** [image-rs/image#1476]
Passing an `ImageBuffer<Rgb8>` to a `JpegEncoder` and encoding it as `ColorType::Rgba8` causes an internal panic.

Code to reproduce:
```rust
use image::{DynamicImage, jpeg::JpegEncoder, ColorType};

fn main() {
  let image = DynamicImage::new_rgb8(10, 10);
  let imbuf = image.to_rgb8();
  let mut buf: Vec<u8> = Vec::new();
  let mut encoder = JpegEncoder::new_with_quality(&mut buf, 5);
  encoder.encode(&imbuf.into_raw(), 10, 10, ColorType::Rgba8);
}
```

Error:
```
thread 'main' panicked at 'called `​Option::unwrap()`​ on a `​None`​ value', /playground/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/codecs/jpeg/encoder.rs:460:98
```

The function that returns None is documented to only do so if the allocated buffer is not large enough. This does not seem to be the reason it is returning None here, as passing the correct `ColorType` while making no changes to the buffer allocation avoids the panic.

**Comment by fintelia** [comment]
I think this is working correctly. A 10x10 Rgb8 image takes 30 bytes whereas a 10x10 Rgba8 image takes 40 bytes. You are passing a `&[u8]` of length 30 to a function that (based on the other arguments) is expecting 40 bytes of data.
