### ISSUE TITLE
Reminder: Simplify HDR Decoder

### ISSUE THREAD

**Issue by johannesvollmer** [image-rs/image#1480]
F32 color support was further improved, allowing us to hopefully simplify the HDR decoder. 

See #1478  and maybe #1473

## Draft

The HDR decoder currently uses an adapter to simulate f32 storage. This issue is a reminder to consider removing the adapter in favor of a simple RGB32F buffer.

**Comment by johannesvollmer** [comment]
There seems to be a very minimal HDR encoder, which is not used anywhere yet. There seems to be no comment about whether it could work. Maybe the only barrier preventing it from being used was the missing f32 support back then? 

Now that f32 support is here, how difficult would it be to make the encoder work?

**Comment by emble** [comment]
Yes, please, do that. All my votes for that! I just stumbled about that issue.

My project is hdr/exr import, image = "0.24.1"
Invoking Reader::decode()
Result:

- the brand-new OpenExr decoder works great (many thanks to all involved)
- the Hdr decoder, as it currently is,  renders itself unusable, on the first impression. One could call it broken. It should return f32, not u8.

Workaround for me was to invoke the Hdr decoder directly and call decoder.read_image_hdr(), while passing the other formats to decode()

Again, please remove the bad wrapper code that breaks the good code.

**Comment by johannesvollmer** [comment]
I've opened #1695 1599 for this, but got stuck

**Comment by wrightwriter** [comment]
need
