### ISSUE TITLE
ImageOutputFormat should be used everywhere or nowhere

### ISSUE THREAD

**Issue by fintelia** [image-rs/image#1481]
Right now, the `ImageOutputFormat` enum is only used by `DynamicImage::write_to`, whereas everywhere else that we encode image files takes an instance of the `ImageFormat` enum. This distinction has led to confusion (see #1461) and is an API inconsistency. I see two possible ways to resolve this:

* Use ImageOutputFormat everywhere. This was attempted by @johannesvollmer who provided a possible patch in https://github.com/image-rs/image/pull/1477#issuecomment-844069443. May also want to implement #1380 at the same time to avoid more API breakage in the future.
    - Pros: Retains and expands the opportunity for per-format encoding options
    - Cons: More API breakage, more complex API 

* Change `DynamicImage::write_to` to take a ImageFormat, and remove ImageOutputFormat entirely.
   - Pros: decreases API complexity
   - Cons: can't specify JPEG quality without working with a JpegEncoder directly.

**Comment by johannesvollmer** [comment]
In the first case, API consistency is increased also by the fact that a user cannot accidentally try to write an image with an unsupported ImageFormat. Explicitly declaring an ImageOutputFormat catches the error that a certain image format can not (yet) be written, ahead of runtime.

In the second case: Given you want your image to be decoded with a jpeg quality of 80, you already know you need a Jpeg Encoder, so there would be no need to use the dynamic image, right?

**Comment by fintelia** [comment]
Yeah, working with a Jpeg Encoder shouldn't be too much of a big deal. Just: `JpegEncoder::new_with_quality(writer, 80).encode_image(img)?`

Your point about not accidentally trying to write an image with an unsupported format is a good one. Makes me torn between that and the opportunity to reduce the API surface.

**Comment by johannesvollmer** [comment]
Just hypothetically, if one were to keep ImageOutputFormat and then rename ImageFormat to ImageInputFormat, would this be an obvious change? Or does the ImageFormat do more than just Input?

**Comment by fintelia** [comment]
Off hand I don't recall anything else that `ImageFormat` is used for, but a quick grep indicates nearly 350 references to the type so I don't want to say anything for sure. One notable difference between `ImageFormat` and `ImageOutputFormat` is that when working with the latter, you _must_ specify encoding options. I think some users produce an `ImageOutputFormat` via `ImageFormat::into()` to get the defaults options instead.

**Comment by johannesvollmer** [comment]
That might be true. If we are going for breaking changes anyways, we could point users to `ImageOutput::default()`, so that would not be a problem

**Comment by ror6ax** [comment]
Hi, confused client here. I want to write out configurable compression JPEGs and PNGs in my program. Currently, I use save method on imagebuffer that does not take any arguments(see #1461 for context). Could you please advise what is the simplest way to go about it?

**Comment by fintelia** [comment]
@ror6ax the API isn't great right now, but given a DynamicImage something like this should work:
```rust
let mut encoded = Vec::new();
image::codecs::jpeg::JpegEncoder::new_with_quality(&mut encoded, 95)
    .encode(img.as_bytes(), img.width(), img.height(), img.color()).unwrap();
std::fs::write("img.jpeg", encoded).unwrap();
```

**Comment by ror6ax** [comment]
@fintelia I'm getting  the `trait std::io::Write is not implemented for ImageBuffer<Rgba<u8>, Vec<u8>>` error.  I can't figure out what is supposed to be used with what on nth attempt. Probably biting off more than I can chew with this one.

**Comment by fintelia** [comment]
With an ImageBuffer, the encode call should look something like:
```
.encode(&*img, img.width(), img.height(), ColorType::Rgba8)
```

**Comment by ror6ax** [comment]
Still getting ```method not found in `ImageBuffer<_, Vec<_>>``` for encode.

**Comment by ror6ax** [comment]
Thanks, got it working now.

**Comment by pevogam** [comment]
Hi all, I still wonder about the handling of the previous ImageOutputFormat::Unsupported here. In the past we had some local format conversions like
```rust
impl From<AutoPyImageFormat> for ImageOutputFormat {
    fn from(format: AutoPyImageFormat) -> ImageOutputFormat {
        use image::ImageOutputFormat::*;
        match format {
            AutoPyImageFormat::BMP => BMP,
            AutoPyImageFormat::GIF => GIF,
            AutoPyImageFormat::JPEG => JPEG(100),
            AutoPyImageFormat::PNG => PNG,
            AutoPyImageFormat::Unsupported => {
                Unsupported("This image format is unsupported by AutoPy".to_string())
            }
        }
    }
}

impl From<ImageOutputFormat> for AutoPyImageFormat {
    fn from(format: ImageOutputFormat) -> AutoPyImageFormat {
        use image::ImageOutputFormat::*;
        match format {
            BMP => AutoPyImageFormat::BMP,
            GIF => AutoPyImageFormat::GIF,
            JPEG(_) => AutoPyImageFormat::JPEG,
            PNG => AutoPyImageFormat::PNG,
            _ => AutoPyImageFormat::Unsupported,
        }
    }
}
```
but with the above PR merged the closest I can get to is
```diff
@@ -418,29 +418,29 @@ enum AutoPyImageFormat {
     Unsupported,
 }
 
-impl From<AutoPyImageFormat> for ImageOutputFormat {
-    fn from(format: AutoPyImageFormat) -> ImageOutputFormat {
-        use image::ImageOutputFormat::*;
+impl From<AutoPyImageFormat> for ImageFormat {
+    fn from(format: AutoPyImageFormat) -> ImageFormat {
+        use image::ImageFormat::*;
         match format {
-            AutoPyImageFormat::BMP => BMP,
-            AutoPyImageFormat::GIF => GIF,
-            AutoPyImageFormat::JPEG => JPEG(100),
-            AutoPyImageFormat::PNG => PNG,
+            AutoPyImageFormat::BMP => Bmp,
+            AutoPyImageFormat::BMP => Bmp,
+            AutoPyImageFormat::GIF => Gif,
+            AutoPyImageFormat::JPEG => Jpeg,
+            AutoPyImageFormat::PNG => Png,
             AutoPyImageFormat::Unsupported => {
-                Unsupported("This image format is unsupported by AutoPy".to_string())
+                // TODO: now what?
             }
         }
     }
 }
 
-impl From<ImageOutputFormat> for AutoPyImageFormat {
-    fn from(format: ImageOutputFormat) -> AutoPyImageFormat {
-        use image::ImageOutputFormat::*;
+impl From<ImageFormat> for AutoPyImageFormat {
+    fn from(format: ImageFormat) -> AutoPyImageFormat {
+        use image::ImageFormat::*;
         match format {
-            BMP => AutoPyImageFormat::BMP,
-            GIF => AutoPyImageFormat::GIF,
-            JPEG(_) => AutoPyImageFormat::JPEG,
-            PNG => AutoPyImageFormat::PNG,
+            Bmp => AutoPyImageFormat::BMP,
+            Gif => AutoPyImageFormat::GIF,
+            Jpeg => AutoPyImageFormat::JPEG,
+            Png => AutoPyImageFormat::PNG,
             _ => AutoPyImageFormat::Unsupported,
         }
     }
```
note the ` // TODO: now what?` part. What format should I choose for unsupported? I could raise an error but this is not compatible with the `fn from(format: AutoPyImageFormat) -> ImageFormat` signature.

**Comment by kornelski** [comment]
Idiomatic solution is not to have From, and use TryFrom instead

**Comment by pevogam** [comment]
> Idiomatic solution is not to have From, and use TryFrom instead

Great comment, I assume then the point was for the `image::ImageOutputFormat::Unsupported` to really die out and to never again provide support for such "unknown" image format.
