### ISSUE TITLE
Copy impl GenericImage to an ImageBuffer

### ISSUE THREAD

**Issue by masonk** [image-rs/image#1486]
I'm trying to load an image, crop it, and save the cropped SubImage to an ImageBuffer.

Minimal RTC:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ba845e34f336bbdcc4ff0aa22ad72f43

I get multiple errors.

I think the biggest one is that `impl GenericImage` does not provide a trait bound `EncodableLayout` that is needed to save things. What's the most generic trait bound I can use for this? While I currently only work with DynamicImages, I'd like to be able to operate over whatever `image` itself can operate over.

But, even before I try to save, there's a lifetime bound problem that I truly cannot fathom::

```
   |
   |     let mut imgbuf = image::ImageBuffer::new(dest_w, dest_h);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider adding an explicit lifetime bound `<impl GenericImage as GenericImageView>::Pixel: 'static`...
   = note: ...so that the type `<impl GenericImage as GenericImageView>::Pixel` will meet its required lifetime bounds
```

**Comment by fintelia** [comment]
It is just a matter of having the same bounds as the `ImageBuffer::save` method requires:
```rust
fn crop<I, P>(dest: &Path, mut img: I) -> Result<()> where 
    I: GenericImage<Pixel = P>,
    P: Pixel + 'static,
    [P::Subpixel]: EncodableLayout
{
    ...
}
```

**Comment by masonk** [comment]
Thanks! I really appreciate that you took the time to answer this question.
