### ISSUE TITLE
Saving file with unsupported file extension generates empty file

### ISSUE THREAD

**Issue by autumnull** [image-rs/image#1513]
When a filename is given to `save()` that has an unsupported file extension, an empty file is created with the given filename before an error is thrown.

I think that an error should be thrown before the file is generated. I think this should be achievable by just switching these two lines:

https://github.com/image-rs/image/blob/3197e3d964f5d214cbdec98206fbc895723e5c72/src/io/free_functions.rs#L131-L132

**Comment by HeroicKatora** [comment]
Since you already found the error, a PR for this (with regression test) would be highly appreciated.

**Comment by autumnull** [comment]
> a PR for this (with regression test) would be highly appreciated.

Hopefully this new PR that passes all `cargo test` is suitable... I've not contributed to many projects before.

**Comment by HeroicKatora** [comment]
Yep, thank you.
