### ISSUE TITLE
Failure to decode PNGs with invalid checksums for ancillary data

### ISSUE THREAD

**Issue by awused** [image-rs/image#1524]
## Expected

PNGs with invalid checksums for ancillary data (ICC profiles, in my case) should be decoded without said ancillary data. Or at least the option should be available to skip the invalid chunk, as most implementations will tolerate these invalid checksums with a warning.

## Actual behaviour

The entire PNG decoding process fails with no option for recovery.

## Reproduction steps

There's a similar bug for Go's image library with a sample image: https://github.com/golang/go/issues/43382

**Comment by fintelia** [comment]
This should now be fixed
