### ISSUE TITLE
MIME type

### ISSUE THREAD

**Issue by RustyNixieTube** [image-rs/image#1528]
I would like to be able to create `ImageFormat` from a MIME type.

My specific use case for this functionality is decoding an image that comes from a js function.

if this feature is accepted, i will do a pr for it.

## Draft

```rust
impl ImageFormat {
    fn from_mime_type(mime_type: &str) -> Option<Self> {
        match mime_type {
             "image/png" => Some(ImageFormat::Png)
             _ => todo!();
        }
    }
}
```

**Comment by fintelia** [comment]
This sounds good to me.

**Comment by RustyNixieTube** [comment]
ok i open a pr for it.
