### ISSUE TITLE
Question: use transparent background with GIF instead of the first frame.

### ISSUE THREAD

**Issue by poly000** [image-rs/image#1531]
I would like to be able to generate a GIF with transparent background,

But I got 

![0](https://user-images.githubusercontent.com/34085039/128636263-462f6abc-11ad-4a84-8f39-c562d28b0696.gif)

instead of

![0](https://user-images.githubusercontent.com/34085039/128636223-3ed7f45a-ee2a-45b3-8996-e2c8f97388ce.gif)

**(Images from [morgirl_wiki](https://zh.moegirl.org.cn/File:TqmhL.png))** so this post should be CC-BY-NC-SA 3.0

I am trying to RIIR petpet generator.

Any use need to generate GIF with  transparent background and the frames cannot simply overlay the last frames.

**Comment by fintelia** [comment]
Are you using `Frame::from_rgba` to create your GIF frames? That should let you specify a transparent background

**Comment by poly000** [comment]
> Are you using `Frame::from_rgba` to create your GIF frames? That should let you specify a transparent background

My code is here: https://github.com/poly000/petpet-rs

**Comment by poly000** [comment]
> Are you using `Frame::from_rgba` to create your GIF frames? That should let you specify a transparent background

Thx for the reply, I will try

**Comment by poly000** [comment]
> Are you using `Frame::from_rgba` to create your GIF frames? That should let you specify a transparent background

thx for the reply...
but I can't find `from_rgba` method in `image` ... should I use gif crate instead?

**Comment by poly000** [comment]
I guess the problem is not in `Frame`, because the frames are now with a Alpha channel

**Comment by fintelia** [comment]
I think your code should work. Might be a bug in the gif crate

**Comment by poly000** [comment]
> I think your code should work. Might be a bug in the gif crate

I guess so. Because when I tried add a transparent frame, it will still come out the first hand frame as background.

**Comment by fintelia** [comment]
Actually, I tried making a small tweak to your code and it seems to work?

```
             .pixels()
             .zip(resize_then_overlay.pixels_mut())
         {
-            if let &Rgba([_, _, _, 0]) = pixel_hand {
+            if pixel_hand.0[3] != 0 {
                 *pixel_canvas = *pixel_hand;
             }
         }
```

![test](https://user-images.githubusercontent.com/4943209/128641579-d17bcab2-2eb4-448a-97b0-6a2c718b93c2.gif)

**Comment by poly000** [comment]
> Actually, I tried making a small tweak to your code and it seems to work?
> 
> ```
>              .pixels()
>              .zip(resize_then_overlay.pixels_mut())
>          {
> -            if let &Rgba([_, _, _, 0]) = pixel_hand {
> +            if pixel_hand.0[3] != 0 {
>                  *pixel_canvas = *pixel_hand;
>              }
>          }
> ```
> 
> ![test](https://user-images.githubusercontent.com/4943209/128641579-d17bcab2-2eb4-448a-97b0-6a2c718b93c2.gif)

Ah, sorry. here is a bug
