### ISSUE TITLE
ImageBuffer::write_to akin to DynamicImage::write_to

### ISSUE THREAD

**Issue by PurpleMyst** [image-rs/image#1548]
I would like to be able to call a method like `DynamicImage::write_to` on `ImageBuffer`.

My specific use case for this functionality is to write images that I statically know the type of to buffers.

This is more generally applicable to anybody that wants to write an image not to a file.

**Comment by HeroicKatora** [comment]
`ImageBuffer::write_to` is available in `0.24` (#1449).
