### ISSUE TITLE
Panic when opening `gif` file - thread 'main' panicked at 'range start index 255 out of range for slice of length 196' 

### ISSUE THREAD

**Issue by qarmin** [image-rs/image#1551]
Opening(via open function) this image
[steam_logo_onwhite13.gif.zip](https://github.com/image-rs/image/files/7107547/steam_logo_onwhite13.gif.zip)

another one 
[motif_MoveNoDrop32x3212.gif.zip](https://github.com/image-rs/image/files/7107563/motif_MoveNoDrop32x3212.gif.zip)

cause panic
```
thread 'main' panicked at 'range start index 255 out of range for slice of length 196', /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/gif-0.11.2/src/reader/decoder.rs:251:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 5225225** [comment]
Looks like this has been fixed now in `gif` version `0.11.3`. I tested `image::open` locally on those two files and they seem to decode fine now.
