### ISSUE TITLE
How to detect encoding of input image

### ISSUE THREAD

**Issue by sam0x17** [image-rs/image#1553]
Is there a way to directly get the encoding of the input image? Dealing with scenarios where user-uploaded files have `.png` extension but are actually jpeg images, etc. I want to know that the file is actually png encoded regardless of extension.

**Comment by farjadfazli** [comment]
^^ +1 -- also need to know how to do this!

**Comment by RobKlock** [comment]
^ need this as well (keeps me up at night)

**Comment by robert10997** [comment]
also need this

**Comment by HeroicKatora** [comment]
You can use [`guess_format`](https://docs.rs/image/0.23.14/image/fn.guess_format.html) with a prefix (32 bytes suffice for all current formats; that fact should probably be added to the documentation) of the image file. If your program needs to _ensure_ that exactly that same format is being used during decoding then [`io::Reader`](https://docs.rs/image/0.23.14/image/io/struct.Reader.html#method.with_format) may be used to skip or override the automatic mechanisms for format detection. For example, either with an uploader provided parameter, or with the format corresponding to the extension, or with the format that has been previously guessed.

**Comment by sam0x17** [comment]
thanks a bunch!
