### ISSUE TITLE
Loading invalid jpgs

### ISSUE THREAD

**Issue by benrhughes** [image-rs/image#1556]
Hi,
I'm migrating a program from node/typescript to rust. The program converts corrupted jpgs to non-corrupted by opening and re-saving them. It uses [sharp](https://sharp.pixelplumbing.com/) which has a "best effort" option when reading the image. 

When I attempt to load a corrupted jpg using `image`, I get:
```
Decoding(DecodingError { format: Exact(Jpeg), underlying: Some(Format("failed to decode huffman code")) })
```

which is essentially the same error I get from `sharp` if I don't set the "best guess" flag. 

I've had a look though the `image` documentation and source but can't see any options to ignore errors and "best guess" the jpg decoding. I'm very new to rust though so it's quite possible I've missed something obvious.

Is there a way to do what I want?

Cheers,

 Ben

**Comment by HeroicKatora** [comment]
No, recovery from Huffman encoding is not yet implemented. Sorry :/

**Comment by benrhughes** [comment]
No probs - I'll convert the rest of the pipeline to rust and leave the jpg recovery in node for now. 

Cheers,

Ben
