### ISSUE TITLE
Decode a BMP image from clipboard (i.e. in memory)

### ISSUE THREAD

**Issue by michaelrommel** [image-rs/image#1569]
How does one ... ?

... create a BmpDecoder with the setting `no_file_header: true`?

Overall, I'm trying to achieve ...

... to decode a BMP image with DIBV5HEADERINFO and alpha channels that I obtained from Windows' GetClipboardData.
I managed to get to the correct memory location, that contains the headerinfo struct, but both:
* `load_from_memory_with_format` and
* `BmpDecoder` instantiation
do not work as they immediately try to parse the given pointer and fail, because the file header is not present.

I also tried to manually instantiate a BmpDecoder and then use `decoder.read_metadata()` but this is not possible be cause the module is private and various structs like, BMPHeaderType and ImageType are also not accessible (or I am doing this wrong, which certainly might be the case, as this is my second Rust program in my life...)

Any ideas or pointers to an example would be very helpful.

  Michael.

**Comment by fintelia** [comment]
I don't think the crate currently supports that kind of BMP file. I'm not super familiar with the whole BMP format, so I don't quite know what it would entail. Can this be added without changing the overall load_from_memory_with_format / BmpDecoder interface?

**Comment by michaelrommel** [comment]
At least a glance over the formats and encoder sections showed, that the headerformat is an enum with the DIBV5HEADERINFO contained, so I wanted to try that, instead of writing my own converter or disk-writer. I will now try to create a whold structure including the file header and see if the crate then parses that.

But at least it is good to know, that I did not miss something simple, as I am a Rust beginner... Thanks!

**Comment by michaelrommel** [comment]
Hi,

I ended up really preparing a file header and copying the image data below it like this: https://github.com/michaelrommel/clipboard-win/blob/885a87a38dafc7cf40b2861a3282ee97deea50eb/src/raw.rs#L486

It does work and produce the desired result.

Thanks for your library!

  Michael.
