### ISSUE TITLE
resize_to_fill uses integer division and truncation instead of rounding floating points, causing extra distortion

### ISSUE THREAD

**Issue by awused** [image-rs/image#1594]
## Expected

When calling `resize_to_fill` it should do its best to maintain the aspect ratio of the source image. 

## Actual behaviour

The image can be distorted by nearly an entire pixel on one on one axis, where rounding would limit the error to no more than half of a pixel.

## Reproduction steps

I was able to notice this with an image of initial resolution 4264x2476 and calling `resize_to_fill` with nwidth = 3840 and nheight = 2160. The `intermediate` value in `resize_dimensions` works out to 2229.793, which should be rounded up to 2230, but is instead truncated to 2229 which causes more distortion than is necessary.

This was noticeable when porting existing code away from imagemagick to just using methods from the image crate to drop that dependency.

**Comment by fintelia** [comment]
I think this makes sense to fix. Do you want to make a PR for it?
