### ISSUE TITLE
How can I save  raw pixels(w*h*c) / ImageBuffer to Vec<u8> / &[u8]?

### ISSUE THREAD

**Issue by ahaoboy** [image-rs/image#1614]
How can I save ImageBuffer to Vec<u8> / &[u8] ?
I want to save raw pixels(w*h*c) to Vec<u8>, but just find some ways can save to file.

```
let mut imgbuf = image::ImageBuffer::new(imgx, imgy);
// ...
let v: Vec<u8> = imgbuf.to_vec();
or
let mut v = vec![];
imgbuf.to_vec(&v);
```

Overall, I'm trying to achieve ...
I try to use  PngEncoder::new, but I do't find some ways to create PngEncoder by pixels.

**Comment by fintelia** [comment]
The ImageBuffer type directly derefs into a slice of channels:
```rust
let buf: &[u8] = &*img;
```
You can also use the [ImageBuffer::into_vec](https://docs.rs/image/0.23.14/image/struct.ImageBuffer.html#method.into_vec) method.

For 16-bit per pixel images, you'd then have to convert the &[u16] to a &[u8]. Something like [bytemuck::cast_slice](https://docs.rs/bytemuck/1.7.2/bytemuck/fn.cast_slice.html) should work for that

**Comment by HeroicKatora** [comment]
Note that [`DynamicImage::as_bytes`](https://docs.rs/image/0.23.14/image/enum.DynamicImage.html#method.as_bytes) will also do the same cast. So you might construct the right variant using your buffer and the utilizing that method to get access to the underlying bytes.

If you're looking for a _cheap_ way to save bytes to a file, however, then you may have a look into the [`pnm`](https://docs.rs/image/0.23.14/image/codecs/pnm/index.html) format—which has been intended for program-to-program interaction. Internally, it is _almost_ a pure byte dump but the header and byteorder convention ensures no data is lost compared to `ImageBuffer` (floating point images aren't supported though).

**Comment by ahaoboy** [comment]
Sorry for the ambiguous description.
I want to do something like this, but failed
```
    let mut img = RgbaImage::new(width, height);
    // do something ...

    let fileBuffer: Vec<u8> = vec![];
    let pixels = img.as_bytes();
    let p = PngEncoder::new(fileBuffer);
    p.encode(pixels, width, height, ColorType::Rgba8);

    let mut file = File::create("./png.png")?;
    // error: 
    // borrow of moved value: `fileBuffer`
    // borrow occurs due to deref coercion to `[u8]`
    file.write_all(fileBuffer.as_bytes())?;
```
I want use this lib in wasm, but in the wasm it does't have file system, I just can tranform Vec<u8> to js.

**Comment by ahaoboy** [comment]
I try to use  JpegEncoder and it can work ... Why their api is different?  
```
    let height = 100;
    let width = 100;
    let mut img = RgbImage::new(width, height);
    let pixels = img.as_bytes();
    let mut fileBuffer: Vec<u8> = vec![];
    let mut p = JpegEncoder::new(&mut fileBuffer);
    p.encode(pixels, width, height, ColorType::Rgb8);
    let size = fileBuffer.len();
    let ptr = fileBuffer.as_bytes();
    let mut file = File::create("./png.jpg")?;
    file.write_all(fileBuffer.as_bytes())?;
```

**Comment by HeroicKatora** [comment]
You can do the same thing in `PngEncoder`. They have the two constructors:

- `PngEncoder<W>::new(W) where W: Write`
- `JpegEncoder<W>::new(&mut W) where W: Write`

In fact, the second is _less_ generic. It's possible to pass `&mut W` to the png version as well, due to the standard library providing `impl Write for &mut W where W: Write {…}`. This impl captures all the possibilities of the jpeg constructor already, just with a different type for `W`.

**Comment by ahaoboy** [comment]
>

**Comment by ahaoboy** [comment]
> You can do the same thing in `PngEncoder`. They have the two constructors:
> 
> * `PngEncoder<W>::new(W) where W: Write`
> * `JpegEncoder<W>::new(&mut W) where W: Write`
> 
> In fact, the second is _less_ generic. It's possible to pass `&mut W` to the png version as well, due to the standard library providing `impl Write for &mut W where W: Write {…}`. This impl captures all the possibilities of the jpeg constructor already, just with a different type for `W`.

Thanks, It works
But their docs are different, I am a beginner, so I was misled. 
https://docs.rs/image/0.19.0/image/png/struct.PNGEncoder.html
![image](https://user-images.githubusercontent.com/19884146/142800222-fb7a42fa-3ae7-4af9-8b94-f7c078149f3c.png)

https://docs.rs/image/0.21.0/image/jpeg/struct.JPEGEncoder.html
![image](https://user-images.githubusercontent.com/19884146/142800249-240b5c35-7260-4ebb-ad76-61bc901b71c2.png)
