### ISSUE TITLE
Attempt to multiply with overflow in PNM decoder

### ISSUE THREAD

**Issue by saethlin** [image-rs/image#1616]
Running the PNM fuzzing target, this input produces a crash due to an attempt to multiply with overflow:
```
[80, 54, 10, 52, 50, 57, 52, 56, 50, 57, 52, 56, 35, 56, 10, 52, 10, 48, 10, 12, 12, 56]
```
It looks like the offending multiply is this: https://github.com/image-rs/image/blob/0f1c38a97ec809f399a2a5edfb85c7e17fcd46ec/src/codecs/pnm/decoder.rs#L608

I suspect this should be a `checked_mul`

**Comment by fintelia** [comment]
Yeah, I think the right fix is switching the type for the second argument from u32 -> usize while also replacing the multiplication with a `checked_mul`.
