### ISSUE TITLE
Attempt to add with overflow in PNM decoder

### ISSUE THREAD

**Issue by saethlin** [image-rs/image#1617]
More Fuzzing! Failing input to the PNM fuzzer is
```
[80, 52, 52, 50, 57, 52, 57, 54, 55, 50, 57, 50, 10, 48, 10, 49]
```
The offending line is: https://github.com/image-rs/image/blob/0f1c38a97ec809f399a2a5edfb85c7e17fcd46ec/src/utils/mod.rs#L49

I'm going to stub this out on my end, but unfortunately this looks like the PNM decoder might need some higher-level input validation before we get into this code.

**Comment by fintelia** [comment]
Decoded to ascii input is:
```
P44294967292
0
1
```
In other words, this is a width=4294967292, height=0 image.

**Comment by ScanMountGoat** [comment]
Has this already been resolved? I see test cases and checks for overflow, and I'm not able to reproduce this with the pnm fuzzer.

**Comment by fintelia** [comment]
Probably fixed then. If anyone discovers this wasn't fixed, please feel free to reopen this issue or create a new one. Or even better, submit a PR to fix it!
