### ISSUE TITLE
I used crop on an image to be sent vai email, but the result is the alt tag shown!

### ISSUE THREAD

**Issue by Lejla94** [image-rs/image#1629]
Hello fellows. I am using this crate and lettre 0.10.0-rc-4.
I am using this:
```
  let content_id = String::from("") + &index.to_string() + &"-" + &ind.to_string() + &"-" + &product.picture.name;
  let img = image::open("src/images/".to_string() + &product.picture.name+ &"." + &"jpeg").unwrap();
  let filebody = image::imageops::crop_imm(&img, 50 as u32, 50 as u32, 500 as u32, 500 as u32).to_image().into_vec();
  let content_type = "*/*".parse().unwrap(); 
  Attachment::new_inline(content_id).body(filebody, content_type)
```

To send images via email, but nothing appears inline and the image is not a jpeg.
Before i could see the images, but after adding `resize` or `crop_imm `then they do not appear to be images anymore.
Is there something wrong with lettre or any workaround to this package.

Note: the image when trying to open after changing the extension to .jpeg says it is not a jpeg but starts with 0xcf. The image is not null bytes either. Seems with lettre all images appear with the same name of the content type!
Thanks!
I am new to Rust, so the probability is i am doing something unreasonable.

**Comment by paolobarbolini** [comment]
:wave: `lettre` contributor here.

When it comes to lettre can you also attach the HTML of the email you're sending?

On the `image` crate side I think what you're doing at line 3 of your code is that you're attaching the raw unencoded pixels, instead of encoding them into a proper format like .jpg or .png

**Comment by asonix** [comment]
When you `open` the image, it decodes from a jpeg into a unique in-momory representation, then you're attaching that in-momory representation without first encoding it to a specific format.

Try using [crop_imm](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.crop_imm) to crop the DynamicImage you get from open and  [write_to](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.write_to) to encode the image to a specific format.

```rust
let img = image::open(/* blah blah */)?;
let cropped = img.crop_imm(/* blah blah */)?;

let mut jpeg_bytes = Vec::new();
cropped.write(Cursor::new(&mut jpeg_bytes), ImageOutputFormat::Jpeg(100))?;

let content_type = "*/*".parse()?;
Attachment::new_inline(content_id).body(jpeg_bytes, content_type)
```
