### ISSUE TITLE
performance question - parallel processing of JPG files

### ISSUE THREAD

**Issue by yuribudilov** [image-rs/image#1643]
Hello everyone

I am trying to process **several million images** (all in JPG files, size ~1mb-3mb per image).

Consider this line of code which appears to take most CPU time on my prototype:

**`let hash1 = hasher.hash_image(&image1); `** 

Above line of code takes about ~0.25-0.3 sec elapsed time per each JPG file, on average, running on my PC i.e. about 3-4 JPG images per 1 second (this is cargo build **--release** optimized exe).

I am using default hasher:

**`let hasher = HasherConfig::new().to_hasher();`**

Can you please tell me if this code/library uses a Single-CPU thread by default, if I am running it from single main() thread in Rust?

I have 8 logical cores on my server so I am hoping to process 8-threads concurrently to improve the elapsed time to process these millions of JPG images. I could also look as Rust async (tokio) but I suspect this is a CPU bound task that may benefit from parallel processing using thead::spawn or rayon crate etc...

Perhaps I should use a different **hasher config** for JPG files to improve performance ?

thank you for any guidance/suggestions

**Comment by fintelia** [comment]
Yeah, the crate just automatically derives Hash you might be better off implementing your own hashing. You can get the underlying bytes of an image with [DynamicImage::as_bytes](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.as_bytes) and then hash those however you'd like.

**Comment by yuribudilov** [comment]
thanks! Will check the custom hasher out.

Thoughts running the hasher.hash_image() on multiple CPU threads concurrently, for multiple JPG images, to gain elapsed time parallelism?

**Comment by fintelia** [comment]
Yes, you should be able to use multiple CPU threads as you describe, and with rayon's parallel iterators it really shouldn't be very much work.

**Comment by yuribudilov** [comment]
thank you, closing this one, much obliged ! Happy 2022 !
