### ISSUE TITLE
build failed `crc32fast v1.3.0`

### ISSUE THREAD

**Issue by AnatolyBug** [image-rs/image#1650]
Hi there,

I am very new to Rust.  I have an issue with installing image crate:
[dependencies]
image = "0.23.14"

cargo 1.57.0 (b2e52d7ca 2021-10-21)
rustc 1.57.0 (f1edd0429 2021-11-29)
 Microsoft Windows 10 Home
OS Version: 10.0.19043 N/A Build 19043

I get following compiling error:
**error: failed to run custom build command for `crc32fast v1.3.0`**

Am I missing some dependency?

Many thanks,

**Comment by HeroicKatora** [comment]
Can you post the full build error?

**Comment by AnatolyBug** [comment]
@HeroicKatora,
Yes sorry. Here is the full build error. 
<details>
error: failed to run custom build command for `crc32fast v1.3.0`
Caused by:
  could not execute process `C:\rust\combiner2\target\debug\build\crc32fast-7038adb3598a69d5\build-script-build` (never executed)
Caused by:
  The process cannot access the file because it is being used by another process. (os error 32)
warning: build failed, waiting for other jobs to finish...
error: build failed
</details>

It's odd that this local file is "used by another process". Something is def wrong.
Many thanks,

**Comment by HeroicKatora** [comment]
This usually happens in Windows if something is trying to write to an executable file while it's being executed. This should be entirely unrelated to Rust, `crc32fast`, or this library. Can you check if there is some overly eager anti virus or a CI issue [similar to this one](https://github.com/Lokathor/wide/commit/6419c50d80f84e347a2618022bf19b4f3db1643c)? I'm not sure in any case if we could help you any further.

**Comment by AnatolyBug** [comment]
@HeroicKatora,
Switching off Kaspersky worked. Thank so much for your help!
Regards,
