### ISSUE TITLE
File is created even if extension is invalid

### ISSUE THREAD

**Issue by casey** [image-rs/image#1652]
We noticed that if you call `ImageBuffer::save` a path with an invalid extension, for example `foo.invalid`, it will create an empty file called `foo.invalid`. We're using `0.23.14`. It would be nice if the file weren't created if the extension is bad.

Thanks for the awesome crate!

**Comment by fintelia** [comment]
This has been fixed on `master`, I believe unintentionally as part of unrelated refactoring. Unfortunately, we're far overdue for a new release...

**Comment by casey** [comment]
Nice, looking forward to it!
