### ISSUE TITLE
Correct way to convert an image to Bgra format

### ISSUE THREAD

**Issue by CatCode79** [image-rs/image#1653]
Hello! Is my first issue on this repo and I take this opportunity to thank you for this very useful library!

I am trying, successfully, to convert an image to Bgra format. The problem is, I feel like I'm not doing it cleanly.

I am using wgpu api graphics, this supports four formats:
`TextureFormat::Rgba8Unorm`
`TextureFormat::Rgba8UnormSrgb`
`TextureFormat::Bgra8Unorm`
`TextureFormat::Bgra8UnormSrgb`

So if the hardware returns as preferred texture format the Bgra8UnormSrgb one I need to convert the image (tipically Rgba) to Bgra.

I'm using the image 0.23.14 release and i found that the type I need, the BgraImage, is not public:
https://github.com/image-rs/image/blob/2a79d33e663d27e402c76bfc6aa5ca78b1cc9895/src/buffer.rs#L1302

I solved it by copying the BgraImage type from your crate (where it is `pub(crate)`) thus making it public in my interface:
https://github.com/irid-game-framework/irid/blob/330fb4c3a592594fc553ed9dd81b913d0c3132ce/irid_assets_interface/src/lib.rs#L22

But it was clear enough that this was not the way to go; checking the issues I found this:
[Remove Bgr and Bgra color types #1482](https://github.com/image-rs/image/pull/1482)

Do you think my use case could be enough to revert that merge and made the BgraImage public?
If not could you tell me how to swap the color channels? I couldn't figure out exactly how to do it.

Thanks for your time!

**Comment by fintelia** [comment]
You can call `image.into_raw()` to convert your image into a `Vec<u8>` of the form [r0, g0, b0, a0, r1, g1, b1, a1, r2, ...]. Then just use a for loop to convert it to [b0, g0, r0, a0, ...] order.

**Comment by CatCode79** [comment]
> You can call `image.into_raw()` to convert your image into a `Vec<u8>` of the form [r0, g0, b0, a0, r1, g1, b1, a1, r2, ...]. Then just use a for loop to convert it to [b0, g0, r0, a0, ...] order.

Thank you!

> PS: Typically with wgpu only _surface_ textures are in BGRA format, and the rest of you textures are RGBA order.

And thanks again! I realize now that I have taken the wrong approach and therefore the conversion I do to normal textures is useless.
