### ISSUE TITLE
ImageResult data is all black/white when loading images with `image::open` or `image::load_from_memory`

### ISSUE THREAD

**Issue by ArthurKValladares** [image-rs/image#1658]
Hi. I'm trying to load image data and pass it into an Ash/Vulkan buffer, but all images I try to load end up being all black/white, depending on the image. My code looks like this:

```
let image = image::load_from_memory(data).unwrap().to_rgba8();
let (width, height) = image.dimensions();
let image_extent = vk::Extent3D {
    width,
    height,
    depth: 1,
};
let image_data = image.into_raw();
```
The values in `data` look correct:
```
[137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 4, 176, 0, 0, 3, 32, 8, 6, 0, 0, 0, 51, 224, 155, 2, 0, 0, 0, 25, 116, 69, 88, 116, 83, 111, 102, 116, 119, 97, 114, 101, 0, 65, 100, 111, ...
```

But the buffer in `image/image_data` returns all zeros:

```
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
```

I'm not too sure what I'm doing wrong, I would appreciate some direction. This is on version `0.23`, on Windows 10 for whatever it's worth.

**Comment by HeroicKatora** [comment]
Regarding the input image, can you provide the image or as much of its metadata (format, size, …) as possible? This looks to be likely a problem with a decoder and this is necessary to determine the faulty code path.

**Comment by ArthurKValladares** [comment]
It happened on these 3 png images.  The earth texture returned all [255, 255, 255, 0] as opposed to all [0, 0, 0, 0]
The decoder code is copied from the texture example in ash, and the images render correctly when building their example. 
![earth](https://user-images.githubusercontent.com/23410311/151334988-b5944261-e98a-435e-b7b6-e1f83fea312b.png)
![ferris](https://user-images.githubusercontent.com/23410311/151334994-8b1bdbbb-d2fb-4bb4-9124-e49a7c14ffae.png)
![rust](https://user-images.githubusercontent.com/23410311/151334996-d32fac33-cc05-43db-878f-ce15f9a026f2.png)

**Comment by ArthurKValladares** [comment]
Nevermind ,I figured out my mistake, the image was loading correctly and if I looked deeper into the buffer I would have seen non-zero results. I was just being stupid.
