### ISSUE TITLE
Png encoder and BGRA format lead to panic

### ISSUE THREAD

**Issue by nikitablack** [image-rs/image#1660]
This happens in the following code:

```
let mut imgbuf = image::ImageBuffer::new(extent.width, extent.height);

for x in 0..extent.width {
    for y in 0..extent.height {
        // code to get r, g, b and a

        let pixel = imgbuf.get_pixel_mut(x, y);
        *pixel = image::Bgra([r, g, b, a]);
    }
}

imgbuf.save("screenshot.png").unwrap();
```

## Expected

According to documentation, `png` supports encoding and decoding of all supported color formats. But looking at the implementation I see only the following formats are supported:

- ColorType::L8
- ColorType::L16
- ColorType::La8
- ColorType::La16
- ColorType::Rgb8
- ColorType::Rgb16
- ColorType::Rgba8
- ColorType::Rgba16

## Actual behaviour

The application crashes with the message:

>thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported(UnsupportedError { format: Exact(Png), kind: Color(Bgra8) })'

**Comment by fintelia** [comment]
Unfortunate phrasing. We support encoding all of the color formats that PNG supports, which doesn't include BGRA. We're actually removing BGRA handling in the next major release, partly due to inconsistent support as you've noticed here.
