### ISSUE TITLE
Handling raw buffer (posting to s3)

### ISSUE THREAD

**Issue by acollierr17** [image-rs/image#1666]
I've been trying to take the raw buffer and use its contents to put an image into an s3 bucket I have using the https://github.com/durch/rust-s3 library. I believe I can "read" the buffer somehow, such as if I were to do a multi-part file upload (I've done this in Go before). However, I'm not sure what direction to take in Rust.

Overall, I'm trying to use the buffer to write to an actual image I can save into s3. I'm fairly new to Rust, so I'm all ears. I have some code snippets below so you can get an idea of what I'm trying to do. It's very barebones right now as I'm trying to get basic functionality. But hopefully, y'all can get the gist.

```rust
// inside my "upload_image" function
let mut img = RgbaImage::new(512, 512);
// some image manipulation stuff
img.save("image/assets/test.png").unwrap(); // for development purposes only

spaces::upload_image(img.as_raw().clone()); // this is where I pass in the raw buffer. here's when things get tricky.
```
Now here's the `spaces::upload_image` function I wrote:
```rust
// spaces::upload_image()
pub async fn upload_image(bytes: Vec<u8>) {
    untokio::v1::spawn(async move {
        let mut bucket = get_bucket();
        bucket.add_header("Content-Length", &*bytes.len().to_string()); // i added this from a go project of mine hoping this makes a difference

		// here's where I wrote the buffer back to the file system as a test. its corrupted
		let path = std::path::Path::new("image/assets/test-1.png");
        let mut file = std::fs::File::create(&path)?;

		file.write_all(bytes.as_bytes(); // is this even proper?

        return bucket
            .put_object_with_content_type(
                "unknown.png",
                bytes.as_bytes(), // is this even proper too?
                "image/png"
            )
            .await;
    }).await.unwrap();
}
```

**Comment by fintelia** [comment]
You are confusing image file formats like PNG with raw pixel data as returned from ImageBuffer::as_raw. If you want to encode an image as a PNG and get a Vec of the resulting bytes, use:
```rust
let mut bytes: Vec<u8> = Vec::new();
img.write_to(&mut Cursor::new(&mut bytes), image::ImageOutputFormat::Png)?;
```

**Comment by acollierr17** [comment]
I can't use the `write_to` method in this case on `ImageBuffer`. Similar to #1548 as well. Any other options I have? I'll keep digging through the docs to see if I can come up with something.

**Comment by fintelia** [comment]
You can always turn a RgbaImage into a DynamicImage by doing `DynamicImage::IamgeRgba8(img)`. But as now mentioned in that other issue, starting with the 0.24 release [ImageBuffer::write_to](https://docs.rs/image/latest/image/struct.ImageBuffer.html#method.write_to) is also now available

**Comment by acollierr17** [comment]
Got it. That helps and wraps up my inquiry then. Thank you for the help!
