### ISSUE TITLE
can we generate thumbnail with AspectFill style? 

### ISSUE THREAD

**Issue by keepsimple1** [image-rs/image#1667]
https://github.com/image-rs/image/blob/398b087ca8b97322f216a159e40414cdb408e29b/src/imageops/sample.rs#L424

The above method can generate a thumbnail given (width, height), however if the ratio does not match with the original image the thumbnail will look aspect-skewed.    Example: the original is (300, 500), and the thumbnail is (100, 100), the thumbnail looks skewed.

Is there a way to keep the aspect of the original image when the thumbnail aspect is different? for example, by allowing cropping?  (i.e. the so-called "AspectFill" style)?

**Comment by keepsimple1** [comment]
never mind, I found that I can use `DynamicImage::resize_to_fill`.

**Comment by samdenty** [comment]
`DynamicImage::resize_to_fill` crops the image whereas with a thumbnail you probably want it padded instead
