### ISSUE TITLE
DynamicImage::resize_to_fill runs very slow

### ISSUE THREAD

**Issue by keepsimple1** [image-rs/image#1669]
https://github.com/image-rs/image/blob/e4af9c8ba83788b55e5fe2a06c1cc305e06376a8/src/dynimage.rs#L695-L700

I'm using this `resize_to_fill` to resize a PNG image original (2878, 1800) to small size (274, 274) JPEG.  It took 17 seconds, which is very slow to me.

Hardware: MacBook Pro 2015, CPU: 2.2 GHz Quad-Core Intel Core i7,  Memory: 16 GB. macOS: Big Sur. 

Is it a known issue that `resize_to_fill` is very slow?  or maybe I didn't use it properly?

**Comment by fintelia** [comment]
Are you running with optimization (`cargo run --release`)? That would be the first thing to check

**Comment by keepsimple1** [comment]
you're right.  I forgot that. It's better much faster in release.  I also counted `decode` together with `resize_to_fill`. In any case, now the time is `decode 85 mills resize 291 mills`. Much better :) Thanks!
