### ISSUE TITLE
Resizing SubImage

### ISSUE THREAD

**Issue by bertiqwerty** [image-rs/image#1670]
Hi there. Thanks for the nice crate!

How does one resize a `SubImage` in version `0.24.0`? In `0.23.*` one could use `imageops::resize`. In `0.24.0` somehow `SubImage` stopped implementing `GenericImageView`.

Overall, I'm trying to resize a `SubImage` without an additional copy.

**Comment by HeroicKatora** [comment]
The error is caused by Rust not performing auto-deref for generic arguments. You'll want to dereference the sub-image to the inner image. You can use:

```rust
pub fn example(img: &mut DynamicImage, filter: imageops::FilterType) {
    let sub_image = img.sub_image(0, 0, 10, 10);
    let resized = imageops::resize(&*sub_image, 100, 100, filter);
}
```

**Comment by bertiqwerty** [comment]
Ah. This works. Thanks!
