### ISSUE TITLE
`ImageBuffer::get_pixel_checked` sometimes returns incorrect pixel

### ISSUE THREAD

**Issue by julienc** [image-rs/image#1672]
In certain cases, the functions `ImageBuffer::get_pixel_checked` and `ImageBuffer::get_pixel_mut_checked` seem to return a shifted pixel reference.

## Reproduction steps

The following code creates a 2x1 RGB image buffer, sets the second pixel to white, then reads its color.
Reading with `get_pixel` succeeds with white but `get_pixel_checked` results in a blue pixel.

(On  [Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f5658a90ff8bf1ba9250b08ee1b9f16c))

```rust
use image::{Rgb, RgbImage};

const WHITE: Rgb<u8> = Rgb([255, 255, 255]);

fn main() {
    let mut img = RgbImage::new(2, 1);

    img.put_pixel(1, 0, WHITE);

    assert_eq!(img.get_pixel(1, 0), &WHITE);
    assert_eq!(img.get_pixel_checked(1, 0).unwrap(), &WHITE);
}
```

The second assert fails:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Rgb([0, 0, 255])`,
 right: `Rgb([255, 255, 255])`', src/main.rs:11:5
```

**Comment by fintelia** [comment]
It seems that get_pixel_checked [never actually multiples by the number of channels in the image](https://github.com/image-rs/image/blob/e4af9c8ba83788b55e5fe2a06c1cc305e06376a8/src/buffer.rs#L735-L742).

**Comment by PoignardAzur** [comment]
Well damn, I was just about to file the same bug report.
