### ISSUE TITLE
DynamicImage.write_to(...) does not accept Vec<u8> anymore?

### ISSUE THREAD

**Issue by acirep** [image-rs/image#1673]
This piece of code was perfectly happy in `0.23.*` 

```Rust
        let img = DynamicImage::ImageRgb8(ImageBuffer::from_raw(1024, 768, buff).unwrap());
    
        let mut png: Vec<u8> = Vec::new();

        img
          .write_to(&mut png, ImageOutputFormat::Png)
          .expect("Failed to convert image to png");
```

where `buff` is also `Vec<u8>`

However in `0.24` I get a compile error

```
error[E0277]: the trait bound `Vec<u8>: Seek` is not satisfied
   --> src/.../mod.rs:143:21
    |
143 |           .write_to(&mut png, ImageOutputFormat::Png)
    |            -------- ^^^^^^^^ the trait `Seek` is not implemented for `Vec<u8>`
    |            |
    |            required by a bound introduced by this call
```

Is there a way to wrap `png: Vec<u8>` here so this will work or do I need to use something else now?

**Comment by asonix** [comment]
https://doc.rust-lang.org/std/io/struct.Cursor.html

**Comment by HeroicKatora** [comment]
You'll need to wrap it in `std::io::Cursor::new(&mut png)`, in other regards the code can stay the same. It is no longer necessary to wrap the image in `DynamicImage` if you have a concrete supported ImageBuffer:

```rust
// Wraps the buffer to be seekable.
use std::io::Cursor;

let image = ImageBuffer::<image::Rgb<u8>, _>
        ::from_raw(1024, 768, vec![0u8; 3*1024*768]).unwrap();
    
let mut png: Vec<u8> = Vec::new();
    
image
    .write_to(&mut Cursor::new(&mut png), ImageOutputFormat::Png)
    .expect("Failed to convert image to png");
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=94b7742f88f70a16276e29ea09ede3a1

**Comment by acirep** [comment]
Thank you both so much! :100: Cursor is exactly what I needed - building my rust knowledge bit by bit every day :pray:
