### ISSUE TITLE
Unsure how to use as_rgba

### ISSUE THREAD

**Issue by rokonio** [image-rs/image#1676]
I have an error when the function `as_rgba` return a value for some a file and a None on another. I'm very new to image programming so I don't know much about the conversion methods but the documentation does not help and I thinks that's a problem. Indeed, the documentation explains nothing about when the function could return None.

**Comment by fintelia** [comment]
The `as_XXX` functions don't do any conversions. Rather they return Some if the image is _already_ in the request format, and None otherwise. If you want to do conversion, use `to_XXX` (if you want to make a copy) or `into_XXX` (if you want to take ownership).
