### ISSUE TITLE
How to resize an ImageBuffer

### ISSUE THREAD

**Issue by tqwewe** [image-rs/image#1677]
How does one resize an ImageBuffer?

Overall, I'm trying to capture my webcam with the `nokhwa` crate, which gives me an `ImageBuffer` per frame, and shrink the image buffer so I can enumerate over the pixels (with x and y position).

**Comment by fintelia** [comment]
The [`imageops::resize`](https://docs.rs/image/latest/image/imageops/fn.resize.html) function can take an `ImageBuffer`.
