### ISSUE TITLE
PNG decoding regression

### ISSUE THREAD

**Issue by HactarCE** [image-rs/image#1679]
I loaded [this PNG file](https://github.com/HactarCE/InfiniteMinesweeper/blob/b073f32618563bb92a23ecb2015a52e2d59b3785/src/render/textures/tiles_64.png) using the following function:

```rs
fn load_rgba_image(image_bytes: &[u8]) -> RawImage2d<'_, u8> {
    let image = image::load_from_memory(image_bytes)
        .expect("Failed to load image data")
        .to_rgba8();
    let dimensions = image.dimensions();
    RawImage2d::from_raw_rgba_reversed(&image.into_raw(), dimensions)
}
```
where `image_bytes = include_file!("tiles_64.png")`

## Expected

The image loads successfully, as happens on version 0.23.14.

## Actual behaviour

On version 0.24.1, this error is produced:

```
Decoding(DecodingError { format: Exact(Png), underlying: Some(Format(FormatError { inner: DuplicateChunk { kind: ChunkType { type: gAMA, critical: false, private: false, reserved: false, safecopy: false } } })) })
```

## Reproduction steps

If you don't mind building glium and a handful of other dependencies, you can use [this repository](https://github.com/HactarCE/InfiniteMinesweeper) and update the version of `image` in `Cargo.toml` to `"0.24.1"` to reproduce the error.

**Comment by tronical** [comment]
This might be https://github.com/image-rs/image-png/issues/340
