### ISSUE TITLE
How to convert Rgba8 to Rgba32F for encoding OpenEXR?

### ISSUE THREAD

**Issue by orhun** [image-rs/image#1681]
I'm trying to encode an OpenEXR image using [`Rgba<u8>`](https://docs.rs/image/latest/image/struct.Rgba.html) pixels. For example, let's say that I have the following pixel data:

```rs
// 1x2 RGBA image data
let data = vec![
    Rgba::<u8>::from([0, 0, 0, 255]),
    Rgba::<u8>::from([255, 255, 255, 255]),
];
```

Normally, I'd convert this to `Vec<u8>` for encoding images in `Rgba8` like this:

```rs
let rgba8_data = data.iter().fold(Vec::<u8>::new(), |mut data, rgba| {
    data.extend(vec![rgba[0], rgba[1], rgba[2], rgba[3]]);
    data
});
```

(I'm doing this conversion because [`write_image`](https://docs.rs/image/latest/image/trait.ImageEncoder.html#tymethod.write_image) method accepts `&[u8]` as buffer.)

Then I can e.g. encode PNG without problems:

```rs
let png_encoder = PngEncoder::new(File::create("test.png").unwrap());
png_encoder.write_image(&rgba8_data, 1, 2, ColorType::Rgba8).unwrap();
```

However, when I want to encode OpenEXR, I'm not sure what to do for step 2 (conversion from `Rgba`):

```rs
let rgba32f_data = data.iter().fold(Vec::<u8>::new(), |mut data, rgba| {
        
    // What do I do here to have 16 bytes per pixel?
    data.extend(vec![rgba[0], rgba[1], rgba[2], rgba[3]]);

    data
});
```

<details>
<summary>Full example</summary>

```rs
use image::{
    codecs::openexr::OpenExrEncoder, codecs::png::PngEncoder, ColorType, ImageEncoder, Rgba,
};
use std::fs::File;

fn main() {
    // 1x2 RGBA image data
    let data = vec![
        Rgba::<u8>::from([0, 0, 0, 255]),
        Rgba::<u8>::from([255, 255, 255, 255]),
    ];

    // Create a PNG encoder.
    let png_encoder = PngEncoder::new(File::create("test.png").unwrap());
    // Convert `Vec<Rgba<u8>>` to `Vec<u8>`
    let rgba8_data = data.iter().fold(Vec::<u8>::new(), |mut data, rgba| {
        data.extend(vec![rgba[0], rgba[1], rgba[2], rgba[3]]);
        data
    });
    // Write image.
    png_encoder
        .write_image(&rgba8_data, 1, 2, ColorType::Rgba8)
        .unwrap();

    // Create a OpenEXR encoder.
    let exr_encoder = OpenExrEncoder::new(File::create("test.exr").unwrap());
    // Convert `Vec<Rgba<u8>>` to `Vec<u8>`
    let rgba32f_data = data.iter().fold(Vec::<u8>::new(), |mut data, rgba| {
        
        // What do I do here to have 16 bytes per pixel?
        data.extend(vec![rgba[0], rgba[1], rgba[2], rgba[3]]);

        data
    });
    // Write image.
    exr_encoder
        .write_image(&rgba32f_data, 1, 2, ColorType::Rgba32F)
        .unwrap();
}
```

</details>

`image` version: `0.24.1`

**Comment by sassman** [comment]
I'm not an expert with OpenEXR at all. But 16 byte per pixel could simply mean that every color channel is not one `u8` but one `u32`. 

```rust

    // What do I do here to have 16 bytes per pixel?
    data.extend(vec![rgba[0], rgba[1], rgba[2], rgba[3]]);

```

so did you try simply to cast here every entry as `u32` and write them?

**Comment by orhun** [comment]
> so did you try simply to cast here every entry as `u32` and write them?

As I said [`write_image`](https://docs.rs/image/latest/image/trait.ImageEncoder.html#tymethod.write_image) method accepts `&[u8]` as buffer so I need `Vec<u8>` not `Vec<u32>` 😕

**Comment by HeroicKatora** [comment]
It expects the native-endian byte representation (common denominator of all texel types).

```
for &channel in &rgba[..] {
    data.extend_from-slice(&channel.to_ne_bytes());
}
```

**Comment by orhun** [comment]
> It expects the native-endian byte representation (common denominator of all texel types).

Thanks for your reply! I tried the following:

```rs
let rgba32f_data = data.iter().fold(Vec::<u8>::new(), |mut data, rgba| {
    for &channel in rgba.channels() {
        data.extend_from_slice(&channel.to_ne_bytes());
    }
    data
});
```

But now I'm getting an error while encoding OpenEXR:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Encoding(EncodingError { format: Exact(OpenExr), underlying: Some("byte buffer not large enough for the specified dimensions and f32 pixels") })', src/main.rs:38:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any ideas?

**Comment by sassman** [comment]
But would you not need to normalize the value, like dividing by the maximum as e.g. ` / 255` for every color channel?

**Comment by sassman** [comment]
But do you get the right colors in your image then?

I was pretty sure you would need to convert it to a percentage like color value range as for example:

```rust
        data.extend_from_slice(&(channel as f32 / 255.).to_ne_bytes());
```

**Comment by orhun** [comment]
> But do you get the right colors in your image then?
> 
> I was pretty sure you would need to convert it to a percentage like color value range as for example:

Good point! I didn't realize the colors wasn't correct, only checked the file format 🙈

Dividing each channel with 255 makes it work like a charm. Thank you! 💯

**Comment by fintelia** [comment]
The intended way of implementing this is map over the pixel components to produce a `Vec<f32>`. Then in a second step, convert it to a `&[u8]` using something like [`bytemuck::cast_slice(...)`](https://docs.rs/bytemuck/latest/bytemuck/fn.cast_slice.html) or [`.align_to().1`](https://doc.rust-lang.org/std/primitive.slice.html#method.align_to)

If you use a `Vec<u8>` directly, then there is a chance it won't be aligned to a four byte boundary. This is disallowed according to the documentation, [although the code itself doesn't care](https://github.com/image-rs/image/blob/060a41c491a7b9cb7d1ebb3be5a100c8c3c73972/src/codecs/openexr.rs#L278).

**Comment by orhun** [comment]
> The intended way of implementing this is map over the pixel components to produce a `Vec<f32>`. Then in a second step, convert it to a `&[u8]` using something like [`bytemuck::cast_slice(...)`](https://docs.rs/bytemuck/latest/bytemuck/fn.cast_slice.html) or [`.align_to().1`](https://doc.rust-lang.org/std/primitive.slice.html#method.align_to)
> 
> If you use a `Vec<u8>` directly, then there is a chance it won't be aligned to a four byte boundary. This is disallowed according to the documentation, [although the code itself doesn't care](https://github.com/image-rs/image/blob/060a41c491a7b9cb7d1ebb3be5a100c8c3c73972/src/codecs/openexr.rs#L278).

So do you suggest not doing it this way? I think there is a limitation in `image-rs`'s side which is it requires you to use `Vec<u8>` while encoding. What are the visible side effects of this conversion?

**Comment by fintelia** [comment]
> So do you suggest not doing it this way?

What you're doing is fine for now. There's a possibility that we'll change it to returning an error in some future major version bump, but even that's not certain.

> I think there is a limitation in image-rs's side which is it requires you to use Vec<u8> while encoding.

It requires a `&[u8]` while encoding. But you can temporarily convert a `Vec<f32>` to a `&[u8]` essentially for free using one of those linked methods:

```rust
let rgba32f_data: Vec<f32> = ...;
exr_encoder
    .write_image(bytemuck::cast_slice(&rgba32f_data), 1, 2, ColorType::Rgba32F)
    .unwrap();
```

> What are the visible side effects of this conversion (especially while encoding OpenEXR)?

There shouldn't be any side effects. The conversion is always safe, cannot fail, and internally just involves a tiny bit of pointer manipulation.

**Comment by johannesvollmer** [comment]
Is it not possible to use `ImageBuffer<Rgba<f32>>`? Why do we need to handle any bytes explicitly here at all?

**Comment by fintelia** [comment]
I think you're right that `.save()` now works for `Rgba<f32>`. Want to open a PR to correct that?

**Comment by johannesvollmer** [comment]
Yes. By the way, is there no functionality to convert between rgb8 and rgb32f? Maybe we can add some new function beside to_grayscale?
