### ISSUE TITLE
Clarify alignment requirements for OpenExrEncoder::write_image

### ISSUE THREAD

**Issue by fintelia** [image-rs/image#1682]
The function documentation for OpenExrEncoder::write_image currently says:
> Returns an Error if the buffer is not aligned to f32

Although the code itself doesn't care:
https://github.com/image-rs/image/blob/060a41c491a7b9cb7d1ebb3be5a100c8c3c73972/src/codecs/openexr.rs#L278-L285

See also: https://github.com/image-rs/image/issues/1681#issuecomment-1060755806

**Comment by fintelia** [comment]
In that case, it sounds like all that is needed is a documentation change to clarify that there are no alignment requirements for the input buffer.

**Comment by johannesvollmer** [comment]
Yes, the documentation was not updated. The code itself was adjusted to work with any alignment :)

**Comment by johannesvollmer** [comment]
> It should just copy the data into a local, aligned buffer in any case, not enforce any alignment of the input buffer. The unit is 4 bytes so this doesn't even require any allocation.

The f32 is looked up directly from the unaligned buffer by extracting 4 bytes individually, and then constructing the float from those. 

Do you mean it is possible to align the whole byte buffer to 4 without converting each few individually?

**Comment by johannesvollmer** [comment]
Fixed in #1692
