### ISSUE TITLE
webp getting converted to grayscale upon encoding to jpeg

### ISSUE THREAD

**Issue by sam0x17** [image-rs/image#1683]
Loading this webp image and re-encoding as jpeg using code I've used on 1000s of other images. Something about this particular image is off, but it works fine when I load it in standard image editors.

https://s3.amazonaws.com/sam0x17.dev/AdventureTime.webp

## Expected

Should result in a jpeg resembling the original image

## Actual behaviour

End up with a jpeg of the original image in grayscale

## Reproduction steps

1. load that webp image from https://s3.amazonaws.com/sam0x17.dev/AdventureTime.webp using image crate
2. encode as jpeg

**Comment by fintelia** [comment]
Unfortunately, we don't yet fully support decoding webp images so what you're seeing is expected. There was some work to address this in (https://github.com/image-rs/image/pull/952) but that seems to have stalled out for the moment. But if anyone is interesting in reviving the effort, PRs are always appreciated!

**Comment by tristanphease** [comment]
I tested this myself, and got the image as jpeg in colour. You will need to be using version 0.24 though.

**Comment by tristanphease** [comment]
> Unfortunately, we don't yet fully support decoding webp images so what you're seeing is expected. There was some work to address this in (#952) but that seems to have stalled out for the moment. But if anyone is interesting in reviving the effort, PRs are always appreciated!

Just FYI, that PR is probably outdated at this point, although some of the things like more commenting and separating out the code more would be nice.

**Comment by sam0x17** [comment]
thanks for the heads up. I will upgrade to the new version!
