### ISSUE TITLE
png image bytes -> thumbnail -> to bytes -> back to png does not work

### ISSUE THREAD

**Issue by Jasperav** [image-rs/image#1693]
I have some bytes which is a PNG image. I want to resize the PNG and upload the thumbnail bytes to the server. However, I get an error while converting the bytes back to a PNG. This is my code:

```
let png = include_bytes!("image_for_test.png").to_vec();
let image = libs::image::load_from_memory_with_format(&png, ImageFormat::Png).unwrap();
let image = image.resize(50, 50, FilterType::Nearest);
let bytes = image.as_bytes();

libs::image::load_from_memory_with_format(bytes, ImageFormat::Png).unwrap(); // <-- this fails
```

This fails:

```
called `Result::unwrap()` on an `Err` value: Decoding(DecodingError { format: Exact(Png), underlying: Some(InvalidSignature) })
thread 'media::uploader::test::temp' panicked at 'called `Result::unwrap()` on an `Err` value: Decoding(DecodingError { format: Exact(Png), underlying: Some(InvalidSignature) })', entities/src/media/uploader.rs:317:76
```

I also tried the `thumbnail` method instead of `resize`, but it gives the same error. I don't know the difference between the two.

**Comment by HeroicKatora** [comment]
`image.as_bytes()` does not encode, it's the pure rgb pixels. You want

```
let mut buffer = Cursor::new(vec![]);
image.write_to(&mut buffer, ImageFormat::Png)?;
```

**Comment by Jasperav** [comment]
@HeroicKatora Thanks, I am only wondering why you wrap it in a Cursor because a raw `vec![]` is also working

**Comment by HeroicKatora** [comment]
You're on `0.23`? Then yes, in newer versions it requires an implementation of `Seek` which is the reason for Cursor wrapping.
