### ISSUE TITLE
Avoid temporary copy of SubImage when used with copy_from

### ISSUE THREAD

**Issue by thomak-dev** [image-rs/image#1709]
I'm trying to copy_from a view (a SubImage) but since SubImage is not a GenericImageView, I have to use to_image which makes a temporary copy. Is it possible to avoid this?

**Comment by fintelia** [comment]
It isn't showing up properly from the documentation, but SubImage::deref() returns a SubImageInner which does implement GenericImageView.

**Comment by thomak-dev** [comment]
Ahhh, tried many things but not that, thanks.
