### ISSUE TITLE
Need explanation for the output of `ImageDecoder::read_image`

### ISSUE THREAD

**Issue by anhtumai** [image-rs/image#1711]
I use `ImageDecoder::read_image` to read this image data
![screenshot](https://user-images.githubusercontent.com/32799668/167245217-49ac3b65-02fd-4b5d-9c67-c6f8d076c72e.png)

```rust
use image::ImageDecoder;
use std::fs::File;

fn main() {
    let mut image_file = File::open("inputs/screenshot.png").unwrap();
    let image = image::codecs::png::PngDecoder::new(&mut image_file).unwrap();

    let color_type = image.color_type();

    let num_image_bytes = image.total_bytes();
    let mut image_data = vec![0; num_image_bytes as usize];
    image.read_image(&mut image_data).unwrap();

    println!("{:?}", color_type);
    println!("{:?}", image_data);
}
```

My output is:
 
![image](https://user-images.githubusercontent.com/32799668/167245275-ea7723bb-fd3a-4eee-a2c6-a22d7e582624.png)

I think the value for 1 pixel in RGBA should be (integer, integer, integer, float) and the alpha value should be between 0.0 and 1.0. However, the fourth value in the array is 255. To get the alpha value, can I divide the fourth value by 255?

**Comment by fintelia** [comment]
Yes, in Rgba8 format the alpha values range from 0 to 255 with 0 being fully transparent and 255 being fully opaque. If you want to convert to a value between 0.0 and 1.0 you'd just have to divide.

**Comment by anhtumai** [comment]
Thanks @fintelia 

does the format [Red1, Green1, Blue1, Alpha1, Red2, Green2, Blue2, Alpha2, ....] also apply for other Rgba type, like Rgba16?

**Comment by anhtumai** [comment]
about the Rgba16 format, image data is also a vector of u8. Does the format [Red1, Green1, Blue1, Alpha1,..., RedN, GreenN, BlueN, AlphaN] still apply for Rgba16?

**Comment by anhtumai** [comment]
what is the difference between the output of `image.read_image(...)` of a Rgba8  and Rgba16? And also between L8 and L16, La8 and La16, ...

**Comment by fintelia** [comment]
The ___16 formats are slices of u16's "transmuted" to slices of u8.  So the order of Rgba16 is [Red1a, Red1b, Green1a, Green1b, Blue1a, ..., AlphaNa, AlphaNb]. Often, if you are dealing with one of the 16-bit per channel formats, you'd use [`bytemuck::cast_slice_mut`](https://docs.rs/bytemuck/latest/bytemuck/fn.cast_slice_mut.html):
```rust
let mut v = vec![0u16; SIZE]; // v will hold [R1, G1, B1, A1, R2, ...]
image.read_image(bytemuck::cast_slice_mut(&mut v))?;
```

**Comment by anhtumai** [comment]
thanks @fintelia , I understand
