### ISSUE TITLE
Is this library async-friendly?

### ISSUE THREAD

**Issue by Directory** [image-rs/image#1713]
I am writing a webserver (rocket framework) which has async io support. When rocket receives a file it stores it in the os temp dir and i use `image::io::Reader::open(file.path().unwrap())` to open the file. Since this reads bytes from the filesystem i would expect this to be blocking for anything async in the thread. same for `DynamicImage.write_to()`. This would block the main thread since its not awaited correct? was async every considered or should the blocking io be a factor for me to consider? 

im considering just using `DynamicImage.write_to()` and use that buffer to write to the filesys with `tokio::fs::write` and read also from a tokio awaited buffer. (update: did that and it works fine)

**Comment by HeroicKatora** [comment]
The library was too early to have considered async, so sadly no. We're also blocked on [async-traits in `std`](https://rust-lang.github.io/async-book/07_workarounds/05_async_in_traits.html) given that the main decoder interface *is a trait*. It wasn't worth it at the time to depend on the full machinery of a crate in flux at the time, it might be time now. Sadly it also means rewriting every decoder to support that and ensure their methods are also `async fn`, which is inconvenient.

That said, some of the decoders isolate their IO components decently well and it actually might happen. For now, you'll want to use a separate thread for the blocking work.

**Comment by kaj** [comment]
A fully separate thread (or at least the explicit handling of a fully separate thread) may not be necessary.  If I remember correctly, rocket uses tokio?  If so, there is [`tokio::task::spawn_blocking`](https://docs.rs/tokio/1.18.2/tokio/task/fn.spawn_blocking.html) thats run things on a thread-pool just for things like this.

**Comment by fintelia** [comment]
Another thing to consider is that `image` supports decoding and encoding from in-memory buffers. So you could for instance use async code to load an image file into a Vec and then a subsequent decode step wouldn't do any blocking I/O calls into the OS.

**Comment by Directory** [comment]
yup im doing both of those tokio read and write the file bytes from the fs into memory, and then spawn_blocking to offload the cpu intensive image stuff.

**Comment by HeroicKatora** [comment]
This has been sufficiently answered. Feel free to open other issues for concrete ideas how to *add* certain levels of async support though.
