### ISSUE TITLE
Missing big-endian support for exr

### ISSUE THREAD

**Issue by botovq** [image-rs/image#1715]
The image crate 0.24.x fails to compile with default features big-endian platforms. This is unfortunate since various things, like [clamav][1] or [czkawka][2] started depending on the latest image crate, so they need patching to keep working on big-endian architectures.

Should a feature that is enabled by default not work on all platforms?

## Expected

The image crate compiles. This works fine for 0.23.x. It was broken with https://github.com/image-rs/image/pull/1475 that added exr to the default features.

## Actual behaviour

Compilation fails with 

```
error: expected `,`, found `function`
  --> /usr/obj/ports/czkawka-4.1.0/czkawka-4.1.0/modcargo-crates/exr-1.4.2/src/compression/rle.rs:39:29
   |
39 |         unimplemented!(this function probably returns little-endian data);
   |                             ^^^^^^^^ expected `,`

error: could not compile `exr` due to previous error
```
According to https://github.com/johannesvollmer/exrs/issues/155#issuecomment-1119288212 the missing quotes are deliberate to cause  a compile time failure rather than a runtime failure.

## Reproduction steps

Attempt to compile on a big-endian platform such as sparc64 or powerpc.

[1]: https://github.com/Cisco-Talos/clamav/blob/main/libclamav_rust/Cargo.toml#L15
[2]: https://github.com/qarmin/czkawka/blob/master/czkawka_gui/Cargo.toml#L32

**Comment by johannesvollmer** [comment]
Luckily, today I have time to try to add big-endian support. It might take me more than one day though. Until it is there, we have several quick fixes available. For example, disabling the `exr` feature on big endian architectures by default in the image crate, until `exrs` supports it. Until this happens, all users of the image library can also disable the exr feature as a work-around.

**Comment by johannesvollmer** [comment]
> the missing quotes are deliberate to cause a compile time failure rather than a runtime failure

Well, the missing quotes are probably not intentional, I apologize. I was sure that I had inserted intentional compile-time errors in other places in the code, but it seems that there are none. Anyways, I'll try to actually finish the big-endian support today :)

**Comment by johannesvollmer** [comment]
see #1771
