### ISSUE TITLE
cargo:warning= #include <OpenImageIO/paramlist.h>

### ISSUE THREAD

**Issue by sammeboy635** [image-rs/image#1719]
## Problem
I'm just trying to open an image up for processing but i'm met with a compile error on my mac m1. I did install "brew install openimageio" thinking that might fix it but it didn't. I would love to know how to fix this problem if you have any ideas. Thanks
## System
samuelwaite@Samuels-MacBook-Air screenshots % system_profiler SPSoftwareDataType SPHardwareDataType
Software:

      System Version: macOS 12.3.1 (21E258)
      Kernel Version: Darwin 21.4.0
      Boot Volume: Untitled
      Boot Mode: Normal
      Computer Name: Samuel’s MacBook Air
      User Name: Samuel Waite (samuelwaite)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 28 days 13:18

Hardware:

      Model Name: MacBook Air
      Model Identifier: MacBookAir10,1
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 8 GB
      System Firmware Version: 7459.101.3
      OS Loader Version: 7459.101.3
      Serial Number (system): FVFDR117Q6L5
      Hardware UUID: 64E90150-57B0-5537-8F30-FAD0488A8F1A
      Provisioning UDID: 00008103-001C70A10E62001E
      Activation Lock Status: Disabled
## Implementation

    use image::{GenericImageView, ImageBuffer, RgbImage, imageops};
    fn main() {
        let mut img: RgbImage = ImageBuffer::new(512, 512);
        let subimg = imageops::crop(&mut img, 0, 0, 100, 100);
        
        assert!(subimg.dimensions() == (100, 100));
    }

## Expected

I was expecting to compile. 

## Actual behaviour
 ran "Cargo run" and Couldn't compile with basic implementation.
<img width="1014" alt="Screen Shot 2022-05-28 at 10 50 53 AM" src="https://user-images.githubusercontent.com/33207323/170834992-5ce677f9-a08a-485e-93d7-c92e118fe726.png">

**Comment by HeroicKatora** [comment]
Wrong repo, I believe. You're looking for https://github.com/zshipko/image2-rs
