### ISSUE TITLE
Format and Dimensions

### ISSUE THREAD

**Issue by MichalMoravik** [image-rs/image#1720]
Hi! 

I am trying to get simple things like `.format()` or `.dimensions()` but those methods don't exist on `DynamicImage`. Is it necessary to convert it to something else (e.g. a buffer) at the beginning?

```
let loaded_img = ImageReader::new(Cursor::new(bytes)).with_guessed_format()?.decode()?;

let (width, height) = loaded_img.dimensions(); 
let format = loaded_img.format();
```

Lastly, does anyone know about any articles/code examples about image-rs? Even some open-source GH repos might be sufficient. I was not able to find any sources that I can use to understand the basic concepts of this crate. Thanks a lot! :)

**Comment by MichalMoravik** [comment]
UPDATE: I was able to get the dimensions but not the format yet. Still, I would be really grateful for those articles/repos if you have some examples. Thanks!

**Comment by HeroicKatora** [comment]
The last step already decodes into a pixel matrix. The format and other decoding state is left behind in the reader. If you want to get anything else from it then do something with the object before calling `decode`.

```rust
let reader = ImageReader::new(Cursor::new(bytes)).with_guessed_format()?;

let format = reader.format();
let loaded_img = reader.decode()?;
```

**Comment by MichalMoravik** [comment]
Hey @HeroicKatora, thanks a lot for the reply, it worked.
