### ISSUE TITLE
Link to Frame::from_rgba_speed for GifEncoder::new_with_speed doc broken

### ISSUE THREAD

**Issue by stevenhuyn** [image-rs/image#1724]
The reference to `Frame::from_rgb_speed` in [docs](https://docs.rs/image/latest/image/codecs/gif/struct.GifEncoder.html) lead to nowhere

![image](https://user-images.githubusercontent.com/18359644/172717067-4f012206-54fa-4825-8ad1-4b8c6ef3e099.png)

src\codecs\gif.rs
```rust
    /// Create a new GIF encoder, and has the speed parameter `speed`. See
    /// [`Frame::from_rgba_speed`](/gif/struct.Frame.html#method.from_rgb_speed)
    /// for more information.
    pub fn new_with_speed(w: W, speed: i32) -> GifEncoder<W> {
        assert!(
            speed >= 1 && speed <= 30,
            "speed needs to be in the range [1, 30]"
        );
        GifEncoder {
            w: Some(w),
            gif_encoder: None,
            speed,
            repeat: None,
        }
    }
```

The `from_rgb_speed` method doesn't exist in this codebase but it does in [image-gif
](https://github.com/image-rs/image-gif)'s source code.

**Comment by HeroicKatora** [comment]
We could just inline the relevant documentation. Would you be interested in opening a PR for this?

**Comment by stevenhuyn** [comment]
It would work but we'd assume we are always using latest image-gif?

**Comment by HeroicKatora** [comment]
It can be a little more generic than the `image-rs/gif` one, sure. Generally, all decoders will have to perform color sampling as `gif` only supports palettes of 256 colors per frame. This is the reason the method is exposed here in the first place as it's surely not a property specific to the `image-rs/gif` implementation.
