### ISSUE TITLE
PNG conversion to rgba actually spits out bgra 

### ISSUE THREAD

**Issue by MrGibus** [image-rs/image#1726]
This happens in image = "0.24.2"

## Expected

Orange rustacean looks orange.

## Actual behaviour

Rustacean is blue.

## Reproduction steps

```rust
let png = include_bytes!("rust.png").as_ref();
let img = image::load_from_memory(png)?;
let rgba: Vec<u8> = img.to_rgba8().into_vec(); // The bytes here represent bgra not rgba

// Some function which displays image.
```

**Comment by HeroicKatora** [comment]
The reproduction isn't extensive enough for me to see the issue. Could you add the image and detail _how_ you're displaying it?`This could just be a terminology issue. We're referring to channels in memory order while SDL2, for example, refers to channels in order of `u32::from_le_bytes`.

**Comment by MrGibus** [comment]
Apologies. I haven't solved this issue but I made a little red dot png and just did a println on the values which clearly showed rgba. So the issue must lie elsewhere.

**Comment by cdecompilador** [comment]
I think this issue should be reopenned, now `wgpu` has the format `Bgra8UnormSrgb` which some crates like `egui` force you to use (I don't know why), to it would be great to have a filter that does this, or more image formats including `Bgr` and `Bgra`

**Comment by MrGibus** [comment]
@cdecompilador I think that would be a separate issue. The issue here was that sometimes I am a bit of an idiot :)

**Comment by HeroicKatora** [comment]
@MrGibus You're not an idiot, just sloppy and working with imperfect documentation :slightly_smiling_face: 

But agreed on the separate issue. It would be good to track that this conversion are part of the considerations for an improved image buffer.
