### ISSUE TITLE
Export Tiff file with LZW compression

### ISSUE THREAD

**Issue by gospodnetic** [image-rs/image#1730]
How can one export an image to tiff format with compression?

I've noticed that `image-tiff` allows lzw compression, however, I can't seem to understand how to get it working together with `image`?

In general, I need to load a tiff, do some image processing on it (tiling, resizing...) and then save it as a big tiff with lzw compression.

I haven't found any examples and am fairly new to rust so it is not straightforward for me to read it out of the library and would appreciate a help.

The code below saves only uncompressed image.
```
use image::{GenericImageView, ImageFormat};
use std::path::Path;
use std::fs::File;

fn main() {
    let img = image::open("image.tif").unwrap();

    // Do some image processing

    let output_path = &mut File::create(&Path::new(&format!("{}.tif", "processed"))).unwrap();

    img.write_to(output_path, ImageFormat::Tiff).unwrap();
}
```

**Comment by HeroicKatora** [comment]
You certainly didn't miss anything. No bindings for tiff-compression options have been added in `image` as of yet. The best way to get it working together is deferring directly to `tiff` as of now.

**Comment by gospodnetic** [comment]
Ah, I see. Thank you for letting me know :)
Now I've managed to do it for both `LZW` and `Deflate`

Would this be ok, or is there something I could optimize?

```
use image::{GenericImageView};
use std::path::Path;
use std::fs::File;
use tiff::encoder::{TiffEncoder, colortype};
use tiff::encoder::compression;

fn main() {
    let img = image::open("bess-axa.tif").unwrap();
    println!("dimensions {:?}", img.dimensions());
    println!("{:?}", img.color());

    let dims = img.dimensions();

    let output_filename = String::from("test");
    let output = &mut File::create(&Path::new(&format!("{}.tif", output_filename))).unwrap();

    let mut bigtiff = TiffEncoder::new_big(output).unwrap();
    // bigtiff.write_image_with_compression::<colortype::RGB8, compression::Lzw>(dims.0, dims.1, compression::Lzw, &img.as_bytes()).unwrap();
    bigtiff.write_image_with_compression::<colortype::RGB8, compression::Deflate>(dims.0, dims.1, compression::Deflate::default(), &img.as_bytes()).unwrap();
}
```
