### ISSUE TITLE
How to pass `DynamicImage` as an argument?

### ISSUE THREAD

**Issue by gospodnetic** [image-rs/image#1731]
After opening an image with `image::open()` the image is of type `DynamicImage`.

However, if I pass it as `img: &[image::DynamicImage]`,  methods such as `dimensions()` or `as_bytes()` are not found.

I've tried looking at the `imageproc` functions, but didn't find something I could use as an example.

**Comment by fintelia** [comment]
You probably just want `img: &DynamicImage`.

**Comment by gospodnetic** [comment]
Hehe, this feels silly. I've tried so many different types and combinations that I must have missed this one by accident. :) Thank you!
