### ISSUE TITLE
Is the documentation outdated for the High Level API section on doc.rs?

### ISSUE THREAD

**Issue by miketwenty1** [image-rs/image#1732]
How does one use the High level API https://docs.rs/image/latest/image/#high-level-api without these errors? Is the documentation lacking or am I just misunderstanding?

Overall, I'm trying to achieve reading an image in and then eventually removing the extra bytes added via steganography, and recreating the image with just the necessary visual bytes. I want to "sanitize" user input.

![Screen Shot 2022-06-19 at 10 20 49 PM](https://user-images.githubusercontent.com/7761473/174514033-cf5c0fa5-fb6b-4dcd-9085-dd459341aab7.png)
![Screen Shot 2022-06-19 at 10 20 43 PM](https://user-images.githubusercontent.com/7761473/174514037-71142626-a1a4-4b25-8fb1-80806d14415f.png)

**Comment by miketwenty1** [comment]
Hmm.. seems I should be able to use the `?` after `("myimage.png")` as this seems to return a result. 
I'm not sure why rust is upset.

I'm able to see the rust analyzer show it is indeed a Result, and able to match on it as a test. 
When I add the question mark it says it's not a Result.

![Screen Shot 2022-06-19 at 11 14 23 PM](https://user-images.githubusercontent.com/7761473/174519117-e470172a-e7a8-4a33-b98e-62794a6dc192.png)
![Screen Shot 2022-06-19 at 11 14 38 PM](https://user-images.githubusercontent.com/7761473/174519133-816848d6-ace7-4b8c-945b-4029aac72695.png)

**Comment by kaj** [comment]
It seems you are trying to use the `?` operator in a `main` function that does not return an error.  The `?` operator returns early on error, so the function where you use it needs to be able to return an error.

Try to change the line declaring the function to something like this:

```rust
fn main() -> Result<(), std::error::Error> {
    // ... keep the implementation
    Ok(()) // add this line at the end to signal success
}
```

When the `main` of a rust program returns an error, it prints a debug representation of the error and then exits with a non-zero exit code, telling the user and operating system that something went wrong.  Otherwist, it continues operation normally until it reaches the final `Ok(())` value, and terminates with a zero exit status, signalling success.

**Comment by miketwenty1** [comment]
@kaj using this for the error type will result in an rust error that will have a quick fix suggestion of:
```
add `dyn` keyword before this trait: `dyn `
```

Aftering adding this `dyn std::error::Error` I get another error that says:
```
the trait `Sized` is not implemented for `(dyn std::error::Error + 'static)`rustc[E0277](https://doc.rust-lang.org/error-index.html#E0277)
result.rs(504, 20): required by a bound in `Result`
```

I found a solution that worked for me where I needed to import `ImageError` and use that as my error type. I wonder if I'm doing something wrong to not be able to use `std::error::Error`.

I'll leave this open in case you want to answer or think the docs need to be updated with some more "complete'ish examples" to help noobs.

Otherwise, feel free to close.

**Comment by fintelia** [comment]
If you click, the view source link on the documentation page, you can actually see the full code for that example (lines starting with `#` are hidden from the docs.rs output):
https://github.com/image-rs/image/blob/144ea599fcda523956604b3733751beee6b8d5cb/src/lib.rs#L19-L27
https://github.com/image-rs/image/blob/144ea599fcda523956604b3733751beee6b8d5cb/src/lib.rs#L33-L46
If you want to read more about error handling in general, you might want to read through the relevant section of the rust book: https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#where-the--operator-can-be-used. (TLDR: `Result<(), Box<dyn std::error::Error>>` is what you need to fixed the issue with Error not being Sized).

**Comment by kaj** [comment]
Ah, sorry.  I should have said `Box<dyn Error>`, like this:

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
```

**Comment by miketwenty1** [comment]
I'm going to close this. My main issue was my lack of rust understanding. 
Appreciate the help!
