### ISSUE TITLE
Openning a big tiff fails with `LimitError`

### ISSUE THREAD

**Issue by gospodnetic** [image-rs/image#1734]
Using `image::open()` for openning a TIFF of size 7GB fails with `LimitError`
```
Limits(LimitError { kind: InsufficientMemory }) 
```

I thought it might have been a problem that it is not yet implemented in `image-rs` to support big files so I've tried using `image-tiff` decoder, following a [decoding test](https://github.com/image-rs/image-tiff/blob/a874b9c3a565c44711f87f6ede093ddb30f90980/tests/decode_bigtiff_images.rs).
```
let img_file = File::open("very_big.tif").expect("Unable to open file");
let mut decoder = Decoder::new(img_file).expect("Cannot create decoder");
let img = decoder.read_image().unwrap();
```
This too fails with the following error when trying to call `read_image()`
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LimitsExceeded'
```

What is the right way to go about this?

**Comment by silentbat** [comment]
just to be sure - do the 7GB fit into your memory?

**Comment by gospodnetic** [comment]
Yes, 16GB of RAM and 18 swap...should be enough
![image](https://user-images.githubusercontent.com/15703361/174665121-34f50555-0335-4750-a237-1fd5a4c8191c.png)

**Comment by HeroicKatora** [comment]
The `tiff` library [uses some default limits](https://docs.rs/tiff/latest/src/tiff/decoder/mod.rs.html#286-291) to avoid accidental DOSing of code paths going through the simple usage. You'll want to change them and try again by going through [`Decoder::set_limits`](https://docs.rs/tiff/latest/src/tiff/decoder/mod.rs.html#532-535) or by [`image::io::Reader::limits`](https://docs.rs/image/latest/image/io/struct.Reader.html#method.limits) respectively.

**Comment by m0rg-dev** [comment]
I'm also running into this issue - it looks like `image::io::Reader::limits` doesn't actually pass the limits on to `tiff` (which I assume is a bug), and as far as I can tell there's not an easy way to use `tiff`'s `Decoder::set_limits` here without reimplementing a bunch of `image` format-handling stuff.

**Comment by fintelia** [comment]
The code is present on the master branch, but it seems we haven't done a release since it was added...
https://github.com/image-rs/image/blob/04052e64c9a94606efc8bd3d87d5f3e0f566774e/src/codecs/tiff.rs#L178-L196
