### ISSUE TITLE
OOM in JPEG decoding (found by fuzzer)

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#1754]
This happens in image from git on commit 04052e64c9a94606efc8bd3d87d5f3e0f566774e

## Expected

The default RAM usage (soft) limit for decoding is documented to be 512Mb. I would expect it to be roughly respected.

## Actual behaviour

Decoding the attached file exceeds the 2Gb memory limit of the fuzzer: [oom-9cae66e6f4bd2dab39eacfb5b3464ce28d1a7efa.jpeg](https://user-images.githubusercontent.com/291257/177612075-5f0c26f1-c88f-4804-9ae9-855d661950a5.jpeg)

IIRC the underlying `jpeg-decoder` crate has no support for memory limits as yet, so this is not particularly surprising.

It also takes 34 seconds to decode.

## Reproduction steps

```
cargo fuzz run --release --sanitizer=none fuzzer_script_jpeg path/to/file
```

**Comment by fintelia** [comment]
Closing since we've switched JPEG decoding crates
