### ISSUE TITLE
Error loading PNG: ''Format error decoding Png: Invalid PNG signature.'

### ISSUE THREAD

**Issue by AndroGR** [image-rs/image#1755]
## The Bug
Simply loading any PNG image fails, with the error on the title, despite the image being readable by all other software.
## Expected

Returning the actual image without any errors

## Actual behaviour

The application panics, because of an invalid value returned because of the error.

## Reproduction steps

This is my code, where the crash occurs: 
```rust

struct x {
    /* ... */
}

impl x {
    pub fn load(&self, path: &str) {  
                let image_final;
                let image = image::load(Cursor::new(path),
                        image::ImageFormat::Png);
                match image {
                        Err(e) => {
                                eprintln!("Could not load image: {} - {}", e, errno::errno());
                                panic!("ImageCreator::load ({})", path);
                        },
                        _ => {
                                image_final = image.unwrap().to_rgba8();
                        }
                }
                let image_dimensions = image_f.dimensions();
                /* ... */
        }
}
```

**Comment by HeroicKatora** [comment]
```
image::load(Cursor::new(path)
```

This will interpret the *path*, the file name, as contents and try to load it. You'll want to pass the opened file instead:

```
let reader = BufReader::new(File::open(path)?);
```

**Comment by AndroGR** [comment]
Oh yeah, sorry, I am just getting started out with Rust and I didn't know what a Cursor is.
