### ISSUE TITLE
Docs of `as_rgb32f` tells that it is 16bit

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [image-rs/image#1764]
## Expected

>Return a reference to an 32bit RGB image

## Actual behaviour

>Return a reference to an 16bit RGB image

## Reproduction steps

https://docs.rs/image/0.24.3/image/enum.DynamicImage.html#method.as_rgb32f

**Comment by fintelia** [comment]
That's just an issue with the documentation. Please feel free to open a PR to correct it
