### ISSUE TITLE
Feature Request: Colour space information.

### ISSUE THREAD

**Issue by AstroFloof** [image-rs/image#1766]
I would like to be able *to tell what colour space a given image is saved in*

My specific use case for this functionality is *in yet another Quite OK Image Format converter. The format requires a detail of whether an image is sRGB or linear RGB and it would be useful to be able to get that information and pass it on.*

This is more generally applicable to *any time anyone needs to tell what colour space an image is using*

## Draft

This sort of information is saved in PNG. I don't know about other formats, but there could be a default for those that don't save that info. I'm not completely familiar with how images work, as I'm just getting in to it. 
Ideally, this information would be a getter method of DynamicImage, which would return an enum ColorSpace for using `match` on later.

**Comment by fintelia** [comment]
This is a _much_ deeper rabbit hole than one might at first expect. The biggest problem isn't so much images that don't specify color space information, but rather rather images that specify a whole lot more about color spaces than just linear vs. sRGB. The various items linked items in https://github.com/image-rs/image/issues/786 might give you more of an idea

**Comment by AstroFloof** [comment]
Ah, I see. I did try to search issues but apparently not thoroughly enough. Glad to see it's potentially coming soon!
