### ISSUE TITLE
How to compile without wasm-bindgen ?

### ISSUE THREAD

**Issue by buxx** [image-rs/image#1769]
Hello,

I use the `image` crate to make some basics image manipulations. But, when I compile [my program](https://github.com/buxx/rollgui2/) for WASM version, `image` crate seems to require [wasm-bindgem](https://crates.io/crates/wasm-bindgen) and my [macroquad](https://crates.io/crates/macroquad) game based lib is not compatible with `wasm-bindgem` (related to [this issue](https://github.com/not-fl3/macroquad/issues/466)).

This `wasm-bindgem` seems required since 0.21 `image` version, according to [changelog](https://github.com/image-rs/image/blob/0dfc52dd7629e00262710a49ffbc85ac7d28b38a/CHANGES.md#version-021).

To be able to use `image` in my program, I use the `0.20.1` version. **Is that possible to disable `wasm-bindgem` `image` requirement when compile my program ?

Thanks in advance :)

**Comment by HeroicKatora** [comment]
We don't directly depend on bindgen, please find the dependency that does and open an issue to them. You can disable most of the dependencies by specifying `default-features = false` in `Cargo.toml` and only include those codecs you actually need. Like recommended, `cargo tree --target wasm32-unknown-unknown` will help pinpoint which dependency may be activated without such a dependency.

**Comment by buxx** [comment]
Using only wanted codec seems exclude bindgen :)

    image = { version = "0.24.3", default-features = false, features = ["png"] }

Thanks for your time !
