### ISSUE TITLE
Setting multiple pixels at once

### ISSUE THREAD

**Issue by mapa17** [image-rs/image#1772]
Hi, I am very new to rust and to image-rs in particular but I am confused/surprised to not have found any option to set multiple pixels at once. Am I missing something? I thought either one could do a kind of slicing on an ImageBuffer or set a SubImage to a specific value.

So something like
```
let mut img: ImageReader::open("test.png")?.decode()?.to_rgba();
img[0..100, 0..100] = Rgba([255, 255, 255, 255]);
```
or
```
let mut img: ImageReader::open("test.png")?.decode()?.to_rgba();
img.data.sub_image(0, 0, 100, 100).fill(Rgba([255, 255, 255, 255]));
```

Is there something similar or this a very naive question?

thx,
Manuel

**Comment by fintelia** [comment]
You can just use a `for` loop. The rust compiler is smart enough to turn that into just as optimized code as we'd be able to implement internally.

**Comment by HeroicKatora** [comment]
Doing 2d-slices with the former above syntax is not (currently) possible in Rust and I'm tired of explaining why (there's at least 3 duplicate explanations in these issues already). It doesn't feel like the appropriate place for open ended questions with no concrete resolution or sketch anyways.

There's the rough idea of adding a (defaulted) extension method on `GenericImage` which internally does the mentioned loop. That seems like a decently simple first contribution even?

```
trait GenericImage {
    fn fiil(&mut self, val: Rgba) {
        // ?? to be filled
    }
}
```

Usage would then be very similar to your second sketch :)

**Comment by mapa17** [comment]
Thank you!
