### ISSUE TITLE
A deprecation message of Pixel::from_channels suggests a non-existent method

### ISSUE THREAD

**Issue by ytoku** [image-rs/image#1782]
A deprecation message of Pixel::from_channels suggests to use `Rgba::new`, but there's no such method.

## Expected

Suggest a correct code such as `Rgba([r,g,b,a])`

## Actual behaviour

```
warning: use of deprecated associated function `image::Pixel::from_channels`: Use the constructor of the pixel, for example `Rgba::new(r,g,b,a)` or `Pixel::from_slice`
```

## Reproduction steps

```
Rgb::from_channels(r, g, b, 0)
```

**Comment by HeroicKatora** [comment]
Nicely spotted and diagnosted. Sounds simple enough to fix, I like the suggestion as well. Would you consider making a small PR for that?

**Comment by ytoku** [comment]
Thanks. I have opened a PR.
