### ISSUE TITLE
Loading rgb8 data from_raw

### ISSUE THREAD

**Issue by quorth0n** [image-rs/image#1785]
This currently does not seem to be possible with this crate as the function simply returns None due to failure on the vec bounds check.
```rust
            let img = RgbImage::from_vec(
                rgb_frame.width(),
                rgb_frame.height(),
                rgb_frame.data(0).to_vec(),
            ) // None
```

In the turbojpeg library I am able to specify a pitch argument when I load images like this:

```rust
            let img = Image {
                pixels: rgb_frame.data(0),
                width: rgb_frame.width() as usize,
                height: rgb_frame.height() as usize,
                pitch: (rgb_frame.width() * 8 / 8) as usize, // rgb8
                format: PixelFormat::RGB,
            };
```

Is it possible to do something similar here? My images need to onnx compatible which requires this color profile.

**Comment by fintelia** [comment]
No, the internal representation of RgbImage requires that the rows are tightly packed. However, should be able to do that yourself with something along the lines of:
```rust
let mut packed = vec![0; width * height * 3];
for y in 0..height {
    packed[y * width*3..][..width*3].copy_from_slice(&input[y * row_pitch][..width*3]);
}

let img = RgbImage::from_vec(width, height, packed);
```
