### ISSUE TITLE
Saving webcam frame from nokhwa crate fails

### ISSUE THREAD

**Issue by paulmelis** [image-rs/image#1801]
While working with the [nokhwa](https://github.com/l1npengtul/nokhwa) webcam capture crate I stumbled on a situation where saving the current frame with `frame.save("file.jpg")` fails with a `Unsupported(UnsupportedError { format: Exact(Jpeg), kind: Format(Exact(Jpeg)) }` panic. I'm not sure why, as saving the exact same frame with `image::save_buffer()` directly works. Initially I reported this in the nokhwa repo, but got a [reply](https://github.com/l1npengtul/nokhwa/issues/61) this was an image crate issue, hence the issue created here.

Secondly, while trying to further debug the issue I can't seem to get `frame.save_with_format()` to work, as it apparently needs a value of `ImageFormat` that's not exposed publicly? At least, that what's the error seems to imply to me.

This is with image 0.24.4, nokhwa 0.9.4 (input-v4l) and rust 1.64.0

## Expected

`frame.save("file.jpg")` saving the buffer without error

## Actual behaviour

```
melis@juggle 09:39:~/examples/rust/nokhwa-save-error$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/nokhwa-save-error`
image::buffer_::ImageBuffer<image::color::Rgb<u8>, alloc::vec::Vec<u8>>
(1280, 720)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported(UnsupportedError { format: Exact(Jpeg), kind: Format(Exact(Jpeg)) })', src/main.rs:28:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Reproduction steps

Cargo.toml
```
[package]
name = "nokhwa-save-error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
nokhwa = {version = "0.9.4", features = ["input-v4l"]}
```

src/main.rs
```
use nokhwa::*;

fn print_type_of<T>(_: &T) {
    println!("{}", std::any::type_name::<T>())
}

fn main() {
    let mut camera = Camera::new(
        0, 
        Some(CameraFormat::new_from(1280, 720, FrameFormat::MJPEG, 30)),
    )
    .unwrap();

    // open stream
    camera.open_stream().unwrap();

    let frame = camera.frame()
        .expect("could not get latest frame");

    print_type_of(&frame);
    println!("{:?}", frame.dimensions());

    // Works    
    image::save_buffer("frame1.jpg", &frame, frame.width(), frame.height(), 
        image::ColorType::Rgb8).expect("save_buffer");

    // Fails at runtime
    frame.save("frame2.jpg").unwrap();

    // format value is of invalid type? 
    // expected enum `image::image::ImageFormat`, found enum `ImageFormat`
    //frame.save_with_format("frame3.jpg", image::ImageFormat::Jpeg).unwrap();
}
```

**Comment by fintelia** [comment]
Saving a JPEG image requires that the "jpeg" feature is enabled. This is one of the default features, so normally you wouldn't have to do anything to enable it, but nokhwa [specifically imports image will all default features disabled](https://github.com/l1npengtul/nokhwa/blob/17a87eafee2a77809dd3109dde8b920effbf8ef1/Cargo.toml#L51)...

Normally, importing a crate directly in your Cargo.toml would override that and give you all default features. Unfortunately, the crates.io version of nokhwa still uses the outdated 0.23.x image branch rather than the current 0.24.x.

If you switch your Cargo.toml to say `image = 0.23` or switch to the GitHub version of nokhwa I think your code should work

**Comment by paulmelis** [comment]
Thanks for the insight! That takes away some of my confusion :)

I guess we can close this one...
