### ISSUE TITLE
Add Export feature on dynamic_map macro

### ISSUE THREAD

**Issue by c4r3** [image-rs/image#1809]
I would like to be able to hook a custom function from "imageops" crate.
I would like to recreate a function similar to the following example of 'blur':

`  pub fn blur(&self, sigma: f32) -> DynamicImage {
        dynamic_map!(*self, ref p => imageops::blur(p, sigma))
    }`

As you can see with the enabling of the export of the macro 'dynamic_map' i can add new functionalities from the 'imageops' crate (i.e.: overlay()).

**Comment by HeroicKatora** [comment]
There's a small detail easily missed: `DynamicImage` is `non_exhaustive`. The macro does not create any fallback match arm. It would thus not work in its current state outside the crate where such a match arm is required by the compiler.

**Comment by c4r3** [comment]
Right. You are right; but if the macro would be exhaustive it could be easily "plugged" any apis of the imageops crate.
What do you think?

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by c4r3** [comment]
Ok I got it, you are right. The capability of "plug" different custom functions thank to the abstraction of the DynamicImage would be a comfortable feature, but never mind.

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HeroicKatora** [comment]
If anyone comes up with a good SemVer story for such a macro, we can definitely do it though! The need for abstraction and comfort are definitely there.
