### ISSUE TITLE
How to send Vec<u8> to flutter?

### ISSUE THREAD

**Issue by guchengxi1994** [image-rs/image#1811]
I was using [flutter_rust_bridge](https://github.com/fzyzcjy/flutter_rust_bridge) to build some tools in rust for flutter.

I noticed that `ImageBuffer` can be converted to Vec<u8> by using `as_raw()` or `to_vec()`, but the vector cannot be rendered by flutter and I think it is not right in this way.

 
![image](https://user-images.githubusercontent.com/33513462/197493174-69fec8a1-b23f-418b-aac8-44e616e73f1a.png)

I saved base64 code of the vector, and it is different from the result should be. My question is, how to send a vector (Uint8list in dart) to render image directly rather than save the image first.

**Comment by fintelia** [comment]
When you call `as_raw` or `to _vec` you get the raw pixels of the image, but when you call `save` you get the contents of the image _encoded_ as PNG or JPEG or whatever format you specify. From your description you probably want something like:
```rust
let mut bytes: Vec<u8> = Vec::new();
img2.write_to(&mut Cursor::new(&mut bytes), image::ImageOutputFormat::Png)?;
```

**Comment by guchengxi1994** [comment]
@fintelia thanks for your help, images can be rendered correctly now.
![image](https://user-images.githubusercontent.com/33513462/197675021-03080531-d258-4a36-98b2-212f5c4bfa78.png)
