### ISSUE TITLE
Unclear return values for GenericImageView::bounds

### ISSUE THREAD

**Issue by bjorn-ove** [image-rs/image#1829]
This happens in at least 0.24.5

## Expected

Either `(x, y, width, height)` or `(x, width, y, height)` should be returned by the `GenericImageView::bounds` method

## Actual behaviour

* https://github.com/image-rs/image/blob/f64b52b514a857d053a6e5a3cf2ed8f79fc3e90f/src/flat.rs#L1375-L1378
* https://github.com/image-rs/image/blob/f64b52b514a857d053a6e5a3cf2ed8f79fc3e90f/src/flat.rs#L1418-L1421
* https://github.com/image-rs/image/blob/f64b52b514a857d053a6e5a3cf2ed8f79fc3e90f/src/buffer.rs#L1150-L1152

## Reproduction steps

Look at the source code

I'm happy to fix this in a PR, but are not sure if I'm missing something obvious as the code is pretty old.

**Comment by brykgroup-andrews** [comment]
Hey! Re the MR that attempts to resolve this at #2036, Is there any plan to re-expose xoffset/yoffset via a different method? I can't find anything that exposes these values anymore given the deprecation of ::bounds()
