### ISSUE TITLE
Transparent background 'Png' to white background 'Jpg'

### ISSUE THREAD

**Issue by inzanez** [image-rs/image#1835]
Hi

Is there any way to ensure a white background for an image when converting PNG with a transparent background to JPG? I currently end up with a black background. I am afraid I do not have enough knowledge to know what to transform when,...:-)

**Comment by fintelia** [comment]
After loading the PNG, you can just loop over the pixels of the image and set any with A=0 to have RGB=255.

**Comment by farsightltd** [comment]
@fintelia Oh, yeah...that works, very nice!  Thanks

**Comment by inzanez** [comment]
@fintelia Oh, very nice, that worked out perfectly! Thanks.
