### ISSUE TITLE
Some modern ico-formats will be rejected

### ISSUE THREAD

**Issue by cyberpunkbln** [image-rs/image#1836]
Hello,

when i try to load:
`let img = image::open(&Path::new(&iconPath)).unwrap();`
and the ico is an 512x512 or with an png in the stack
it comes:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Decoding(DecodingError { format: Exact(Ico), underlying: Some(ImageEntryDimensionMismatch { format: Png, entry: (256, 256), image: (512, 512) }) })', src\EXE.rs:40:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

the PNG entry and the image entry are correct modern ico-spezifications

thx

**Comment by fintelia** [comment]
I believe it should just be a matter of correcting the check here: https://github.com/image-rs/image/blob/b02bb7426cc716d9353fac19ac1d744c8b298f41/src/codecs/ico/decoder.rs#L234

Do you want to open a PR?

**Comment by cyberpunkbln** [comment]
@fintelia thx for your answer.
Is this the line? Image-rs says an icon-entry with 256x256 are okay and 512x512 are not okay. And an entry with an png encode icon are not okay,too. I think in this file the dimension must be set higher:

https://github.com/image-rs/image/blob/ac7656945391411b726ea2638d33246e57b7b5c8/src/codecs/ico/decoder.rs

?

**Comment by cyberpunkbln** [comment]
hmmm it is a special problem with 512x512, its a modern specification, but i think image-rs should implement the higher specifications, that code can correct 512er Icons to 256er icons. They i found that should minimally include in the decoder-lib.

**Comment by fintelia** [comment]
Do you know if the higher specifications are written up anywhere? That would help for knowing exactly what changed.

**Comment by cyberpunkbln** [comment]
@fintelia i think is only a hack. The metadata is png256 but the raw binary data is png512. My icons where i test unpack i from an exe. Gimp import this icons well but inform at the save output that some older prgs have problems.

Is it possible to tell image-rs that he take the first normal 256erpng?
