### ISSUE TITLE
Decoding Windows clipboard bitmaps

### ISSUE THREAD

**Issue by lunixbochs** [image-rs/image#1880]
I'm writing a clipboard crate, I would like to be able to encode/decode images directly to/from the Windows CF_DIB format, which is exactly the same as a bitmap file, but without the BITMAPFILEHEADER. It seems like image-rs could support this format with minimal changes. I would just add the BITMAPFILEHEADER myself before passing the data to image-rs, but the `bfOffBits` field requires parsing the other headers to heuristically calculate, and I'd rather avoid that.

It looks like for decoding, we might just need to have a method that sets `no_file_header = true` with no other changes.

**Comment by lunixbochs** [comment]
Possible implementation here: https://github.com/talonvoice/image-rs/commit/145998bdf9bcc1f0c5c72b217aca1d6a5dd74858

**Comment by fintelia** [comment]
Could you open a pull request? It would be good to include a couple test cases so we don't accidentally break this in the future.

**Comment by lunixbochs** [comment]
Yeah, I'll do a PR soon with a test. We can test this by encoding a BMP, discarding the file header, and ensuring it decodes afterwards. I confirmed my patch does work great for decoding the CF_DIB clipboard type on Windows.
