### ISSUE TITLE
Many decoders don't check dimensions limits, but advertise support

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#1889]
As of `image` 0.24.5, all decoders advertise support for setting limits on image dimensions through the default implementation of `Limits::check_support`:

https://github.com/image-rs/image/blob/fe069785ae245a2c510fd724ef96da283b05a236/src/io/mod.rs#L84-L87

However, may of them don't actually implement that; e.g. the [PNM decoder](https://github.com/image-rs/image/blob/master/src/codecs/pnm/decoder.rs) doesn't handle limits at all, and the [TGA decoder](https://github.com/image-rs/image/blob/master/src/codecs/tga/decoder.rs) only handles one special case but otherwise doesn't check dimensions.

Checking dimensions against the limit can be implemented simply by querying `.dimensions()` on the decoder and doesn't require any elaborate support from the underlying decoder. There's a helpful function [`Limits::check_dimensions`](https://docs.rs/image/0.24.5/image/io/struct.Limits.html#method.check_dimensions) for this; it should be actually called by every decoder in their `into_reader` and `read_image` implementations.

**Comment by fintelia** [comment]
The default implementation of `set_limits` checks the dimensions:
https://github.com/image-rs/image/blob/fe069785ae245a2c510fd724ef96da283b05a236/src/image.rs#L768-L769

**Comment by Shnatsel** [comment]
Ah, I see. This issue is invalid then.

**Comment by fintelia** [comment]
It might however make sense to better document that not calling set_limits is implicitly using `Limits::no_limits` rather than `Limits::default` as you might expect

**Comment by Shnatsel** [comment]
Good point, I've created an issue to track that. Thanks!
