### ISSUE TITLE
Add GenericDecoder implementing ImageDecoder

### ISSUE THREAD

**Issue by sophie-h** [image-rs/image#1895]
I would like to be able to use the features of `ImageDecoder` without having to care about the file format.

My specific use case for this functionality is writing an image viewer that needs some features of `ImageDecoder` that `io::Reader` does not seem to provide or consume the reader for it (`into_dimensions()`).

This is more generally applicable to implementing features like `io::Reader::into_dimensions()` or `io::Reader::decode()` since the case differentiation for all file formats only has to be done in the `GenericDecoder`.

## Draft

```rust
pub enum GenericDecoder {
    Jpeg(codecs::jpeg::JpegDecoder),
    ...
}

impl GenericDecoder {
    pub fn with_format(reader, format) {
        match format {
            Jpeg => Self::Jpeg(codecs::jpeg::JpegDecoder::new(reader),
            ...
        }
    }
    /// Format is guessed from magic byte first and extension as fallback
    pub fn with_guessed_format(path)
}

impl ImageDecoder for GenericDecoder {
    ...
}

impl From<codecs::jpeg::JpegDecoder> for GenericDecoder {
    ...
}
```

**Comment by fintelia** [comment]
I'd be curious what you think of https://github.com/image-rs/image/pull/1869 which (among other changes) proposes adding `Reader::into_decoder` that produces an opaque `impl ImageDecoder` from an `io::Reader`

**Comment by sophie-h** [comment]
That looks great!

I have chosen an enum to keep compatibility with the functions that don't take `self` as a reference. But as you have mentioned in your MR, that keeps a lot of annoying aspects, at least internally.

The only thing I haven't thought through yet is how animation fits into this. Maybe ImageDecoder could get an 

```rust
animated_decoder(&mut self) -> Option<impl <AnimatedDecoder>
```

**Comment by fintelia** [comment]
As of 0.25.0, the `ImageDecoder` trait is now object safe. That means that `Box<ImageDecoder>` can abstract over different decoders and you can use [`Reader::into_decoder`](https://docs.rs/image/latest/image/io/struct.Reader.html#method.into_decoder) to infer the image type and construct the appropriate decoder.
