### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by sophie-h** [image-rs/image#1902]
I think there is no git tag for the latest release. Also, `WebPDecoder::has_animation` seems to be part of the release, so something after the "Release 0.24.6" commit. Therefore, a tag would be helpful xD

**Comment by fintelia** [comment]
Thanks for catching this!   https://github.com/image-rs/image/commit/1028cff98b00c9f20c6ab1e6098bbdf6da70132d is the commit that should be tagged (it is the merge commit associated with the PR for releasing 0.24.6)

**Comment by sophie-h** [comment]
Are you sure about the commit? Because `WebPDecoder::has_animation` is in. I'm not good at git though

![image](https://user-images.githubusercontent.com/3466497/230483215-7db4db36-6b31-4630-be36-0745be08ad90.png)

**Comment by sophie-h** [comment]
Ah, the merge. I said nothing. I'm really bad at git xD

**Comment by HeroicKatora** [comment]
Fixed, thanks for notifying us :+1:
