### ISSUE TITLE
Add option to ignore/replace background color for extended webp

### ISSUE THREAD

**Issue by Nogesma** [image-rs/image#1906]
I would like to be able to disable the background color when decoding extended webp images/animations. 

Some webp animations use a white background by default, and transparent pixels. When the frame does not cover the whole canvas, the white background will appear. 

[Example webp](https://cdn.7tv.app/emote/62a8dfd6aa031674e785e8a1/1x.webp)

The webp specification says that the background color value should be treated as a hint, and does not need to be used, so it would be nice to have the option to make the background transparent, or choose it's color completely.

## Draft
```rust
// WebPDecoder
pub fn set_background_color(&mut self, color: Rgba<u8>) -> ImageResult<()> {
    match &mut self.image {
        WebPImage::Extended(image) => image.set_background_color()?
        _ => Err(...) 
    }
}

// ExtendedImage
pub(crate) fn set_background_color(&mut self, color: Rgba<u8>) -> ImageResult<()> {
    match &mut self.image {
        ExtendedImageData::Animation { anim_info, .. } => {
            anim_info.background_color = color;
            Ok(())
        }
        _ => Err(...),
    }
}


```

**Comment by fintelia** [comment]
Seems reasonable. Want to open a PR?

**Comment by Nogesma** [comment]
Sure
