### ISSUE TITLE
how to get individual red, green, blue pixel values from image?

### ISSUE THREAD

**Issue by dddictionary** [image-rs/image#1915]
How does one ... ?

I am trying to get the individual red, green, and blue pixel values from the image in order to generate an ascii image. I just need to get the individual RGB values and then map them to some range of ascii chars, but I am finding it quite difficult to access said RGB values. I need to eventually grayscale the image, co I decided to just grayscale after opening and then read the pixel values then, but still, the actual act of getting the numbers is baffling me. 

Overall, I'm trying to convert images to ascii which require access to the individual RGB values. While yes, there are libraries that already do this for me, I want to write it myself. (Rust beginner).

**Comment by dddictionary** [comment]
https://pastebin.com/LZzRZTdf

This is my function to actually do the image manipulation.

**Comment by fintelia** [comment]
After calling grayscale there are no longer red / green / blue pixel values, there's only a single "luma" value that ranges from black (0) to white (255 or 65535 depending on the bit-depth).

Specifically, the type of `pixel` within your loop is [`Luma<u16>`](https://docs.rs/image/latest/image/struct.Luma.html) so based on that documentation page, you can get contents by doing `pixel.0[0]`. If you hadn't converted to grayscale, you would be working with an RGB image and your pixel would have type [`Rgb<u16>`](https://docs.rs/image/latest/image/struct.Rgb.html) and you could do:
```rust
for pixel in my_rgb_image.pixels() {
    let red = pixel.0[0];
    let green = pixel.0[1];
    let blue = pixel.0[2];
}

As a side note, most images are 8-bits per channel, so calling `to_rgb8` would work just as well as `to_rgb16`

**Comment by dddictionary** [comment]
yep, this seems to be doing what i want, thank you :)
