### ISSUE TITLE
Add a way to stop running decoding operations

### ISSUE THREAD

**Issue by sophie-h** [image-rs/image#1918]
I would like to be able to stop an ongoing decoding operation.

My specific use case for this functionality is that of an image viewer: The image (loading screen) might no longer be shown because of flipping through images or closing one app window. It would be useful to stop the decoding process in that case.

This is more generally applicable to: Probably the area of UI.

## Draft

I haven't seen any decoder used by image-rs supporting this yet. It sounds like it's technically not too hard if there is a flag that is checked 'once in a while' that can be set from the outside. But maybe I'm wrong.

**Comment by fintelia** [comment]
I'd probably suggest seeing how far you can get with the existing incremental decoding functionality we have. Either `ImageDecoder::into_reader` or `ImageDecoderRect::read_rect`. Basically move the _early_exit_ flag into your own code. Only some decoders have meaningful implementations of those, which is mostly a consequence of it being much easier to define an API than to actually implement it for all our decoders...

**Comment by sophie-h** [comment]
I'm already cutting off the data source, but that doesn't seem to help. Do you mean manually reading different parts of the image with read_rect? I don't understand your suggestion yet.

**Comment by fintelia** [comment]
You have to check the code to see whether the format you're using supports streaming decode. For instance, [PNG has a real implementation](https://docs.rs/image/latest/src/image/codecs/png.rs.html#68) while [JPEG just decodes the entire image into a `Vec<u8>`](https://docs.rs/image/latest/src/image/codecs/jpeg/decoder.rs.html#107) when you first call `into_reader`.

**Comment by sophie-h** [comment]
Well, it sounds like zune-jpeg has given up on implementing streaming decoding, which is fine. But for an image viewer, we need a way to stop decoding. Since I'm planning to maybe move decoding to separate processes, we could just kill them if they don't react. But being able to recycle the process might be neater. But before we have to chase every decoder to support shutdown, we might just go with the brute-force method.

I'm undecided :laughing:

**Comment by sophie-h** [comment]
I will handle this by putting decoding in a separate process.
