### ISSUE TITLE
8-bit color TIF fails to decode

### ISSUE THREAD

**Issue by leonz** [image-rs/image#1927]
This happens in image-0.24.6

## Expected

I would expect that this type of TIF (8-bit RGB) is supported given my quick read of tiff.rs.

## Actual behaviour

> The decoder for Tiff does not support the format features RGBPalette with [8] bits per sample is unsupported

## Reproduction steps

Attempting to call

```ImageReader::with_format(input, ImageFormat.TIFF).decode()```

where input is a reader of [this TIF](https://people.math.sc.edu/Burkardt/data/tif/bali.tif).

**Comment by fintelia** [comment]
"RGBPalette with [8] bits per sample" isn't 8-bit RGB. It is a single 8-bit value per pixel that references a list of 256 possible RGB values, and is much rarer than normal 8-bit RGB.

**Comment by leonz** [comment]
Gotcha, I was misinterpreting the file metadata on this image. I assume this is expected to be not supported then.
