### ISSUE TITLE
avif decoder error 

### ISSUE THREAD

**Issue by xxaier** [image-rs/image#1930]
this avif [1.avif.zip](https://github.com/image-rs/image/files/11485598/1.avif.zip)

image::guess_format is UnsupportedError

with file header[3] == 24

[src/lib.rs:46] &format = Avif
[src/lib.rs:53] &bin[..12] = [
    0,
    0,
    0,
    24,
    102,
    116,
    121,
    112,
    97,
    118,
    105,
    102,
]
[src/lib.rs:54] b"\0\0\0\x1cftypavif" = [
    0,
    0,
    0,
    28,
    102,
    116,
    121,
    112,
    97,
    118,
    105,
    102,
]

avif decoder error 
<img width="1898" alt="image" src="https://github.com/image-rs/image/assets/130831741/250e531f-d529-4e01-9a5d-1838e6788265">

[src/lib.rs:55] image::guess_format(bin) = Err(
    Unsupported(
        UnsupportedError {
            format: Unknown,
            kind: Format(
                Unknown,
            ),
        },
    ),
)
  ✘ [fail]: img → jpg Rejected promise returned by test
  ─

  img → jpg

  Rejected promise returned by test. Reason:

  Error {
    code: 'GenericFailure',
    message: 'The image format could not be determined',
  }

**Comment by awxkee** [comment]
@fintelia After #2373 changes everythings works, should I set close flag to this in PR?
