### ISSUE TITLE
Broken on nightly

### ISSUE THREAD

**Issue by johnrichardrinehart** [image-rs/image#1933]
This happens when using (at least)
```bash
$ cargo --version && rustc --version           
cargo 1.71.0-nightly (13413c64f 2023-05-10)
rustc 1.71.0-nightly (ce5919fce 2023-05-15)
```
## Expected

```
 cargo build --release --features avif-decoder
 ```
 doesn't fail

## Actual behaviour

```
 cargo build --release --features avif-decoder
 ```
 failed in accordance with the description in #1932 .

## Reproduction steps

You can just use this repo. I'm on `x86_64-linux`. I can provide `glibc` or other versions, if needed. But, they oughtn't be necessary.

**Comment by fintelia** [comment]
This was fixed thanks to a new release of `mp4parse`

**Comment by johnrichardrinehart** [comment]
Awesome! Thank you!
