### ISSUE TITLE
`.hdr` images decoded as LDR.

### ISSUE THREAD

**Issue by pema99** [image-rs/image#1936]
In my renderer, I was using the following code to load radiance HDR image (`.hdr` extension), but noticed that all values were getting clamped to [0; 1] range:

```rs
pub fn load_dynamic_image(path: &str) -> Option<DynamicImage> {
    image::io::Reader::open(path).ok()?.decode().ok()
}
```

I was able to fix it by adding a special case:
```rs
pub fn load_dynamic_image(path: &str) -> Option<DynamicImage> {
    // Image crate does not by default decode .hdr images as HDR for some reason
    if path.ends_with(".hdr") {
        let hdr_decoder = image::codecs::hdr::HdrDecoder::new(std::io::BufReader::new(
            std::fs::File::open(&path).unwrap(),
        )).ok()?;
        let width = hdr_decoder.metadata().width;
        let height = hdr_decoder.metadata().height;
        let buffer = hdr_decoder.read_image_hdr().ok()?;
        return Some(DynamicImage::ImageRgb32F(image::ImageBuffer::from_vec(
            width,
            height,
            buffer.into_iter().flat_map(|c| vec![c[0], c[1], c[2]]).collect(),
        )?));
    }

    image::io::Reader::open(path).ok()?.decode().ok()
}
```

I noticed it seems to be caused by this line `HdrAdapter::read_image_data`:
```rs
fn read_image_data(&mut self, buf: &mut [u8]) -> ImageResult<()> {
        assert_eq!(u64::try_from(buf.len()), Ok(self.total_bytes()));
        match self.inner.take() {
            Some(decoder) => {
                let img: Vec<Rgb<u8>> = decoder.read_image_ldr()?; // <-- clamp to LDR
                ...
```
I guess the simple fix would just be to swap the call to `read_image_hdr` instead. I'm mainly opening this bug report to verify if this is intentional or indeed a bug. It seems like too obvious of a mistake to me.

## Expected
`.hdr` image is decoded as HDR values, nothing is clamped.

## Actual behaviour
`.hdr` image is decoded such that all pixels above 1.0 are clamped to 1.0.

## Reproduction steps
Run the code from the first snippet, passing a path to an `.hdr` image. Read the pixel values and observe all will be clamped. Attaching the image file I used to test.
https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/2k/clarens_midday_2k.hdr

**Comment by fintelia** [comment]
This is a bug, but one that existing code may be unintentionally relying on. I think the right approach is probably to change when we release `0.25.0`. Honestly, I'm not really sure why we support LDR decoding of `.hdr` images at all. Might make sense just to deprecate it and leave only the HDR decoding logic.

**Comment by pema99** [comment]
I submitted a patch, will 0.25 be the next release?

**Comment by fintelia** [comment]
We'll see. There may be a 0.24.7 release first
