### ISSUE TITLE
Support APNG

### ISSUE THREAD

**Issue by retep998** [image-rs/image#195]
This issue is to track the state of Animated Portable Network Graphics support.
- [ ] Animated Portable Network Graphics support.
- [x] Introduce an API for animated images, see #145

More information:
https://wiki.mozilla.org/APNG_Specification

**Comment by abonander** [comment]
cc PistonDevelopers/image-png#93

I've run into a use-case for this. I'm generating some demo animations for [img_hash](https://github.com/abonander/img_hash) but they're not really suited for GIF encoding for a number of reasons. I'd mostly just like an easy way to losslessly export a sequence of frames to a format that FFMPEG can ingest.

**Comment by HeroicKatora** [comment]
After long waiting we finally have #1250 :tada: It needs a small amount of precursory work in `png` but has already been tested to work with a modified build of `emulsion`.
