### ISSUE TITLE
How to get a "DynamicImage" or "&mut DynamicImage" from a &mut of RgbImage?

### ISSUE THREAD

**Issue by alanthinker** [image-rs/image#1953]
How to get a "DynamicImage" or "&mut DynamicImage"  from a &mut of RgbImage?

 ```
#[no_mangle]
pub unsafe extern "C" fn ffi_test(img_ptr: *mut RgbImage) {
    let mut image = unsafe {
        assert!(!img_ptr.is_null());
        &mut *img_ptr
    };

    //let image_di = DynamicImage::from(*image);  //wrong
    //let image_di_mut = DynamicImage::from(image); //wrong too
    ...
 ```

**Comment by alanthinker** [comment]
Is there any way without copy data to get DynamicImage?

**Comment by fintelia** [comment]
Nope. A DynamicImage contains an owned RgbImage inside but you only have a borrowed one, so you'll need to copy somewhere

**Comment by alanthinker** [comment]
I noticed that some operations only support DynamicImage, while others only support ImageBuffer (such as ImageBuffer<Rgb<u8>, Vec<u8>>). As a result, there is often a need to convert between these two types. If we only have a reference to an ImageBuffer, there is currently no way to convert it to DynamicImage without incurring overhead.

So, why not make all image operations implemented as a Trait for ImageBuffer? This would avoid the need for conversions and make the usage simpler and more convenient.

**Comment by fintelia** [comment]
Most operations should be available on `ImageBuffer` or `GenericImage[View]` as methods in the [`imageops` module](https://docs.rs/image/latest/image/imageops/index.html). Is there something specific you don't see?

**Comment by alanthinker** [comment]
into_luma8 function seems to be called only by DynamicImage.

So I write it by myself.
```
fn to_luma(scaled_image: &ImageBuffer<Rgb<u8>, Vec<u8>>) -> ImageBuffer<image::Luma<u8>, Vec<u8>> {
    let gray_image = ImageBuffer::from_fn(scaled_image.width(), scaled_image.height(), |x, y| {
        let p = *scaled_image.get_pixel(x, y);
        let luma = p.to_luma();
        luma
    });
    gray_image
}
```

**Comment by fintelia** [comment]
Color conversion isn't a super clear part of of the API, but thanks to the [`ConvertBuffer`](https://docs.rs/image/latest/image/buffer/trait.ConvertBuffer.html) trait you should be able to do:
```rust
use image::buffer::ConvertBuffer;

fn to_luma(img: &ImageBuffer<Rgb<u8>, Vec<u8>>) -> ImageBuffer<image::Luma<u8>, Vec<u8>> {
    img.convert()
}
```

**Comment by alanthinker** [comment]
Thank you for your answer. Got it.
