### ISSUE TITLE
WebP Encoder Memory Leak

### ISSUE THREAD

**Issue by mseele** [image-rs/image#1957]
The latest version of https://github.com/jaredforth/webp seems to have an memory leak on decoding: https://github.com/jaredforth/webp/issues/27

Maybe it makes sense to fix the version of https://github.com/NoXF/libwebp-sys to 0.2.2 to avoid the memory leak (https://github.com/NoXF/libwebp-sys/issues/20)!?

**Comment by fintelia** [comment]
I don't think there's anything this crate actually needs to do? When `webp` or `libwebp-sys` figure out what's wrong and publish a new version, we'll pull it in automatically (assuming the changes are semver compatible, and I don't see why they wouldn't be)

**Comment by mseele** [comment]
@fintelia Fair enough. My point was that the memory leak was introduced via a semver-compatible version, which means that all new installs or upgrades of the image crate will get the memory leak, which I thought should be avoided.

**Comment by oldmanfleming** [comment]
@fintelia 

Just following up on this one. It seems there has been a series of patch versions released for the webp crate that indicate various memory leak fixes:

version 0.2.5:
- [Includes animation encoder memory leak fix](https://github.com/jaredforth/webp/pull/29)

version 0.2.4
- [fix WebPPicture memory leak](https://github.com/jaredforth/webp/pull/28)

version 0.2.3:
- [chore: bump libwebp-sys version](https://github.com/jaredforth/webp/pull/25)

I'm wondering if its possible to bump image's webp dependency version to make these fixes available?

**Comment by fintelia** [comment]
You should actually get the patched versions automatically if you run `cargo update`. In a Cargo.toml file, `version = "0.2.2"` actually means the same thing as `version = "^0.2.2"`, i.e. any version "0.2.x" where x>=2.

**Comment by oldmanfleming** [comment]
Ah thanks so much for the quick response! I'm new to the Rust ecosystem and didn't realize thats how the versioning worked. I just wen't into my cargo.toml and indeed confirmed I'm on webp 0.2.4. I ran cargo update and got bumped to 0.2.5. I'll do some testing and see if my observed memory leak issues are resolved with their latest patch.
