### ISSUE TITLE
Some ImageBuffer instances fail to be saved

### ISSUE THREAD

**Issue by JerzySpendel** [image-rs/image#1963]
This happens in image v0.24.6

## Expected

I should be able to save `ImageBuffer<Rgb<f32>, Vec<f32>>` into a .jpg file either directly by calling `.save()` on the buffer object, or by wrapping it in `DynamicImage` and then calling `.save()`

## Actual behaviour

There's no panic or any sign of other error when running the program, but either no file is created or an empty file is created.

What did happen

Not sure, I guess there's a problem with dealing with pixels of type `Rgb<f32>`, because casting ImageRgb32F to ImageRgb8 makes it work again.

## Reproduction steps

```
use rand::{self, Rng};
use image;
use std;

fn main() {
    let mut rng = rand::thread_rng();

    let mut random_floats = Vec::<f32>::with_capacity(3 * 1000000);
    random_floats.resize(3 * 1000000, 0f32);
    rng.fill(random_floats.as_mut_slice());

    let mut noise_image = image::ImageBuffer::<image::Rgb<f32>, Vec<f32>>::from_vec(1000, 1000, random_floats).unwrap();

    // noise_image.save("something.jpg"); # Saving image buffer directly - doesn't work
    let image = image::DynamicImage::ImageRgb32F(noise_image);
    image.save("before.jpg"); // Doesn't work


    image.to_rgb8().save("after.jpg"); // Works!
}

```

`before.jpg` is either not created or is an empty file, `after.jpg` is created correctly

**Comment by fintelia** [comment]
There is a sign of error. The compiler prints a warning that you're ignoring the return value of `save`:
```
warning: unused `Result` that must be used
  --> src/main.rs:16:5
   |
16 |     image.save("before.jpg"); // Doesn't work
   |     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this `Result` may be an `Err` variant, which should be handled
   = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
   |
16 |     let _ = image.save("before.jpg"); // Doesn't work
   |     +++++++

warning: unused `Result` that must be used
  --> src/main.rs:19:5
   |
19 |     image.to_rgb8().save("after.jpg"); // Works!
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this `Result` may be an `Err` variant, which should be handled
help: use `let _ = ...` to ignore the resulting value
   |
19 |     let _ = image.to_rgb8().save("after.jpg"); // Works!
   |     +++++++
```
[(playground link)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fb5efa2e275e600190d4afed64a479fe)

If you handle the error by changing your code to `image.save("before.jpg").expect("failed to save image")` then you can see what the actual problem is:

```
thread 'main' panicked at 'failed to save image: Unsupported(UnsupportedError { format: Exact(Jpeg), kind: Color(Rgb32F) })', src/main.rs:16:30
```

In other words, JPEG files cannot hold Rgb32F pixels so your image couldn't be saved using that format.

**Comment by JerzySpendel** [comment]
Ah ok, I didn't think about that. Ok then, is that expected behaviour that we cannot save Rgb32F pixels? Maybe we could cast `Rgb<f32>` to `Rgb<u8>` by multiplying by 255?

**Comment by fintelia** [comment]
We intentionally don't do that conversion implicitly. However, I believe that's how [`DynamicImage::into_rgb8`](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.into_rgb8) works when called on a Rgb32F image.

**Comment by JerzySpendel** [comment]
Ok, thank you for clarification.
