### ISSUE TITLE
BPG image format

### ISSUE THREAD

**Issue by mattfbacon** [image-rs/image#1964]
https://bellard.org/bpg/

I would like to be able to process BPG images.

My specific use case for this functionality is an image viewer that should support as many formats as possible. BPG is a novel, efficient, and promising format.

This is more generally applicable to applications that want to support as many formats as possible or are interested in the appealing aspects of the BPG format. 

## Draft

I don't believe there is an existing BPG library for Rust. There is a C library, libbpg, for which bindings could be written/generated. A translation to Rust is also possible.

In either case, integrating the format would be mostly glue work rather than new code.

**Comment by fintelia** [comment]
What software currently supports BPG / who is currently using it?

Based on the Wikipedia article, it seems to be a complex, patent encumbered format. And if I'm interpreting correctly, it has been around since 2014 but got abandoned before it even had a 1.0 release

**Comment by mattfbacon** [comment]
Your reasoning makes sense. Is there some document that specifies the criteria for adding a new image format to this lib?

**Comment by fintelia** [comment]
We don't have a specific document listing out exact criteria, but the general factors to consider are things like:
* How widely used is the format? How confident are we that it'll continue being used?
* Are there an existing high quality pure-Rust implementation? 
    * Does it support decoding limits?
    * Has it been fuzzed?
    * Missing features?
* Or is there a contributor interested in writing a pure-Rust implementation?
* (Rare:) is the format important enough to justify shipping bindings to a C implementation behind a non-default feature flag?

A big concern is that once we add support for a format, we have no way of knowing whether anyone is using it and thus, it is very hard to ever remove it in the future. Yet, every new format adds attack surface to the crate and a small amount of ongoing maintenance cost.

**Comment by mattfbacon** [comment]
Got it, thanks.
