### ISSUE TITLE
Expected size is not equal to the real size...

### ISSUE THREAD

**Issue by ghost** [image-rs/image#1968]
I'm trying to do some image compression. But I keep getting the error `wrong data size, expected X got Y` where X is larger than Y but the image size is correct and there is an exact proper number of bytes (I've checked the size on the file system) and for me, on linux, I can open the file perfectly fine. The Image is png and so I'm not really understanding what's the issue and why it's expecting larger amount of bytes than there are..? And I am guessing that this is coming from the `png` crate.
```rs
let mut image = image::io::Reader::new(Cursor::new(image_data));
image.set_format(ImageFormat::Png);
let (width, height) = image.into_dimensions().unwrap();
let mut output = Vec::with_capacity(image_data.len());
let image = image::codecs::png::PngEncoder::new_with_quality(
        &mut output,
        CompressionType::Fast,
        FilterType::Adaptive,
);
image.write_image(image_data, width, height, ColorType::Rgba8)?;
```

Expected behaviour: the image should be properly compressed.

**Comment by fintelia** [comment]
The code you provided never actually decodes the contents of `image_data`. That's a problem because `PngEncoder::write_image` takes raw uncompressed pixels (with the layout specified by the color type argument)
