### ISSUE TITLE
u32 ppm image suuport

### ISSUE THREAD

**Issue by ror6ax** [image-rs/image#1981]
How do I write a u32 image? I noticed that 32 is the only bit variant that does not have unsigned version.  I'm trying to read from .ppm file using tinyppm library and it's pixels are stored as u32's. I have absolutely no idea what I'm doing so please excuse me if this is an obvious question...

**Comment by fintelia** [comment]
The .ppm file format doesn't support 32-bits per channel. It does however support 8-bits per channel and you can pack 3x u8 into a u32, [which is what the tinyppm library does](https://docs.rs/tinyppm/0.2.0/src/tinyppm/ppm_loader.rs.html#78)

So it should be a matter of saving an rgb8 image with this library and loading it with tinyppm
