### ISSUE TITLE
Function to ask for supported image formats/extensions

### ISSUE THREAD

**Issue by emilk** [image-rs/image#1994]
I would like to be able to ask `image` what file extensions it supports _give its current feature flags_.

For instance: `println("{:?}", image::extensions());` could print `["jpg", "jpeg", "png"]` if only the `image` and `jpeg` features of `image` is turned on.

My specific use case for this functionality is adding file extension filters to a file dialog.

**Comment by fintelia** [comment]
I think it makes sense to expose this information. Maybe something like:

```rust
impl ImageFormat {
    pub fn reading_enabled(&self) -> bool;
    pub fn writing_enabled(&self) -> bool; 
}
```
Though we should probably provide a way to iterate over all the formats. I wonder if a method like `fn all() -> impl Iterator<Item=ImageFormat>` would be good?

**Comment by emilk** [comment]
Oh yeah, great catch on the read vs write difference. That API looks solid to me!

**Comment by fintelia** [comment]
Added in #2038
