### ISSUE TITLE
Potential unsound implementation in `from_slice` and `from_slice_mut`

### ISSUE THREAD

**Issue by shinmao** [image-rs/image#1996]
https://github.com/image-rs/image/blob/ec623d2b805a0662b021a752833733b97c353ceb/src/color.rs#L248-L251
Hi, I consider that `from_slice` and `from_slice_mut` might cause to undefined behavior when casting `&[T]` to `RGB<T>` without `#repr(transparent)`. `repr(Rust)` can't guarantee the memory layout is stable, which means compiler can insert padding bytes around `&[T]` in the struct. Same unsoundness could happen in the implementation for `LumaA<T>`, `Rgba<T>`, `Luma<T>`. The best way to guarantee the casting is to add annotation of `#repr(transparent)`.

**Comment by fintelia** [comment]
These structs should be `#[repr(C)]` which I think does provide the guarantees we need?
https://github.com/image-rs/image/blob/ec623d2b805a0662b021a752833733b97c353ceb/src/color.rs#L215-L217

**Comment by shinmao** [comment]
Yes. i think it is a good way to fix the issue. repr(C) can guarantee the layout is stable.

**Comment by fintelia** [comment]
Given that this is already how the code works, no further changes are needed
