### ISSUE TITLE
WebP: `DynamicImage.save` panic when saving to webp path

### ISSUE THREAD

**Issue by LoKy-dev** [image-rs/image#2000]
I'm trying to use this library to convert from the most common image formats to webp, i'm loading an image from [`image::open`](https://docs.rs/image/latest/image/fn.open.html#) and saving it by using [`DynamicImage::save`](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.save).

I used almost the same code provided in the repo example for converting, [here](https://github.com/image-rs/image/blob/master/examples/convert.rs).

## Expected

Create the correct webp file

## Actual behaviour

The save method panics with this message
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported(UnsupportedError { format: Unknown, kind: Format(Name("WebP")) })', src/main.rs:7:35
```

## Reproduction steps

I've set up a little repository [here](https://github.com/LoKy-dev/image-webp-error)
Simply run `cargo run`
rustup 1.26.0 (5af9b9484 2023-04-05)
rustc 1.72.0 (5680fa18f 2023-08-23)

**Comment by LoKy-dev** [comment]
Forgot to mention, targeting 'stable-aarch64-apple-darwin' on an M1 Mac.

**Comment by fintelia** [comment]
You need to enable the `webp-encoder` feature. We very recently [merged a PR](https://github.com/image-rs/image/pull/1978) adding pure-Rust webp encoding and enabling it by default, but that version hasn't been published to crates.io so you'd have to use a git dependency if you wanted to try it out.

**Comment by LoKy-dev** [comment]
Thanks it works, sorry for this dumb issue, i could have found this in the doc 🤦🏻‍♂️
