### ISSUE TITLE
Two arithmetic overflow found in RgbImage

### ISSUE THREAD

**Issue by thdusdl1219** [image-rs/image#2016]
I found two arithmetic overflow cases in the latest version. They look same but exist in different location.

### Case 1

This happens in 

https://github.com/image-rs/image/blob/f1e34f365133a33a27dac5bc59c93d1cfb34a37e/src/buffer.rs#L792

### Case 2

This happens in 

https://github.com/image-rs/image/blob/f1e34f365133a33a27dac5bc59c93d1cfb34a37e/src/buffer.rs#L970

## Expected

Assert or use the checked operation instead.

### Case 1
`thread 'main' panicked at 'attempt to add with overflow', .cargo/registry/src/index.crates.io-6f17d22bba15001f/image-0.24.7/./src/buffer.rs:792:21`

### Case 2
`thread 'main' panicked at 'attempt to add with overflow', .cargo/registry/src/index.crates.io-6f17d22bba15001f/image-0.24.7/./src/buffer.rs:970:25`

### Case 1

```
    let ImageBuffer_self_obj = image::RgbImage::new(u32::MAX - 1, 1);
    let y = u32::MAX;
    let x = u32::MAX - 2;
    ImageBuffer_self_obj.get_pixel_checked(x, y);
```

### Case2

```
    let mut ImageBuffer_self_obj = image::RgbImage::new(u32::MAX - 1, 1);
    let y = u32::MAX;
    let x = u32::MAX - 2;
    ImageBuffer_self_obj.get_pixel_mut_checked(x, y);
```

**Comment by fintelia** [comment]
Could you make a pull request?

**Comment by JulianKnodt** [comment]
@fintelia would it be alright if I fixed these?

**Comment by thdusdl1219** [comment]
Sure! I didn't have enough time to look into them lately, so feel free to do so :)

**Comment by JulianKnodt** [comment]
This can be closed
