### ISSUE TITLE
Two arithmetic overflow found in SubImage::view

### ISSUE THREAD

**Issue by thdusdl1219** [image-rs/image#2017]
I found two arithmetic overflow cases in the latest version. They followed by two assertions but look not working to prevent them.

They happen in L1284 and L1285

https://github.com/image-rs/image/blob/f1e34f365133a33a27dac5bc59c93d1cfb34a37e/src/image.rs#L1280-L1285

## Expected

Assert or use the checked operation instead.

### Case 1
`thread 'main' panicked at 'attempt to add with overflow', .cargo/registry/src/index.crates.io-6f17d22bba15001f/image-0.24.7/./src/image.rs:1271:17`

### Case2
`thread 'main' panicked at 'attempt to add with overflow', .cargo/registry/src/index.crates.io-6f17d22bba15001f/image-0.24.7/./src/image.rs:1272:17`

### Case 1

```
    let mut ImageBuffer_self_obj = image::RgbImage::new(1, 1);
    let SubImage_self_obj = image::SubImage::new(&ImageBuffer_self_obj, u32::MAX, u32::MAX, u32::MAX, u32::MAX);
    SubImage_self_obj.view(1, 1, 1, 1);
```

### Case2

```
    let mut ImageBuffer_self_obj = image::RgbImage::new(1, 1);
    let SubImage_self_obj = image::SubImage::new(&ImageBuffer_self_obj, u32::MAX, u32::MAX, u32::MAX, u32::MAX);
    SubImage_self_obj.view(0, 1, 0, 1);
```

**Comment by fintelia** [comment]
Could you make a pull request to fix these?

**Comment by thdusdl1219** [comment]
Sure, lemme take a look into them in my next available time :)
