### ISSUE TITLE
Unexpected panic due to unwrap None in JpegEncoder::encode

### ISSUE THREAD

**Issue by thdusdl1219** [image-rs/image#2018]
This happens in

L458, 463, 468, 473

https://github.com/image-rs/image/blob/f1e34f365133a33a27dac5bc59c93d1cfb34a37e/src/codecs/jpeg/encoder.rs#L443-L475

## Expected

return Result instead of panic?

## Actual behaviour

```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', .cargo/registry/src/index.crates.io-6f17d22bba15001f/image-0.24.7/./src/codecs/jpeg/encoder.rs:449```

## Reproduction steps

```
    let mut buffer = Vec::new();
    image::ImageEncoder::write_image(image::codecs::jpeg::JpegEncoder::new(&mut
    buffer), &[0], 1, 1024, image::ColorType::L8 /* , La8, Rgb8, or Rgba8 */ );
```

**Comment by fintelia** [comment]
Could you double check that this still happens on `master`? I think the assertion on line 450 (added in #2008) should now catch this case

**Comment by thdusdl1219** [comment]
Right, it does not happen on `master`. Please feel free to close this issue, Thanks!
