### ISSUE TITLE
PBM support

### ISSUE THREAD

**Issue by anstylian** [image-rs/image#2025]
My comment is valid for  `image = "0.24.7"`

In unit test there are the following tests: 
1. [pbm_ascii](https://github.com/image-rs/image/blob/master/src/codecs/pnm/decoder.rs#L1111])
2. [pbm_ascii_nospace](https://github.com/image-rs/image/blob/master/src/codecs/pnm/decoder.rs#L1143)

Both tests are targeting `pbm` format with magic number `P1`.

As I understand from [wikipedia: Netpbm](https://en.wikipedia.org/wiki/Netpbm#PBM_example) the pixels are either 0 or 1, but the  tests mention above they both have the following assertion:
 
`assert_eq!(image, vec![255, 0, 0, 255, 0, 0, 0, 255, 0, 0, 255, 0]);`

I would expect the assert to be:
`assert_eq!(image, vec![0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1]);`

can you please share your thoughts?

**Comment by fintelia** [comment]
The value returned by [`ImageDecoder::color_type`](https://docs.rs/image/latest/image/trait.ImageDecoder.html#tymethod.color_type) determines the meaning of the bytes produced by the decoder. In those cases, they are `ColorType::L8` which means that each pixel takes a single byte and values of 0 and 255 correspond to black and white respectively. We do not support every possible color type that underlying formats do, which means that sometimes there'll be some conversion.

**Comment by anstylian** [comment]
> We do not support every possible color type that underlying formats do, which means that sometimes there'll be some conversion.

Is that on peruse? or is going to be supported in the future?

**Comment by fintelia** [comment]
It is intentional. Having a smaller number of formats makes the API simpler in a bunch of places. And it reduces complexity elsewhere in the crate.

Formats that pack multiple pixels into a single byte would be especially hard to support
