### ISSUE TITLE
Decode PNGs with  (potentially) invalid text chunks

### ISSUE THREAD

**Issue by spiderbiggen** [image-rs/image#2026]
I would like to be able decode PNGs even when text chunks may be invalid

My specific use case for this functionality is scaping web pages with a lot of images that may or may not contain text chunks and may be in different formats.

This is more generally applicable to any downloaded PNG from uncontrolled sources.

## Draft
Since decoding an image for this library already seams to discard any text chunks, I believe this could be accomplished by adding the following line to PngDecoder's with_limits function.

https://github.com/image-rs/image/blob/master/src/codecs/png.rs#L129
```rust 
        decoder.set_ignore_text_chunk(true);
```

**Comment by fintelia** [comment]
Given that we don't expose a way to get the text chunks, I think it makes sense to ignore them while decoding. Want to make a PR?
