### ISSUE TITLE
Rgb32f color space

### ISSUE THREAD

**Issue by Cinglein** [image-rs/image#2031]
What color space is rgb32f in? (Or other image formats, for that matter.) This is useful mostly so that I know whether or not I'll need to linearize the data. Ultimately I want to consume it as a Vec<f32> in linear rgb space.

https://docs.rs/image/latest/image/struct.Rgb.html

The above says it's sRGB -- presumably with gamma 2.2? It doesn't specify though.

https://github.com/image-rs/image/issues/598

But this issue from 2017 says it's linear.

Is the color space linear or 2.2 gamma, and is this guaranteed by calling the relevant DynamicImage function?

**Comment by fintelia** [comment]
This crate isn't color space aware at the moment. The color space will be the same as whatever the image file you loaded was.
