### ISSUE TITLE
How to turn rgba to jpg and make background white

### ISSUE THREAD

**Issue by Septias** [image-rs/image#2033]
I want to downscale an image which has an alpha channel but through the conversion to jpg the background gets black. I want a white one though, how can I achieve that?

**Comment by fintelia** [comment]
A rgba image has red, green, and blue values for all the transparent pixels. When converting to RGB those are the values that get used. It sounds like you need to iterate over all the pixels of your image and set the transparent ones to white

**Comment by Septias** [comment]
Thank you :)
