### ISSUE TITLE
Writing ImageBuffer<Rgba<f32>, Vec<f32>> to disk as a PNG does not work

### ISSUE THREAD

**Issue by Jonne-G** [image-rs/image#2042]
## How does one ... ?
How would I write an `ImageBuffer<Rgba<f32>, Vec<f32>>` to any of the supported file formats?
I would like to use the `.save()` method to write said f32 buffer to disk with any of the formats listed on the [supported-formats page](https://docs.rs/image/latest/image/codecs/index.html#supported-formats).

Ideally the code would work as the [examples/convert.rs](https://github.com/image-rs/image/blob/master/examples/convert.rs):

```rust
// Write the contents of this image using extension guessing.
im.save(Path::new(&into)).unwrap();
```

However, when I try to do this conversion it gives the error `Format error encoding Png: The color Rgba32F can not be represented in PNG.`

## Overall, I'm trying to achieve ...
I am trying to write a small image-processing application that utilizes image buffers to apply a few filters.

In the application I convert the incoming image to a `ImageBuffer<Rgba<f32>, Vec<f32>>` to utilize the 0-1 pixel values.
When time comes to export, I then try to use the `ImageBuffer.save()` method to write out the file to the desired format, but this gives the error shown above.

Ideally (and in its current broken state) my application looks something like this:

```rust
let input_image = ImageReader::open(path)?.decode()?;

let buffer: ImageBuffer<Rgba<f32>, Vec<f32>> = input_image.to_rgba32f();

/* -- Do Some things to the buffer -- */

buffer.save("to/file/decided/by/user.png");
```

**Comment by fintelia** [comment]
The PNG file format cannot store floating point values. You need to convert to Rgba8 or Rgba16 before saving

**Comment by Jonne-G** [comment]
Ah okay, I see. I feel like the docs should specify that, since that isn't quite obvious from anything listed in the docs

**Comment by fintelia** [comment]
If you have thoughts on how the docs could be improved, please do open a PR!
