### ISSUE TITLE
Bump dav1d-rs to 0.10.1

### ISSUE THREAD

**Issue by FlareFlo** [image-rs/image#2044]
The [latest release](https://github.com/rust-av/dav1d-rs/releases/tag/v0.10.0) of dav1d-rs supports the latest version of dav1d 1.3.0, and additionally [fixes problems](https://github.com/rust-av/dav1d-rs/issues/85) encountered when building it transitively through image.

**Comment by fintelia** [comment]
:+1: Would be great to get a PR for this!

**Comment by FlareFlo** [comment]
> 👍 Would be great to get a PR for this!

I would, but i currently have an open PR for image already, and it seems i cannot open a second fork. Any solution to this?

**Comment by FlareFlo** [comment]
Fixed in f1cdb3b3d51baf8ed986db39aef982d16990985e
