### ISSUE TITLE
Promote assertion to Error

### ISSUE THREAD

**Issue by FlareFlo** [image-rs/image#2049]
https://github.com/image-rs/image/blob/eb05a39313093bf37b7fb435dffa48f0ad122112/src/codecs/avif/decoder.rs#L159
Promoting this assertion to an error such as `UnsupportedErrorKind::Format` would let callers catch the error.

**Comment by fintelia** [comment]
Please open a PR!

**Comment by FlareFlo** [comment]
Fixed in #2050
