### ISSUE TITLE
Support RLE encoding for TGA

### ISSUE THREAD

**Issue by marvin-j97** [image-rs/image#2053]
I would like to be able to save images as run-length encoded TGA to save space.
The TGA decoder [seems to](https://github.com/image-rs/image/blob/master/src/codecs/tga/decoder.rs#L390) [support RLE](https://github.com/image-rs/image/blob/master/src/codecs/tga/decoder.rs#L454), but the encoder doesn't.

## Sources

- http://tfc.duke.free.fr/coding/tga_specs.pdf
- https://www.fileformat.info/format/tga/egff.htm#:~:text=information%2C%20if%20any.-,Image%20Data%20Encoding,-Image%20data%20stored
- http://www.paulbourke.net/dataformats/tga/

## Considerations

I'm wondering, from an outside perspective, if I have a DynamicImage, how would one set the encoded = yes/no flag when using `img.save("img.tga")`. Would something like (pseudo API) `img.save_with(path, tga::SaveOptions::encoded())` be required for control over RLE encoding...

**Comment by fintelia** [comment]
The API could use [`DynamicImage::write_with_encoder`](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.write_with_encoder). Analogous to how you can control compression parameters for JPEG:
```rust
let encoder = JpegEncoder::new_with_quality(&mut writer, 95);
img.write_with_encoder(encoder)?;
```

That said, TGA compression is not great by modern standards. If you can use a different format, you'll likely get better compression

**Comment by marvin-j97** [comment]
> That said, TGA compression is not great by modern standards. If you can use a different format, you'll likely get better compression

It's not my choice, unfortunately :neutral_face:

**Comment by fintelia** [comment]
Yeah. Though, I'd probably suggest calling it "rle" or "compression" or something like that. Even the uncompressed version still counts as "encoding".

Another question is whether it makes more sense to add the new option as a constructor ("with_rle") or as a setter ("set_rle"). I think the existing encoders all use constructors, but that doesn't seem as sustainable if we add more options...

**Comment by marvin-j97** [comment]
> Yeah. Though, I'd probably suggest calling it "rle" or "compression" or something like that. Even the uncompressed version still counts as "encoding".
> 
> Another question is whether it makes more sense to add the new option as a constructor ("with_rle") or as a setter ("set_rle"). I think the existing encoders all use constructors, but that doesn't seem as sustainable if we add more options...

Updated :+1:

**Comment by marvin-j97** [comment]
I'm trying to read a bit into the code, and just documenting my thoughts.

Looks like the tga::Header would need another parameter `use_rle`, and extend the match from:
```rs
match color_type {
  ColorType::Rgba8 => (8, 24, ImageType::RawTrueColor),
  // ...
}
```
to
```rs
match (color_type, use_rle) {
  (ColorType::Rgba8, false) => (8, 24, ImageType::RawTrueColor),
  (ColorType::Rgba8, true) => (8, 24, ImageType::RunTrueColor),
  // ... etc
}
```

Need to check the spec to see if this is the only change.

**Comment by marvin-j97** [comment]
Here's my first pass for TGA RLE support:

https://github.com/image-rs/image/pull/2056
