### ISSUE TITLE
Support for multi-channel fp16/fp32 exr images?

### ISSUE THREAD

**Issue by ghost** [image-rs/image#2060]
I would like to be able to load  multi-channel fp16/fp32 exr images

My specific use case for this functionality is for reading exr file from some graphics software.

**Comment by fintelia** [comment]
We support RGB and RGBA f32 images, but I'd suggest using the `exr` crate directly if you want functionality beyond that. I'm not opposed to better support for arbitrary additional channels, but different formats handle them differently so building a common abstraction would be somewhat complicated
