### ISSUE TITLE
Radiance HDR is missing in the supported image formats table

### ISSUE THREAD

**Issue by sorairolake** [image-rs/image#2067]
`ImageFormat` and `ImageOutputFormat` are defined as follows:

<https://github.com/image-rs/image/blob/81b3fe66fba04b8b60ba79b3641826df22fca67e/src/image.rs#L28-L73>
<https://github.com/image-rs/image/blob/81b3fe66fba04b8b60ba79b3641826df22fca67e/src/image.rs#L382-L439>

The supported image formats table is as follows:

<https://github.com/image-rs/image/blob/81b3fe66fba04b8b60ba79b3641826df22fca67e/README.md?plain=1#L23-L38>
<https://github.com/image-rs/image/blob/81b3fe66fba04b8b60ba79b3641826df22fca67e/src/lib.rs#L211-L226>

I think Radiance HDR is not listed in the supported image formats table. Also, other image formats defined in `ImageFormat` and `ImageOutputFormat` seems to be listed.

**Comment by fintelia** [comment]
Please create a PR!
