### ISSUE TITLE
Radiance HDR may be missing in `ImageOutputFormat`

### ISSUE THREAD

**Issue by sorairolake** [image-rs/image#2070]
`ImageOutputFormat` is defined as follows:

<https://github.com/image-rs/image/blob/3dcd4da54891a1eedc4d8cf4927b1aad808a2fd0/src/image.rs#L382-L439>

According to the [supported image formats table](https://github.com/image-rs/image/blob/3dcd4da54891a1eedc4d8cf4927b1aad808a2fd0/README.md#supported-image-formats), this crate can encode all formats listed except DDS. But, Radiance HDR is not defined in `ImageOutputFormat`. So, I think Radiance HDR (`Hdr`) should be added to `ImageOutputFormat`.

**Comment by fintelia** [comment]
Agreed that this was overlooked. And `ImageFormat::{can_write, writing_enabled}` seem to also be incorrect...
