### ISSUE TITLE
image base64 difference issue

### ISSUE THREAD

**Issue by Mon-ius** [image-rs/image#2080]
the example code as following when searching the latest version of crate of both image and base64;

```rust
use std::io::Cursor;
use image::io::Reader as ImageReader;
use base64::{engine::general_purpose::STANDARD as BASE64,  Engine as _};

        let url = std::path::Path::new(_url);
        let base_img = ImageReader::open(url)?.decode()?;
        let mut buf: Vec<u8> = Vec::new();
        base_img.write_to(&mut Cursor::new(&mut buf), image::ImageOutputFormat::Png)?;
        let _b64 = BASE64.encode(&buf);
```

The sample image url is ![nsd-001](https://github.com/image-rs/image/assets/25671258/9e3d3a29-eadd-48f7-80da-c568857e3d7f);

The `base64 -w0` in Linux result ends with, 

```bash
base64 -w0 nsd-001.png

+ql6PbIAAAAASUVORK5CYII=
```

And the Rust code result ends with,

```bash
+kc5q4YMlnKy1wAAAABJRU5ErkJggg==
```

I searched through current issued topic, found the problem is not from the `base64` crate, see "https://www.reddit.com/r/rust/comments/11hyeau/help_cant_correctly_encode_an_image_to_base64"

**Comment by paolobarbolini** [comment]
The difference is probably a result of the image getting decoded and re-encoded using different settings or different encoders, which while all producing PNG compliant images may embed different attributes into the image or use different compression algorithms or settings.

**Comment by Mon-ius** [comment]
But the the original image source is `png`, there should no such encode, decode proccess performed to cause such issue.

**Comment by paolobarbolini** [comment]
`ImageReader::open` is decoding the image. `write_to` is re-encoding it.

**Comment by Mon-ius** [comment]
Did not find a way to prevent such proccess so far, the direct way as "https://www.reddit.com/r/rust/comments/11hyeau/help_cant_correctly_encode_an_image_to_base64" described cause an error.

**Comment by Mon-ius** [comment]
> `ImageReader::open` is decoding the image. `write_to` is re-encoding it.

@paolobarbolini  Now the question becomes, fill the blank code snippet ;)

```rust
 let base_img = image::open(url)?;
# convert the `base_img` into [u8] buffer
let _b64 = BASE64.encode(&buf);
```

**Comment by Mon-ius** [comment]
Okay, f**k `image`;

```rust
        let _buf = std::fs::read(&_url)?;
        let _b64 = BASE64.encode(&_buf);
```
Just solved it :P
