### ISSUE TITLE
WebPEncoder is not available in rustdocs

### ISSUE THREAD

**Issue by qrilka** [image-rs/image#2082]
This happens in rustdocs for the crate

## Expected

It's expected that both WebPDecoder and WebPEncoder should be available in the crate's rustdocs

## Actual behaviour

Only WebPDecoder is shown on https://docs.rs/image/latest/image/codecs/webp/index.html

## Reproduction steps

In https://github.com/image-rs/image/blob/25b284c20c576c21fbfd0ec66c23c830dfd6bc04/src/codecs/webp/mod.rs both structs are visible (under webp feature flag) and on https://docs.rs/image/0.24.7/image/codecs/webp/index.html only the decoder

**Comment by fintelia** [comment]
This will be resolved by #2066

**Comment by qrilka** [comment]
@fintelia does this mean that a new version is about to be published?

**Comment by fintelia** [comment]
Yep: https://github.com/image-rs/image/pull/2095
