### ISSUE TITLE
No method to get xoffset/yoffset from SubImage after deprecating bounds() in #2036

### ISSUE THREAD

**Issue by brykgroup-andrews** [image-rs/image#2118]
As of 0.25.0, specifically in MR #2036, the `::bounds(&self)` method has been deprecated. But there has been no way to get the x and y offsets out of that view since that deprecation - is there any way that something can be reintroduced alongside the newly minted `::dimentions(&self)` call?

In my case, I use it in a `::change_bounds()` call in order to shift the bounds around by a relative margin.

**Comment by fintelia** [comment]
Yeah, removing access to the offsets wasn't intentional. Please feel free to make a PR adding a method to access them
