### ISSUE TITLE
with_guessed_format() fails on one machine, but not the other.

### ISSUE THREAD

**Issue by derspyy** [image-rs/image#2123]
i have this website that gets images from lastfm api and some jpeg images (example:
https://lastfm.freetls.fastly.net/i/u/300x300/902d994170dae8b880c8680f9d3adc6f.jpg)
can't have their formats guessed ("The image format could not be determined")

this is the website for the request: https://piuvas.envs.sh/semaninha/collage?user=andrs-162&size=3&period=1month
my code: https://git.envs.net/piuvas/semaninha/src/commit/77669b6574566c1420738b394e063fc4c1fa7da8/src/main.rs#L65-L67

it works on my arch pc but not on a debian server.

maybe some library issue?

**Comment by fintelia** [comment]
The logic for guessing the format isn't very complex. We read the first 16 bytes of the file and then loop over various file prefixes corresponding to different image types. If the file starts with `ff d8 ff` then it is a JPEG, etc. I'm not sure why that would depend on which OS the code was running on.

Perhaps check whether the first bytes of the file you're passing to `guess_format` match between the two systems?

**Comment by derspyy** [comment]
will do!

**Comment by derspyy** [comment]
oop. suddenly worked. no clue...

**Comment by derspyy** [comment]
maybe some issue with their api.
