### ISSUE TITLE
exit code: 0xc0000135, STATUS_DLL_NOT_FOUND after enabling avif-decoder

### ISSUE THREAD

**Issue by soupslurpr** [image-rs/image#2132]
I'm using Windows 11, Rust 1.76.0 latest stable and MSVC.

## Expected

My program runs normally

## Actual behavior

Compiles fine, but crashes when running with exit code: 0xc0000135, STATUS_DLL_NOT_FOUND

## Reproduction steps

1. Enable avif-decoder and follow the steps to properly install dav1d
2. Just have code that loads an image like so (in my actual program the image doesn't even get loaded yet it just crashes when the program starts, just need to include in this example to make it not optimize it away I think)
```
fn main() {
    let img = image::open("image.webp").unwrap();
}
```

**Comment by fintelia** [comment]
This crate doesn't have any logic for loading DLLs, so I assume the issue is coming from `dav1d`. Might be worth trying to reproduce with only using that crate instead of `image`?

**Comment by soupslurpr** [comment]
You were right, same error occurs using only dav1d

```
fn main() {
    dav1d::Decoder::new().unwrap();
}
```

**Comment by soupslurpr** [comment]
Installing ffmpeg from vcpkg instead of winget fixed it.
