### ISSUE TITLE
Webp encoder version is outdated and vulnerable

### ISSUE THREAD

**Issue by soupslurpr** [image-rs/image#2147]
The webp encoder is vulnerable as it is using an outdated version of the webp crate (0.2.2, almost 2 years old!), please update it.

https://github.com/jaredforth/webp/pull/30

**Comment by soupslurpr** [comment]
Okay sorry, I forgot how cargo versions work and that it specifies any version 0.2.2 and above but under 0.3.0

**Comment by fintelia** [comment]
Yeah, running `cargo update` should pull in a patched version of libwebp. Though for the record, AFAIK that specific vulnerability only impacts decoding while we only use libwebp for encoding
