### ISSUE TITLE
Decoding out of image::io::Reader directly into user-controlled buffer

### ISSUE THREAD

**Issue by jonhoo** [image-rs/image#2162]
I would like to be able to decode from an `io::Reader` into a buffer I control.

My specific use case for this functionality is to avoid an allocation + copy on the critical path of a very hot loop that has to extract the raw image bytes from an image elsewhere in memory.

This is more generally applicable to anyone who may want to eliminate an extra copy in their applications.

## Draft

I think most of the functionality already exists, it's just private in the form of `free_functions::load_inner`:

https://github.com/image-rs/image/blob/2b513ae9a6ac306e752914f562e7d408f096ba3f/src/io/free_functions.rs#L900-L111

plus a variant of `decoder_to_vec`:

https://github.com/image-rs/image/blob/2b513ae9a6ac306e752914f562e7d408f096ba3f/src/image.rs#L708-L722

that re-uses an existing `Vec` instead of allocating a new one. The latter is easy enough to replicate, and so _probably_ doesn't need to be provided by the `image` crate (though it'd be a nice-to-have).

The easiest way to provide this functionality is likely to add a method to `io::Reader` that exposes the `ImageDecoder`. Might be tricky given the `Visitor` pattern, but hopefully doable. Perhaps via a provided callback function?

I'll tack on to the end here that we currently use a `Cursor` over a `&[u8]` to construct an `io::Reader`, which feels a little odd. Is there a nicer way to get `with_guessed_format` without having to go via an I/O trait when you have the image in a buffer already, or is this the intended way?

**Comment by fintelia** [comment]
This is actually being addressed in the 0.25 release! The `ImageDecoder` trait is being changed to be object safe, at which point we can add a [`io::Reader::into_decoder`](https://docs.rs/image/0.25.0-preview.0/image/io/struct.Reader.html#method.into_decoder) method:

```rust
let decoder = Reader::open("path/to/image.png")?.into_decoder()?;
let size = decoder.total_bytes();
decoder.read_image(&mut buf[..size])?
```

> I'll tack on to the end here that we currently use a Cursor over a &[u8] to construct an io::Reader, which feels a little odd. Is there a nicer way to get with_guessed_format without having to go via an I/O trait when you have the image in a buffer already, or is this the intended way?

If you only need to know the format, you can call [`guess_format`](https://docs.rs/image/0.25.0-preview.0/image/fn.guess_format.html) which directly takes a slice of bytes. But if you're going to be decoding the image anyway, you already need to have a `Cursor<&[u8]>` so might as well use it for guessing the format. And `with_guessed_format` is pretty simple: it reads the first 16-bytes, looks them up in a table of magic bytes for different formats, and then seeks back to the start.

**Comment by fintelia** [comment]
There's currently a _0.25.0-preview.0_ release out. Assuming no glaring issues are found with it, a full _0.25.0_ should be at most a few weeks away.

As far as taking advantage of the whole image being in memory, that's actually something that's been discussed in the context of the `png` crate (which is one of the few decoders fast enough for it to possibly matter). The strategy we're investigating there is using the methods provided by the `BufRead` trait. In particular, the implementation of `Cursor::fill_buf` returns the the entire remainder of the slice. If you are curious there's currently a [draft PR](https://github.com/image-rs/image-png/pull/427) and [more discussion here](https://github.com/image-rs/image-png/discussions/416#discussioncomment-8088740).

**Comment by fintelia** [comment]
0.25.0 is now released!
