### ISSUE TITLE
Disable strict mode on JPEG decoder

### ISSUE THREAD

**Issue by djc** [image-rs/image#2180]
I would like to be able to decode JPEG images using HDR functionality to embed "multiple images" without errors.

My specific use case for this functionality is decoding images captured from Instagram for resizing.

This is more generally applicable to JPEG decoding. See https://github.com/etemesi254/zune-image/issues/167.

## Draft

The default JPEG decoder settings should not be strict (in this regard).

**Comment by fintelia** [comment]
Could you make a PR? This wasn't an intentional choice when switching to zune-jpeg, there was just a lot of code movement leading up to `0.25` and it got overlooked. In general, we try to default to accepting images with errors within reason/when other decoders do.

**Comment by djc** [comment]
Of course, thanks for the quick response! Will follow up soon.
