### ISSUE TITLE
JPEG encoding is incorrect

### ISSUE THREAD

**Issue by nashaofu** [image-rs/image#2188]
Save as JPEG does not meet the expectations.

## Expected

Expect the image to display correctly

## Actual behaviour

Image encoding error

## Reproduction steps

Provide source code, a repository link, or steps

```rust
use image;

fn main() {
    let im = image::open("input.png").unwrap();
    im.save("output.jpeg").unwrap();
}
```
* input.png
![input](https://github.com/image-rs/image/assets/19303058/e083a839-c4f5-4c07-bf74-a1242ec6d3da)
* output.jpeg
![output](https://github.com/image-rs/image/assets/19303058/beb1e2b2-4bec-40c8-b7c2-0fc7dd58b44a)

**Comment by gucki** [comment]
Thank you @nashaofu! After reading through other issues, it seems to be a duplicate of https://github.com/image-rs/image/issues/2173. Converting it to a DynamicImage, using to_rgb8 and then saving it as JPG works as expected.

**Comment by nashaofu** [comment]
Get
