### ISSUE TITLE
Convenience function for encoding a `DynamicImage`

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#2225]
I am looking at the [`ImageEncoder` documentation](https://docs.rs/image/0.25.1/image/trait.ImageEncoder.html) and the API for writing an image is fairly low-level. If I have a `DynamicImage`, there doesn't seem to be a function to just write to to the specified format.

Am I just looking into the wrong place in the docs? And if not, is there a reason `ImageEncoder` doesn't just provide a wrapper around the low-level API that accepts a `DynamicImage` and writes it?

**Comment by fintelia** [comment]
The function you are looking for is probably [`write_to`](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.write_to) or [`write_with_encoder`](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.write_with_encoder)

**Comment by Shnatsel** [comment]
Ah, `write_with_encoder` is the one. Thanks!
