### ISSUE TITLE
Animated PNG is decoded incorrectly

### ISSUE THREAD

**Issue by SludgePhD** [image-rs/image#2265]
## Expected
![bonzi-book](https://github.com/image-rs/image/assets/96552222/7b50019a-7c6f-4625-99c2-f1e69de95b61)

This is how the animation should look (assuming your browser correctly implements APNG decoding; Firefox and Chromium-based browsers work fine in my tests).

## Actual behaviour

[Screencast_20240623_180709.webm](https://github.com/image-rs/image/assets/96552222/090ec233-f1c4-43fd-abd7-f5899783ee9e)

Using `image` to decode the animation and rendering the result to a window produces this flickering output instead. Other images work fine, so I don't think the bug is in my code.

## Reproduction steps

The failing APNG is attached above.

**Comment by ripytide** [comment]
I can reproduce the issue:

```rust
use std::io::Cursor;

use image::codecs::png::PngDecoder;
use image::AnimationDecoder;

fn main() {
    let png_decoder = PngDecoder::new(Cursor::new(std::fs::read("monkey.png").unwrap())).unwrap();

    dbg!(png_decoder.is_apng().unwrap());

    let apng_decoder = png_decoder.apng().unwrap();

    let frames = apng_decoder.into_frames().collect_frames().unwrap();

    for (i, frame) in frames.into_iter().enumerate() {
        frame
            .buffer()
            .save_with_format(format!("frame-{i}.png"), image::ImageFormat::Png)
            .unwrap();
    }
}
```

It seems frames 2, 12 and 13 have missing sections (possibly via alpha=0) and all other frames seem fine.

**Comment by Shnatsel** [comment]
At a glance this looks like an issue with compositing. Those frames do not change the the book, so that area is omitted from the frames. Other decoders fill in that area from the composited result of the previous frames, but apparently `image` does not.

We have correct compositing in the GIF decoder in `image` already. It even handles memory limits. We should generalize it to APNG and WebP animations too.

**Comment by MocA-Love** [comment]
I'm currently running into the same problem and will look into it.
