### ISSUE TITLE
The image crate is a top-5 bandwidth consumer on crates.io

### ISSUE THREAD

**Issue by kornelski** [image-rs/image#2267]
Recent downloads &times; crate size gives 11TB of bandwidth used. That's more than the `libc` crate.

This has been fixed in https://github.com/image-rs/image/pull/2206, so it'd be nice to make a point release with the slimmed package.

**Comment by HeroicKatora** [comment]
I've been drafting a bit here, but there are quite a few additional merges that happened: https://github.com/image-rs/image/tree/release-0.25.2 Anyone feel free to add notes and/or rebase on top of the current must_use, too. Otherwise, I'm planning to do it sometimes this weekend.

**Comment by Shnatsel** [comment]
v0.25.2 with the fix has shipped. This can now be closed.
