### ISSUE TITLE
Accidentally pushed to main

### ISSUE THREAD

**Issue by kornelski** [image-rs/image#2269]
Sorry, 4ef7e69e908d5d687fb1ca0d940b495ad76db31e was meant to be a PR.

I can't undo the push, because the `main` is protected against that, but wasn't protected against direct push without a PR.

**Comment by HeroicKatora** [comment]
> I can't undo the push, because the main is protected against that, but wasn't protected against direct push without a PR.

wut.png

Anyways, changing the branch protection rules also allowed me to force-push the previous head after the merge of `#[must_use]`.
