### ISSUE TITLE
Detect alpha on jpeg

### ISSUE THREAD

**Issue by mothsART** [image-rs/image#2317]
I read https://github.com/image-rs/image/issues/2211 and I think this issue is slightly diff.

Image-rs doesn't detect when an **jpeg** image is **rgb8** or **rgba8**.

With the software **The Gimp**, I have opened a jpeg file without alpha channel :

![rusted_chain__with_alpha](https://github.com/user-attachments/assets/d25a3d8e-ca6a-4f42-bab2-1d419f4c6d69)

Secondly, I have created a other jpeg file with an alpha channel : 
![rusted_chain__without_alpha](https://github.com/user-attachments/assets/56623dcb-fd04-4f2b-bfad-b85a13e8736f)

## Expected

On the 2 pictures, `img.color()` give me **Rgba8** and `img.color().has_alpha()` is **true**.

## What behaviour should have happened

I think, first picture will give me **Rgb8** and alpha on **false**.
The second picture will give me **Rgba8** and alpha on **true**.

**Comment by fintelia** [comment]
The JPEG file format cannot store alpha so I'd expect _neither_ one to be Rgba8. Could you share the code you are using to load the images?

**Comment by mothsART** [comment]
When I read the code from my projet, I realize than I used an intermediate buffer with rgba.
Sorry.
