### ISSUE TITLE
Error: PNG image and JPEG failed loading

### ISSUE THREAD

**Issue by itsNiccoloSabatini** [image-rs/image#2330]
This happens in Rust egui/eframe framework,

I add an image to my UI, written in Rust using **egui** and **eframe**, and it used to be load with the `24.9`. But when I updated to `25.2` the images won't load anymore. there's a pop up saying "failed loading bytes::/_imagePath_: the image format Png is not supported" or the same but Jpeg. 

`ui.add(egui::Button::image(LocalImage::Menu.as_image()).fill(UiColor::Orange)` this is how I load an image now, and `LocalImage` is looks something like this:

``` rust
impl LocalImage {
    pub fn as_image(&self) -> egui::Image<'static> {
        match self {
            LocalImage::Green => egui::Image::new(egui::include_image!("images/colors/green.png")),
            LocalImage::Red => egui::Image::new(egui::include_image!("images/colors/red.png")),
            LocalImage::Orange => {
                egui::Image::new(egui::include_image!("images/colors/orange.png"))
            }
            LocalImage::FourG => egui::Image::new(egui::include_image!("images/icons/4g.png")),
            LocalImage::Calling => {
                egui::Image::new(egui::include_image!("images/icons/calling.png"))
            }
            LocalImage::Done => egui::Image::new(egui::include_image!("images/icons/done.png")),
            LocalImage::Error => egui::Image::new(egui::include_image!("images/icons/err.png")),
            LocalImage::Menu => egui::Image::new(egui::include_image!("images/icons/menu.png")),
            LocalImage::Time => egui::Image::new(egui::include_image!("images/icons/time.png")),
            LocalImage::TurnOff => {
                egui::Image::new(egui::include_image!("images/icons/turn-off.png"))
            }
        }
    }
}
```
this is an image of what happens.
![immagine](https://github.com/user-attachments/assets/8ce3881e-f14d-4d2c-b5d1-789e2a5a69fa)

**Comment by fastfailure** [comment]
It seems the problem disappeared with latest egui/eframe version (0.29.1)

**Comment by fintelia** [comment]
This crate uses Cargo features to enable/disable format support. So probably what happened is that egui/eframe set `default-features = false` and in the process disabled support for PNG, JPEG and all the other formats.

**Comment by Shnatsel** [comment]
This was not an issue with `image` and the latest egui version works, so I'm going to go ahead and close this.
