### ISSUE TITLE
Calling `resize` returns a `ImageBuffer <Rgba<_>, _>` for `DynamicImage`

### ISSUE THREAD

**Issue by emsknock** [image-rs/image#2331]
See the following:

```rust
use image::ImageReader;
use image::imageops::{resize, FilterType};

let input_img = ImageReader::open(input_path)?.with_guessed_format()?.decode()?;

let scaled = resize(
	&input_img,
	target_width,
	target_height,
	FilterType::Lanczos3,
);
```

The type of `scaled` is now `ImageBuffer<Rgba<u8>, Vec<u8>>`. This is despite the fact that the image at `input_path` can be a jpeg image; it shouldn't be possible (at least to my understanding) for it to have an alpha channel. This causes problems when I move on to save the image:

```rust
let output_path = "output.jpeg";

scaled.save(output_path)? // → UnsupportedError { format: Exact(Jpeg), kind: Color(Rgba8) }
```

I can work around this with something like:

```rust
DynamicImage::from(scaled).to_rgb8().save(…)
```

But that's not very nice to use when the input/output can also be e.g. transparent png files.

This seems like it could be related to #2274, #2237, and #2227.

**Comment by HeroicKatora** [comment]
Yes. Not a bug.
