### ISSUE TITLE
Proper names for the pixel types

### ISSUE THREAD

**Issue by kleenleen** [image-rs/image#2336]
This is not a feature request, but you have no ticket :: enhancement category.

The issue is that current pixel types are:

    Rgb: RGB pixel
    Rgba: RGB with alpha (RGBA pixel)
    Luma: Grayscale pixel
    LumaA: Grayscale with alpha

This is a bad type naming convention: it's not following any consistent pattern.
Why LumaA (alpha gets a capital A, when it's a small case for Rgba'alpha?

To make the code cleaner, it should be named:

Rgb
RgbA
Luma
LumaA

or

rgb
rgba
luma
lumaa

or

RGB
RGBa
LUMA
LUMAa

Then why did you name the image type gray, when previously you chose Luma for grayscale ?
There's no consistency. Gray has full alpha naming, Rgb alpha is a single letter.

    GrayAlphaImage
    GrayImage
    Rgb32FImage
    RgbImage
    Rgba32FImage
    RgbaImage

Why not call it like this (f32 at the end to comply with Rust's primitive naming convention):

   LumaImage
   LumaImage_f32
   LumaAphaImage
   LumaAphaImage_f32 (missing 32 bit GS image types)
   RgbImage
   RgbImage_f32
   RgbAlphaImage
   RgbAlphaImage_f32

**Comment by kleenleen** [comment]
I'd vote for code consistency and proper names convention, leading to **long term code quality**, over leaving things imperfect code forever be as is, because that would disrupt a few users _once_, forcing them to spend half an hour to update a few types.

**Comment by kornelski** [comment]
Luma is a word, not an acronym (a kind of luminance), so it shouldn't be LUMA.

LumaAlpha would be ok according to Rust naming guidelines, but then RgbAlpha would be oddly inconsistent, and RedGreenBlueAlpha annoyingly long.

OTOH, L and LA would match the RGB and RGBA naming scheme, but single-letter types are odd in their own way, and would be harder to understand given that Luma is not as a popular term as RGB. 

There's no way to win this.

**Comment by kleenleen** [comment]
If working clean and naming things with consistency is trolling, I am then.

Good for YouU if the CaptiaL letters placed poorly and unmatching terms within such a simple api are not an issue.
