### ISSUE TITLE
`Orientation` is a toplevel type in v0.25.3 on crates.io

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#2353]
The version of `image` published to crates.io as v0.25.3 contains `Orientation` as a toplevel type, so it must have been published before  #2349 was merged.

We could either yank it and republish a newer commit, or just accept that Orientation is a toplevel type now and adjust git accordingly. I think yanking is a better option right now.

cc @HeroicKatora

**Comment by fintelia** [comment]
I'd vote for yanking. 0.25.3 was published with commit fe94eabb7f7491b9ba9378ea5ece2f8884c30c65 rather than the merge commit d52a194e5c3fa304143cc71d85d551e88fd211d9 (the current head commit on the main branch), which means the current crates.io release isn't actually from the main branch

**Comment by HeroicKatora** [comment]
Sure, if that happened on top of the other Changelog issue then yanking seems fine to me. Sorry for the apparent communications issues :/
