### ISSUE TITLE
Fixed point in JPEG encoder

### ISSUE THREAD

**Issue by awxkee** [image-rs/image#2386]
YUV encoding/deconding usually works well enough in fixed-point arithmetic and it is faster than floating point. Therefore, it may be possible to replace current JPEG encoding pipeline with Q16 multiplication. Notably, [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/9758c8a74ceb6ee7d4f8350fa2767fdc5b2bad2a/simd/arm/aarch64/jccolext-neon.c#L31) also done in fixed-point arithmetic, so there will be no significant deviation from almost reference implementation.

However, switching to fixed-point is unlikely to yield significant improvements, there is only a few percent gains in end-to-end encoding.

Here is an experimental implementation to try out this approach: https://github.com/awxkee/image/tree/test_yuv_jpeg_fixed_point

```bash
cargo bench --bench fixed_point
```

Tests shows that fixed-point faster something about 20%, but in end-to-end encoding gain are varies from 2% to 7%.

P.S.
Anyway, it seems here `.round()` is missing, so luma and chroma values are truncated on each pass. Over time, this truncation leads to #2311

https://github.com/image-rs/image/blob/5080752fa41640e1a4adeb962bcdf79b3f428134/src/codecs/jpeg/encoder.rs#L773-L789

**Comment by HeroicKatora** [comment]
Getting 2% - 7% over the whole pipeline while improving the accuracy in the process is quite massive. Would you submit a PR with the change to the numeric conversion? Without the benchmarks probably as they won't measure active code, though it'd be nice to refer to them somehow in the evolution. (Quirky idea: maybe you could split that into two commits and then also add a revert of the benchmark addition :joy:). Also please do keep the comment with the original coefficients, I think they explain the magic integer coefficients nicely.
