### ISSUE TITLE
Unexpected Rotations

### ISSUE THREAD

**Issue by RacingRayray** [image-rs/image#2392]
Hello,

I am reading an jpeg from Vec<u8> and writing it back to the buffer and getting unexpected random rotations either 90 or 180 (flipped). Do I miss anything?

Here is my code:

```
let mut tile_buffer: Vec<u8> = Vec::new();
let _tile = ImageReader::new(Cursor::new(contents.clone()))
                    .with_guessed_format()
                    .unwrap()
                    .decode()
                    .unwrap_or(DynamicImage::ImageRgb8(RgbImage::new(100, 100)))
                    .write_to(&mut Cursor::new(&mut tile_buffer), ImageFormat::Jpeg);
```
Original image that is in ```contents```
![original](https://github.com/user-attachments/assets/0a2fed16-d73e-42f1-86da-3bc0ea9e620a)

Image in ```tile_buffer```, after  ```write_to```
![AfterImageReader](https://github.com/user-attachments/assets/c1386424-849b-4d39-b20a-ac03c1461c1a)

**Comment by kornelski** [comment]
Additional rotation of an image can be stored in EXIF data. The actual pixels in the file are in a "wrong" orientation, and the EXIF metadata is used by image viewers to rotate the image to the "correct" orientation. 
If you don't parse EXIF and apply rotation like it wants, you'll get images with unintended rotation.

**Comment by RacingRayray** [comment]
Thanks @kornelski, but when I skip  my ```ImageReader``` code and use raw ```contents``` I am getting exactly the same image as in original.

**Comment by fintelia** [comment]
See the example code on [`DynamicImage::apply_oriontation`](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.apply_orientation) for how to deal with EXIF orientation:

```rust
let mut decoder = ImageReader::open("file.jpg")?.into_decoder()?;
let orientation = decoder.orientation()?;
let mut image = DynamicImage::from_decoder(decoder)?;
image.apply_orientation(orientation);
```
