### ISSUE TITLE
RGB values saved are different from the RGB values I wrote.

### ISSUE THREAD

**Issue by Dqmino** [image-rs/image#2396]
```rust
#[test]
fn test_write_read() {
    let starter_pixel = Rgb([104, 101, 121]);
    let mut write_image: ImageBuffer<Rgb<u8>, Vec<u8>> = ImageBuffer::new(1u32, 1u32);

    for (x, y, pixel) in write_image.enumerate_pixels_mut() {
        *pixel = starter_pixel.clone();
    }

    write_image.save(PATH).unwrap();

    let read_image = image::open(PATH).unwrap();
    let raw_read_data = read_image.into_rgb8().into_raw();

    assert_eq!(raw_read_data, starter_pixel.0);
}
```

This fails, and if you print `raw_read_data` you get `[101, 103, 119]` (NOT supposed to happen)
but if you print `starter_pixel` you get `[104, 101, 121]` (supposed to happen)

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the JpegEncoder to use higher quality settings and adjust the color space conversion to preserve color accuracy better. This should resolve the issue where encoded and then decoded colors don't match the original values.

You can review changes in this commit: https://github.com/jacks-sam1010/image-rs-image-2396/commit/c96eb9993826db891fdba1ac1cf29cdf1f3fc4a4.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by fintelia** [comment]
For what it's worth, the AI response is only partially correct. Using a higher quality setting will _reduce_ the difference between the original values and what gets stored in the image. But if you want bit-exact output you should be using a lossless image format like PNG rather than JPEG
