### ISSUE TITLE
Need more portable image coordinates.

### ISSUE THREAD

**Issue by alexchandel** [image-rs/image#258]
Not all images and image buffers have their origin in the same location. While many have their origin in the top-left corner, and have their x-axis index columns left-to-right, and their y-axis index rows top-to-bottom, there are important exceptions. For example, buffers from gdi32 index rows bottom-to-top, and the BMP format reverses its x and y axes.

The image API functions should have clearer parameter names than `x` and `y`. Maybe `row` and `col`?

**Comment by bvssvni** [comment]
Does this mean when opening a BMP image, you get an image with reversed axis?

I would expect no matter how the format is encoded, the image would be stored in the buffer in a consistent way, such that no special knowledge about the format is required to display the image correctly.

**Comment by tomaka** [comment]
Also when you load a texture OpenGL, you are supposed to upload the rows bottom-to-top (even though you could also choose to upload it top-to-bottom and reverse your texture coords every time you use the texture).

Being able to ask the library to load an image in this order would be nice.

**Comment by nwin** [comment]
We could specialize ImageBuffer over the row order such that we always normalize to intuitive default but per request one could get a transformed buffer.
