### ISSUE TITLE
[gif] Support output for animated images

### ISSUE THREAD

**Issue by nwin** [image-rs/image#331]
So far I’m working on support for animated gif. It’s working but the interface it’s still a bit hacked such that I won’t make a PR yet.

GIF is so efficient for encoding movies…not.

![out](https://cloud.githubusercontent.com/assets/949560/6684988/874e340c-cc96-11e4-904b-1ff519f4cb71.gif)

**Comment by bvssvni** [comment]
Cool!

**Comment by birktj** [comment]
It seems like support for this was added in #773 so I will close this issue.
