### ISSUE TITLE
Meta-bug: images in Servo test suite

### ISSUE THREAD

**Issue by kmcallister** [image-rs/image#413]
A number of images in Servo's test suite are not decoded correctly by piston-image at present. I've put together [a report](http://kmcallister.github.io/docs/piston-image-report/index.html) that should be useful to anyone who has time to work on these issues.

Let me know if there's any other useful information I can provide :) We can coordinate on this ticket, and I'll keep the report up-to-date.

Open issues:
- [x] #414

**Comment by waddlesplash** [comment]
To me, it looks like quite a lot of the differences here probably are caused by a single off-by-one error.

**Comment by kmcallister** [comment]
@tomaka suggested `inflate.rs` as the culprit for some PNG bugs, so I'll try fuzzing it against libflate2.

**Comment by nwin** [comment]
Thanks, that is a nice report. 

Some bugs also look like as if image magic would apply some color/gamma profiles we absolutely not process atm.

fwiw, I’m working on new [png](http://github.com/nwin/png)/[gif](http://github.com/nwin/gif) decoders atm which are a bit more flexible and should also allow for incremental decoding. For the png decoder I actually used the flate2 cate.

**Comment by nwin** [comment]
`image` *should* now pass all png test cases.

**Comment by mbrubeck** [comment]
image-png/issues#4

**Comment by HeroicKatora** [comment]
I'm closing this for being outdated. If there is still a test suite with fails, then *please* open it again as I would be very interested.
