### ISSUE TITLE
Run BMP decoder through bmpsuite

### ISSUE THREAD

**Issue by jdm** [image-rs/image#455]
http://entropymine.com/jason/bmpsuite/bmpsuite/html/bmpsuite.html is a really thorough suite of edge cases, and it would be great to put this decoder through its paces. Adding it to the automated tests would be great, too.

**Comment by martinlindhe** [comment]
Looking into this

**Comment by fintelia** [comment]
I vaguely recall coming across bmpsuite, wanting to images from it as test cases, and the noticing that had already been done

**Comment by martinlindhe** [comment]
The good folder is all passing, but working thru the rest, I'm currently looking at 2-bit support (Windows CE), more for feature completion than general usefulness.
I didn't cross-check checksums, so perhaps some of those are already in the repository. I'll make sure no dupes gets added.

I also imagine having these semi-valid bmp:s in the repo is a good source for mutation-based fuzzing.

**Comment by martinlindhe** [comment]
I also found a different bmptestsuite here: https://github.com/jangko/nimBMP/tree/master/bmptestsuite-0.9 (not original source)

**Comment by martinlindhe** [comment]
@fintelia You are right, several of the images from bmpsuite is in tests/reference/bmp/images already.
