### ISSUE TITLE
Support flif

### ISSUE THREAD

**Issue by redaready** [image-rs/image#469]
http://flif.info/

**Comment by Razican** [comment]
I created an interface for the C decoding library: https://github.com/Razican/libflif_dec-rs
Maybe it can be used from here or it could be adapted. It uses current development snapshot.

**Comment by nwin** [comment]
Thank your, but we intend to use only en-/decoders written in Rust. So no, we can’t use it here.

**Comment by Razican** [comment]
Oh, that'd be great, maybe in some months I can help on it, but I currently don't have time to port all the algorithm :/

**Comment by waldyrious** [comment]
I wonder if [corrode](https://github.com/jameysharp/corrode) could help here.

**Comment by newpavlov** [comment]
What about @dgriffen's [flif](https://github.com/dgriffen/flif.rs) pure-Rust crate? Currently it supports only limited subset of `flif` images, but maybe it can be enabled behind disabled-by-default experimental feature?

**Comment by dgriffen** [comment]
Just to chime in on flif support: Flif might not make too much sense for a game library. The decoding speed is notoriously slow currently (both in the official implementation and in mine). This may be improved in time but is limited by the fact that the decoding is inherently single-threaded.

**Comment by pix64** [comment]
Image is being used outside of game libraries, such as with Servo.

**Comment by dgriffen** [comment]
Ah, yeah in that case putting flif behind a flag sounds like it would be the best option. I'm still working on getting full non-interlaced support. That said, some of the methods on `ImageDecoder` don't make much sense in a flif context, especially if the image is interlaced. For example: `load_rect` would require loading the entire image up to that point and then just returning the decoded region. Which may be more work than the user would be expecting.
