### ISSUE TITLE
check for overflow when allocating pixel data in decoders

### ISSUE THREAD

**Issue by froydnj** [image-rs/image#484]
The BMP decoder, for instance, has:

https://github.com/PistonDevelopers/image/blob/master/src/bmp/decoder.rs#L387

which can easily overflow on a 32-bit system if a specially crafted BMP is used.  (The BMP Suite has just such an image, and while that calculation doesn't overflow on a 64-bit system, it does OOM.  One thing at a time...)

**Comment by HeroicKatora** [comment]
Which line would this refer to exactly? I've searched for it in commit 7aea3d8db3d7c2ef4460ab1a494305a243e093a8 from the date before this issue (and all commits relating to bmp), and it might be https://github.com/PistonDevelopers/image/blob/c142a61df80a3dba8be626289488d37b2dadeeb1/src/bmp/decoder.rs#L876 in the current master? Can someone confirm?

**Comment by fintelia** [comment]
I think this specific instance has been fixed but please create PRs if you notice specific places where decoders can overflow
