### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by emberian** [image-rs/image#503]
# Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback, and has protections from
patent trolls and an explicit contribution licensing clause. However, the
Apache license is incompatible with GPLv2. This is why Rust is dual-licensed as
MIT/Apache (the "primary" license being Apache, MIT only for GPLv2 compat), and
doing so would be wise for this project. This also makes this crate suitable
for inclusion in the Rust standard distribution and other project using dual
MIT/Apache.
# How?

To do this, get explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright) and then add the following to
your README:

```
## License

Licensed under either of
 * Apache License, Version 2.0 ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)
at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you shall be dual licensed as above, without any
additional terms or conditions.
```

and in your license headers, use the following boilerplate (based on that used in Rust):

```
// Copyright (c) 2015 t developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT
// license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
```

And don't forget to update the `license` metadata in your `Cargo.toml`!
# Contributor checkoff
- [x] @nwin
- [x] @bvssvni
- [x] @ccgn
- [x] @tomaka
- [x] @ruud-v-a
- [x] @Potpourri
- [x] @hauleth
- [x] @andersk
- [x] @mbrubeck
- [x] @pix64
- [x] @brookst
- [x] @TyOverby
- [x] @froydnj
- [x] @huonw
- [x] @cybergeek94
- [x] @indiv0
- [x] @b52
- [x] @cmr
- [x] @jpernst
- [x] @Ryman
- [x] @maxsnew
- [x] @gchp
- [x] @frewsxcv
- [x] @tafia
- [x] @ollie
- [x] @pavlov-dmitry
- [x] @zsiciarz
- [x] @AngryLawyer
- [x] @toqueteos
- [x] @lifthrasiir
- [x] @leonkunert
- [x] @bombless
- [x] @twoodford
- [x] @theotherphil
- [x] @orangea
- [x] @andrewrk
- [x] @dummer
- [x] @bpicolo
- [x] @lfairy
- [x] @Doom032
- [x] @Esption
- [ ] @burtonageo
- [x] @xanium4332
- [x] @jdpage
- [x] @Gekkio
- [x] @lucidd
- [x] @m4rw3r
- [x] @mprobinson
- [x] @XMPPwocky
- [x] @paulrouget
- [x] @retep998
- [x] @PeterMozesMerl
- [x] @flying-sheep
- [x] @Blei
- [x] @rsaarelm
- [x] @SimonSapin
- [x] @sondrele
- [x] @stjahns
- [x] @lgvz
- [x] @Denommus
- [x] @bfops
- [x] @ahtn
- [x] @robo9k

(Edit by @HeroicKatora 2019/05/05): Complementary list at https://github.com/image-rs/image/issues/503#issuecomment-489455940

**Comment by xanium4332** [comment]
What is the process for a contributor to provide explicit approval?

**Comment by frewsxcv** [comment]
I consent to relicensing my edits as MIT/ApacheV2

**Comment by cmr** [comment]
@xanium4332 just leave a comment here.

**Comment by pix64** [comment]
I consent

**Comment by jpernst** [comment]
I can't remember what I contributed exactly or if it qualifies, but just in case, I consent to relicense my contributions under MIT and Apache 2.0.

**Comment by andrewrk** [comment]
I consented by using my collaborator rights to check my own box.

**Comment by Gekkio** [comment]
Didn't even remember I made any changes to this project :)

I consent.

**Comment by cybergeek94** [comment]
Checked my own box with collab perms.

**Comment by xanium4332** [comment]
I consent to relicensing my edits as MIT/Apache-2.0

**Comment by andersk** [comment]
I approve relicensing my contributions to dual MIT/Apache 2.0.

**Comment by orangea** [comment]
I consent

**Comment by mbrubeck** [comment]
I approve relicensing my contributions to dual MIT/Apache 2.0.

**Comment by hauleth** [comment]
Let it be.

**Comment by mprobinson** [comment]
I consent.

**Comment by XMPPwocky** [comment]
I consent.

**Comment by Ryman** [comment]
I consent.

**Comment by ruud-v-a** [comment]
I consent.

**Comment by gchp** [comment]
Fine with me!

**Comment by lfairy** [comment]
I consent!

**Comment by twoodford** [comment]
I consent to relicensing my edits as MIT/Apache v.2

**Comment by huonw** [comment]
I consent.

**Comment by TyOverby** [comment]
I consent to relicensing my edits as MIT/Apache v.2

**Comment by bpicolo** [comment]
Relicense is fine with me.

Also, seems it's about time someone invents a license with a better relicense clause

**Comment by m4rw3r** [comment]
I consent to relicensing my edits as MIT/Apache v.2

**Comment by tafia** [comment]
I consent

**Comment by lifthrasiir** [comment]
I'm fine with relicensing.

**Comment by bombless** [comment]
I approve relicensing my contributions to dual MIT/Apache 2.0.

**Comment by zsiciarz** [comment]
I consent to relicensing my contributions as MIT/Apache 2.0.

**Comment by toqueteos** [comment]
I consent.

**Comment by nwin** [comment]
I consent.

**Comment by theotherphil** [comment]
I consent

**Comment by froydnj** [comment]
I consent to relicensing my changes under an MIT/Apache-2.0 dual license.

**Comment by brookst** [comment]
I consent.

**Comment by b52** [comment]
I consent.

**Comment by cmr** [comment]
Pinging people due to github @-mention limit:

 @retep998
@PeterMozesMerl
@flying-sheep
@Blei
@rsaarelm
@SimonSapin
@sondrele
@stjahns
@lgvz
@Denommus
@bfops
@ahtn
@robo9k

**Comment by lucidd** [comment]
I consent to relicensing my contributions as MIT/Apache 2.0.

**Comment by retep998** [comment]
I am okay with this.

**Comment by PeterMozesMerl** [comment]
Sure, thank you for asking.

**Comment by sondrele** [comment]
I consent!

**Comment by bvssvni** [comment]
I approve dual licensing under MIT/Apache.

**Comment by bfops** [comment]
Sounds fine, I agree.

**Comment by rsaarelm** [comment]
I consent to relicensing my edits as MIT/Apache-2.0

**Comment by flying-sheep** [comment]
i consent

**Comment by robo9k** [comment]
I consented by using collaborator permissions to check my own box.

**Comment by pavlov-dmitry** [comment]
I consent.

**Comment by lgvz** [comment]
Fine with me.

**Comment by jdpage** [comment]
I approve relicensing my contributions to dual MIT/Apache 2.0.

**Comment by TyOverby** [comment]
I consent to relicensing my contributions as MIT/Apache 2.0.

**Comment by ollie** [comment]
Yes please. (I consent.)

**Comment by paulrouget** [comment]
I consent.

**Comment by leonkunert** [comment]
I consent

**Comment by Blei** [comment]
I consent to relicensing my edits as MIT/Apache-2.0

**Comment by Esption** [comment]
The relicensing is fine by me.

**Comment by Denommus** [comment]
I'm fine with it.

**Comment by AngryLawyer** [comment]
Yeah go for it

**Comment by stjahns** [comment]
I consent.

**Comment by indiv0** [comment]
I consent.

**Comment by SimonSapin** [comment]
I’m OK with this if the maintainers are.

**Comment by jdpage** [comment]
Any word on moving forward with this? There are still several people who haven't responded yet. Should someone try to contact them out-of-band (email?) and get their consent?

**Comment by bvssvni** [comment]
The biggest contributor that has not given consent yet is @ccgn.

**Comment by flying-sheep** [comment]
he starred something three weeks ago and didn’t do anything else on github within the last year

**Comment by ccgn** [comment]
Wow! Sorry for the late reply. I think this is a good idea.
I give my consent

**Comment by bvssvni** [comment]
Reminder:

@Potpourri @ahtn if you give consent, I think we're ready.

@maxsnew @dummer @Doom032 @burtonageo have made minor contributions, but would like to hear your input before making license changes.

**Comment by flying-sheep** [comment]
@ccgn sorry for stalking your public activity, on your github profile i just wanted to know if it’s realistic that you would respond.

**Comment by ccgn** [comment]
@flying-sheep its no problem i was just exclaiming that i missed this long thread for months

**Comment by dummer** [comment]
Sorry for the late reply. Yes, I consent to relicensing my edits as MIT/Apache-2.0.

**Comment by ahtn** [comment]
I consent

**Comment by nwin** [comment]
So actually we lost track of this one and accepted new merges in the mean time. Would it be feasible to add some kind of addition like: New contributions are accepted under MIT/Apache?

**Comment by bvssvni** [comment]
@Potpourri @ahtn Just a small reminder!

**Comment by maxsnew** [comment]
I consent

**Comment by Potpourri** [comment]
I consent.

**Comment by flying-sheep** [comment]
now only @Doom032 and @burtonageo are missing!

**Comment by Doom032** [comment]
I forgot I even contributed to this. I'd even argue that my commit was
trivial so my consent is not necessary. But I won't keep you up.

I consent to relicensing the source code to dual licensed MIT/Apache-2.0

**Comment by martinlindhe** [comment]
Now only consent from @burtonageo is missing

**Comment by philipc** [comment]
> get explicit approval from each contributor of copyrightable work (as not all contributions qualify for copyright)

I'd consider @burtonageo's [contribution](https://github.com/image-rs/image/commit/c97a5615525cc28f05344f7ac8617b5ad142a40c) to be mechanical enough that it doesn't need consent.

**Comment by fintelia** [comment]
Presumably we also need approval of everyone who contributed after this issue was created in 2016. (Notice for instance that my account isn't listed above...) Does anyone know how to get a list in an automated way?

Also, I consent.

**Comment by HeroicKatora** [comment]
The github api is a good starting point: <https://api.github.com/repos/image-rs/image/contributors>

**Comment by HeroicKatora** [comment]
Renewed list of contributors, not including those already mentioned in the first comment, since then:

- [ ] @abonander
- [ ] @AdnoC
- [ ] @adrianN
- [ ] @ahtn
- [ ] @anthonynguyen
- [ ] @artemkonenko
- [ ] @ArturKovacs
- [ ] @aschampion
- [ ] @atouchet
- [ ] @birktj
- [ ] @bluss
- [ ] @brettfo
- [ ] @calum
- [ ] @CensoredUsername
- [ ] @chills42
- [ ] @crazymykl
- [ ] @cuviper
- [ ] @cybergeek94
- [ ] @d-dorazio
- [ ] @dgulotta
- [ ] @Diggsey
- [ ] @donachys
- [ ] @Dummer
- [ ] @eddyb
- [ ] @edwin0cheng
- [ ] @Eijebong
- [ ] @ethanboxx
- [x] @fintelia
- [ ] @francesca64
- [ ] @HarryLovesCode
- [x] @HeroicKatora
- [ ] @i80and
- [ ] @ijks
- [ ] @Isan-Rivkin
- [ ] @jaysonsantos
- [ ] @jpernst
- [ ] @kaj
- [ ] @kaksmet
- [ ] @Kerollmops
- [ ] @khyperia
- [ ] @lazypassion
- [ ] @leoschwarz
- [ ] @locriani
- [ ] @lovebug356
- [ ] @lukors
- [ ] @lukpank
- [ ] @mandeep
- [ ] @Manishearth
- [ ] @martinlindhe
- [ ] @mathstuf
- [ ] @mdsteele
- [ ] @mgsloan
- [ ] @mr4x
- [ ] @Ms2ger
- [ ] @neosilky
- [ ] @nox
- [ ] @oli-obk
- [ ] @oyvindln
- [ ] @panicbit
- [ ] @pducks32
- [ ] @pedrocr
- [ ] @petr-tik
- [ ] @philipc
- [ ] @rap2hpoutre
- [ ] @red75prime
- [ ] @RedRoosterMobile
- [ ] @Robzz
- [ ] @ruuda
- [ ] @ruud-v-a
- [ ] @sameer
- [ ] @samphippen
- [ ] @shssoichiro
- [ ] @SirWaddles
- [ ] @srdqty
- [ ] @stevebob
- [ ] @sunjay
- [ ] @tatref
- [ ] @tbu-
- [ ] @teovoinea
- [ ] @TheEnigmaBlade
- [ ] @TheNeikos
- [ ] @tjklemz
- [ ] @vbarrielle
- [ ] @vickenty
- [ ] @vitvakatu
- [ ] @vvhh2002

**Comment by Eijebong** [comment]
Sure, I'm ok with this :)

**Comment by Diggsey** [comment]
I consent.

Might want to update the README and PR template so that you don't have to get permission from future contributions, or this list is going to just keep getting longer...

**Comment by birktj** [comment]
I consent.

**Comment by CensoredUsername** [comment]
I consent to relicensing my contributions under dual MIT/Apache-2.0

**Comment by Manishearth** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.


Yes, you should explicitly mention the above text in the issue itself, and use a `<details>` tag to hide the checkist in the initial issue. See https://github.com/rust-lang/rust-clippy/issues/3097 for an example of this being done clearly.

**Comment by brettfo** [comment]
I consent.

**Comment by panicbit** [comment]
I consent.

**Comment by cuviper** [comment]
I consent to relicensing my contributions as MIT/Apache 2.0.

**Comment by dgulotta** [comment]
I consent.

**Comment by abonander** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by Kerollmops** [comment]
I consent.

**Comment by leoschwarz** [comment]
I license past and future contributions to the image-rs/image project under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

I don't think my one commit I have made here is of sufficient individuality and originality to even be copyrightable.

**Comment by mandeep** [comment]
I consent to relicensing the source code to dual licensed MIT/Apache-2.0

**Comment by Isan-Rivkin** [comment]
I consent 👍

**Comment by HeroicKatora** [comment]
@leoschwarz Validating that for each individual contributor would have been far more work. Your contribution is appreciated either way, in your specific case I would certainly judge that it was with `(+30, -42)` on many examples. Sorry if the ping did was annoying.

**Comment by oyvindln** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by martinlindhe** [comment]
+1

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by eddyb** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by philipc** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by d-dorazio** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by edwin0cheng** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by kaksmet** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by adrianN** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by kaj** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by vbarrielle** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by khyperia** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by aschampion** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ijks** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ArturKovacs** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mathstuf** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by chills42** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by lukors** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by atouchet** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by francesca64** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by PeterMozesMerl** [comment]
Cheers

**Comment by fintelia** [comment]
Pinging additional people due to github @-mention limit:

@mdsteele
@mgsloan
@mr4x
@Ms2ger
@neosilky
@nox
@oli-obk
@pducks32
@pedrocr
@petr-tik
@rap2hpoutre
@red75prime
@RedRoosterMobile
@Robzz
@ruuda
@ruud-v-a
@sameer
@samphippen
@shssoichiro
@SirWaddles
@srdqty
@stevebob
@sunjay
@tatref
@tbu-
@teovoinea
@TheEnigmaBlade
@TheNeikos
@tjklemz
@vickenty
@vitvakatu
@vvhh2002

**Comment by sameer** [comment]
I consent.

**Comment by neosilky** [comment]
I consent.

**Comment by srdqty** [comment]
My commit was just a one-liner making an enum public, but I consent if it matters.

**Comment by HeroicKatora** [comment]
@fintelia That explains the extremely skewed distribution of answers towards the top of the original list :joy:

**Comment by vitvakatu** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by teovoinea** [comment]
I license past and future contributions to this repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by SirWaddles** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by nox** [comment]
I approve relicensing my contributions to dual MIT/Apache 2.0.

**Comment by Robzz** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

Funny thing is, I mostly just removed code to move it to image-tiff, so, there ain't much to license.

**Comment by lovebug356** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by tbu-** [comment]
I license my past contributions to this repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jaysonsantos** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Ms2ger** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by vickenty** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by oli-obk** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by TheNeikos** [comment]
I consent

**Comment by lukpank** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by rap2hpoutre** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mdsteele** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by stevebob** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by HeroicKatora** [comment]
Pinging remaining users after a week of unactivity.

Reminder: This is issue is opened to gather consent for relicensing this repo to MIT / Apache v2, the license used by most of the Rust ecosystem see the top comment for details.

To consent, reply with this text:

    I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Note**: I've tried to find the git name authorship for each one to allow us to judge if some one-line contribution are below copyright threshold in case of further inactivity, hopefully we can avoid that. (`git log --author="<name>" --all`). Names where I couldn't find any (also not in https://github.com/image-rs/image/graphs/contributors) are indicated with `???`. No matter if you find them, don't just publicly post their names or other personal information even though they are semi-public in the git commits.

@AdnoC
@anthonynguyen 
@bluss 
@ calum (contacted manually per mail due to inactivity)
@crazymykl
@donachys (`???`)
@ethanboxx
@HarryLovesCode
@lazypassion 
@locriani
@mgsloan
@mr4x
@pducks32 (`???`)
@petr-tik
@RedRoosterMobile
@ruuda
@shssoichiro
@TheEnigmaBlade
@tjklemz
@vvhh2002

**Comment by Isan-Rivkin** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option

**Comment by HeroicKatora** [comment]
@Isan-Rivkin [You had already consented](https://github.com/image-rs/image/issues/503#issuecomment-489457456) but this is clearer. Thanks :joy:

**Comment by calum** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by bluss** [comment]
I license past and future contributions [to this repository] under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by dbrenot-pelmorex** [comment]
@burtonageo looks like this is just waiting on you for approval

**Comment by shssoichiro** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mgsloan** [comment]
Not sure I need to, but

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by locriani** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by fintelia** [comment]
@arthmis are you OK with re-licensing your contributions? I think prior notifications may not have gone through due to a username change

---
I've checked the other remaining contributions by hand and they all seem to either be:
* extremely minor fixes (typos and the like), or
* code that has subsequently been heavily modified/removed (specifically the PRs by _anthonynguyen_ and _vvhh2002_)

**Comment by vvhh2002** [comment]
OK with me

**Comment by AdnoC** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

Sorry for not noticing this sooner.
