### ISSUE TITLE
Provide access to slice of pixels for images

### ISSUE THREAD

**Issue by kvark** [image-rs/image#509]
Currently, a dynamic image can be de-referrenced to `&[u8]`. This doesn't work well with strongly-typed texture initialization in GFX, where an `Rgba8` texture needs a slice to `[u8; 4]` for the input data. Here, `[u8; 4]` is the data type for the pixel data. It would be great if piston-image could provide this slice directly for our convenience. See https://github.com/gfx-rs/gfx/issues/851#issuecomment-175325566 for more info on GFX formats.

**Comment by nwin** [comment]
You mean you want to deref `DynamicImage` to `&[[u8; 4]]`? `&[u8]` is all we have. We could provide a `&[[u8; 4]]` if it is safe to cast `[T]` to `[[T; N]]` ∀ `T` to which not everybody seemed to agree last time we had it in this lib.

**Comment by kvark** [comment]
@nwin yes, that's what I want. Do you... really need `&[u8]` at all?

**Comment by nwin** [comment]
Well...yes. That is the format most people are using exchanging image data. As such the image buffer was specially designed to be baked by an array of primitives.

Beside that, there would be no reason why we would give a slice of arrays precedence over a slice of proper structs which would be more hairy to cast to an arrays of slices.

**Comment by kvark** [comment]
> Well...yes. That is the format most people are using exchanging image data.

"exchanging" is a bit broad here. What I see happening most of the time is people providing this data to the graphics API that uploads images to texture memory. And here comes the interesting point - the graphics API at the lowest level is still receiving `void *` (see [glTexImage2D](https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexImage2D.xml)), so the cast is imminent. Some better-typed rust libraries would accept something like `&[T]`, where T is pixel data type. If others decided to fixate on `&[u8]` - I don't see why this should be considered correct.

> Beside that, there would be no reason why we should give a slice of arrays precedence over a slice of proper structs which would be more hairy to cast to an arrays of slices.

That is arguable. Using simplest built-in types and then having either wraps around them or traits implemented for them has it's own advantages - look at the whole [vecmath](https://github.com/PistonDevelopers/vecmath) story. We may have different views over what the "proper struct" should be, while `[u8; 4]` is universally recognized.

**Comment by nwin** [comment]
I think we could spin circles discussing that.

In short:

A) The underlying storage will have to stay a array of primitives. One of many reasons: All image formats do so. 
B) I don't see any way of implementing that feature nicely until at least associated constants are stable. So I'll propose postponing this.

**Comment by kvark** [comment]
> The underlying storage will have to stay a array of primitives.

What do you mean by `primitive`? `u8`? Isn't `[u8; 4]` a primitive?

> All image formats do so.

That's not a strong argument. Perhaps, we could re-consider this?

> I don't see any way of implementing that feature nicely until at least associated constants are stable. 

Could you elaborate on how you'd use associated constants here?

**Comment by dobkeratops** [comment]
could it/does it do all 3 forms of access you might want..
```&[Pixel]``` , ```&[u8]```,  and ```unsafe.. *const c_void```  (the latter for plugging directly into raw C library bindings with minimum fuss)

One other thing I was going to inquire about is if the image buffer really is always going to be sequential packed pixel data ( might it ever be planar .. seperate r/g/b channels, or even bitplanes, or even indexed formats - or would all that be beyond the scope of this library. I realise indexed is hardly ever used these days).

**Comment by HeroicKatora** [comment]
The standard library now provides `impl<'a, T> TryFrom<&'a [T]> for &'a [T; 3]` etc. I'm fairly sure this is a suitable alternative to providing it directly.
