### ISSUE TITLE
Encoding animated GIF

### ISSUE THREAD

**Issue by tigranbs** [image-rs/image#520]
Hi, I'm trying to encode animated gif , but I can't find encode functionality with multiple Frames. <br/>
Is it possible to do ?

**Comment by nwin** [comment]
Not with `image` as it just provides a very general API. You would need to use `gif` directly.

**Comment by tigranbs** [comment]
Thanks for your response !
But how refer to GIF directly ?  do you know libs for Rust ?

**Comment by bvssvni** [comment]
@tigranbs See https://crates.io/crates/gif

**Comment by Undeterminant** [comment]
Is there a reason why the current `encode_frame` drops self? It seems like a remodelling of that function and the addition of a `finish` method would be good enough to allow multiple frames.

**Comment by bvssvni** [comment]
@Undeterminant Can you open up a new issue for this?

**Comment by nwin** [comment]
@Undeterminant: I guess `image::gif` shouldn’t be public. For format-specific things one should use the `gif` library directly.

**Comment by Undeterminant** [comment]
@bvssvni I was more proposing a solution to not being able to encode animated GIFs, although I wasn't aware that the `gif` module wasn't intended for general use. I ended up just using the `gif` crate directly regardless.

**Comment by birktj** [comment]
It seems like support for this was added in #773 so I will close this issue.
