### ISSUE TITLE
Don't use untrusted Deref/DerefMut traits for generic backends

### ISSUE THREAD

**Issue by bluss** [image-rs/image#529]
These traits are simply not reliable for "backend" generics, i.e. when you need to trust the implementor for some kind of temporal consistency (that the length they tell you about is consistent with what the slice the deref call returns the next time it's called and so on).

See also https://github.com/rust-lang/rust/issues/29701 and https://github.com/rust-lang/rust/issues/29701#issuecomment-154869996 for context.

**Comment by HeroicKatora** [comment]
I'm not aware of any unsafe usage anymore. All remaining usages might panic if the traits are not implemented as expected but that is within their right for such a contract violation.
