### ISSUE TITLE
Iterator types are hidden in the documentation

### ISSUE THREAD

**Issue by retep998** [image-rs/image#549]
While the iterator types are marked as `pub` (thereby bypassing the private in public checks in Rust), they are inside a module which is private, and are not re-exported into a public location. Therefore when viewing the documentation, I cannot view these iterator types, so it makes it somewhat difficult to figure out what the iterators output.

**Comment by nwin** [comment]
About which iterator types are you talking? Pixels and friends? They are not bypassing any checks. They are re-exported in lib.rs, that's a bug in rustdoc. Afaik that issue is already in the bugtracker.

**Comment by retep998** [comment]
Yes Pixels. And yes I now see that they are indeed re-exported, which means rustdoc is just being terrible as usual.

**Comment by nwin** [comment]
Just out of curiosity, what about http://www.piston.rs/image/image/struct.Pixels.html? It’s there…

**Comment by retep998** [comment]
But they're not linked on http://www.piston.rs/image/image/struct.ImageBuffer.html

**Comment by birktj** [comment]
Since this is a rustdoc bug and probably fixed by now, I will close this issue.
