### ISSUE TITLE
Add more documentation for InnerImageView (eg. SubImage) and InnerImage (eg. SubImageMut)

### ISSUE THREAD

**Issue by rsaarelm** [image-rs/image#558]
There's currently only one SubImage type which requires the parent image reference to be mutable. Creating a subimage of an immutable image isn't possible, despite this having obvious use cases. The standard Rust pattern of parallel mutable and immutable accessor types (eg. IterMut and Iter) could be used here. Rename current SubImage with the mutable access to the parent image to SubImageMut and add a new SubImage type that takes an immutable parent reference and only provides read access.

**Comment by nbigaouette-eai** [comment]
Totally supports this.

I was surprised to see `&mut` in `SubImage`'s [`new()` method](https://docs.rs/image/0.12.3/image/struct.SubImage.html#method.new) or in `GenericImage`'s [`sub_image()` method](http://www.piston.rs/image/image/trait.GenericImage.html#method.sub_image).

I associate a SubImage with a slice into a vector for example. It is possible to have a slice to a immutable vector so I though SubImage would work on immutable images too.

**Comment by rsaarelm** [comment]
The SubImage API seems to have changed recently. I haven't looked into it in more detail yet but maybe it resolves this issue and this can be closed?

**Comment by inferrna** [comment]
I was also confused with sub_image() method but then I found [view](https://docs.rs/image/0.21.0/image/trait.GenericImageView.html#method.view) method that returns [InnerImageView](https://docs.rs/image/0.21.0/image/trait.GenericImageView.html#associatedtype.InnerImageView) type. Unfortunately it not described in docs on https://piston.rs site.

**Comment by HeroicKatora** [comment]
This has been changed since the initial issue was opened. It might be appropriate to close this, or at least mark it as 'documentation missing'

**Comment by lovasoa** [comment]
I was ready to open a new issue when I stumbled upon it. The documentation is still missing...
