### ISSUE TITLE
16-bit grayscale pngs decoded as 8-bit

### ISSUE THREAD

**Issue by akonneker** [image-rs/image#560]
So I have a bunch of 16-bit pngs I need to decode, but the decoder is reading them as 8-bit. PNGDecoder reports the pixel type as Gray(8).

I had a similar issue with the c++ library I'm using now (lodePNG), but it has the option to enforce a particular pixel type and bit depth, which fixed the issue.

Is there a similar capability here, and if not, how difficult would it be to add?

I've attached a sample file.

![seq_depth00000](https://cloud.githubusercontent.com/assets/292768/16815718/f0dceb44-4908-11e6-9fd8-1d425db596bf.png)

**Comment by nwin** [comment]
Currently, there is poor support for 16 bit images, currently it just discards the lower bits. You would have to use the png crate directly.

```
extern crate png;
let mut decoder = png::Decoder::new(&*data);
decoder.set(png::TRANSFORM_IDENTITY);
let (info, mut decoder) = decoder.read_info().unwrap();
let mut image = vec![0; info.buffer_size()];
decoder.next_frame(&mut image)
```

**Comment by akonneker** [comment]
Your snippet seems to do the trick. Thanks!

Would it be straightforward to add the capability to return 16-bit png's from the image decoder, or are there assumptions of 8-bit-ness elsewhere that would need to be changed?
