### ISSUE TITLE
Resizing to the same size isn't no-op

### ISSUE THREAD

**Issue by wolfiestyle** [image-rs/image#564]
If you resize an image to it's same original size, it gets distorted/blurred by the filter, when it actually should do nothing.
Code used to reproduce the bug:

``` rust
extern crate image;

fn main()
{
    let orig = image::open("test.png").unwrap().to_rgba();
    let (width, height) = orig.dimensions();
    let resized = image::imageops::resize(&orig, width, height, image::FilterType::Lanczos3);
    resized.save("out.png").unwrap();
}
```

Used Lanczos only as an example, it does the same with the other filters.
Compiled with image v0.10.1 under Gentoo linux x86_64.

**Comment by stevebob** [comment]
I noticed the same problem with the `Nearest` filter and fixed it in: https://github.com/PistonDevelopers/image/pull/661
I just tried running the code you posted with my changes and it produces an output image that looks the same as the input.

**Comment by Mike-Neto** [comment]
I did just test this as well and was able to confirm this is fixed, the code now looks slightly different due to API changes in the mean time.

I tested using `src/imageops/sample.rs:tests::test_resize_same_size` as a basis so that the code was something like:

```rust
    fn test_resize_same_size_lanczos3() {
        use std::path::Path;
        let img = crate::open(&Path::new("./examples/fractal.png")).unwrap();
        let (width, height) = img.dimensions();
        let resized = img.resize(width, height, FilterType::Lanczos3);
        resized.save("./examples/fractal-out.png").unwrap();

        let saved_img = crate::open(&Path::new("./examples/fractal.png")).unwrap();
        assert!(img.pixels().eq(saved_img.pixels()))
    }
```

It seems this is fixed already just like @gridbugs mentioned 👍
