### ISSUE TITLE
No documentation for construction functions (Luma, Rgb..)

### ISSUE THREAD

**Issue by Ploppz** [image-rs/image#572]
Reading [this](https://github.com/PistonDevelopers/image#62-generating-fractals), I noticed `*pixel = image::Luma([i as u8]);`. 

The `Luma` function (and probably for other pixel types), isn't documented (or I can't find it). It should probably be documented.

**Comment by nwin** [comment]
Originally this was a 1-tuple, I wonder why this construct still works. Does anybody has an idea?

**Comment by philipc** [comment]
It's a function defined at https://github.com/PistonDevelopers/image/blob/bc8b8e5b34ab6b9c6caee7ba60a77451631411fc/src/color.rs#L68.

**Comment by nwin** [comment]
Seems like a bug in rustdoc then. The functions don't appear in the docs.

**Comment by nwin** [comment]
I created an issue #37342. The documentation actually exists but is not linked.

**Comment by birktj** [comment]
It seems like these functions do longer exists, so I am closing this issue.

**Comment by HeroicKatora** [comment]
Also, they are back to a 1-tuple again :)
