### ISSUE TITLE
Support guessing format when loading from file

### ISSUE THREAD

**Issue by joshtriplett** [image-rs/image#577]
`image::open` only uses the filename extension.  `image::load_from_memory` can guess the format based on magic numbers, but requires loading the image into memory first in a separate step.  Please consider adding a function to read an image from a file but guess the format based on magic numbers.

**Comment by nwin** [comment]
What would be the benefit of it? Content based type guessing is usually a bad idea if you have another type indication. The internet explorer was quite good at it by parsing files as “text/html” which where explicitly send as “text/plain”.

**Comment by nabijaczleweli** [comment]
Which internet explorer?

**Comment by nwin** [comment]
Haven't tested that in a while. I can confirm IE6.

**Comment by nabijaczleweli** [comment]
Oh, you mean IE, not some random internet explorer.

**Comment by nabijaczleweli** [comment]
As for "What's the benefit of it" -- simplicity of use. No longer woild one have to do [this](https://github.com/nabijaczleweli/termimage/blob/51f2378c4d4d9d8bedcd36cb6d5266c1f4f94078/src/ops/mod.rs#L51-L86):

```rust
pub fn guess_format(file: &(String, PathBuf)) -> Result<ImageFormat, Outcome> {
    file.1
        .extension()
        .and_then(|ext| match &ext.to_str().unwrap().to_lowercase()[..] {
            "png" => Some(Ok(ImageFormat::PNG)),
            "jpg" | "jpeg" | "jpe" | "jif" | "jfif" | "jfi" => Some(Ok(ImageFormat::JPEG)),
            "gif" => Some(Ok(ImageFormat::GIF)),
            "webp" => Some(Ok(ImageFormat::WEBP)),
            "ppm" => Some(Ok(ImageFormat::PPM)),
            "tiff" | "tif" => Some(Ok(ImageFormat::TIFF)),
            "tga" => Some(Ok(ImageFormat::TGA)),
            "bmp" | "dib" => Some(Ok(ImageFormat::BMP)),
            "ico" => Some(Ok(ImageFormat::ICO)),
            "hdr" => Some(Ok(ImageFormat::HDR)),
            _ => None,
        })
        .unwrap_or_else(|| {
            let mut buf = [0; 32];
            let read = try!(File::open(&file.1).map_err(|_| Outcome::OpeningImageFailed(file.0.clone()))).read(&mut buf).unwrap();
            let buf = &buf[..read];

            if buf.len() >= PNG_MAGIC.len() && &buf[..PNG_MAGIC.len()] == PNG_MAGIC {
                Ok(ImageFormat::PNG)
            } else if buf.len() >= JPEG_MAGIC.len() && &buf[..JPEG_MAGIC.len()] == JPEG_MAGIC {
                Ok(ImageFormat::JPEG)
            } else if buf.len() >= GIF_MAGIC.len() && &buf[..GIF_MAGIC.len()] == GIF_MAGIC {
                Ok(ImageFormat::GIF)
            } else if buf.len() >= BMP_MAGIC.len() && &buf[..BMP_MAGIC.len()] == BMP_MAGIC {
                Ok(ImageFormat::BMP)
            } else if buf.len() >= ICO_MAGIC.len() && &buf[..ICO_MAGIC.len()] == ICO_MAGIC {
                Ok(ImageFormat::ICO)
            } else {
                Err(Outcome::GuessingFormatFailed(file.0.clone()))
            }
        })
}
```

To guess image format from either the extension or from the magic (and the magic tests are not as great as I'd like them to be, but eh, simplicity), but rather let `image` handle that (since it already supports both, just not at once).

**Comment by nwin** [comment]
Let me ask differently, what is the use case? How many image files w/o file extension are there? I don’t want to put too much “intelligence” in to a single function. Currently there is only one way for each data source which is fine. Personally, I consider an image file without extension either to be broken or to be application specific. In the latter case you do not have to guess.

**Comment by nabijaczleweli** [comment]
Fixed functions ex definitione don't have intelligence, so you don't have to worry about that.

**Comment by joshtriplett** [comment]
On Thu, Sep 15, 2016 at 10:51:34PM -0700, nwin wrote:
> What would be the benefit of it? Content based type guessing is usually a bad idea if you have another type indication. The internet explorer was quite good at it by parsing files as “text/html” which where explicitly send as “text/plain”.

The web doesn't rely on file extensions, though; it relies on MIME
types.  And I agree that you shouldn't guess based on content if you
have a MIME type, or if you have a file extension.  But if you don't
have either of those, then I'd like to have a function that can check
magic values rather than give up.

As a random example of files without identifying extensions, Linux
avatars live in ~/.face (not ~/.face.jpg or similar).

I've seen various instances of open-coded handling for this wrapped
around the image crate.

**Comment by icefoxen** [comment]
I have a use case: I want to be able to write a library that loads images from files without knowing ahead of time what they are.

We can guess based off the file name, or we can make a much more reliable guess based on the file contents.  I know which I'd prefer.

**Comment by jtojnar** [comment]
I just wanted to try [fireplace](https://github.com/Drakulix/fireplace), which uses this crate for loading background images. Now, I have `~/.config/bg/current` symlinked to my background of choice so that I can use it across WMs. And since the background image can sometimes be a JPEG but very often it is a PNG, the symlink does not have an extension.

**Comment by birktj** [comment]
I think we should properly consider this. As far as I understand magic bytes is the standard way to detect file types on at least Linux. I think an api where we can pass any `Read` implementation and then select the right decoder based on magic bytes would be nice.

**Comment by martinlindhe** [comment]
Having a look at this now
