### ISSUE TITLE
Downsizing and upsizing an image leaves a weird border

### ISSUE THREAD

**Issue by darklajid** [image-rs/image#592]
So, there are a couple utilities that use resize() to downsize/upsize and get a blurred pixelated look - think 'protect the content'.

I tried implementing something like that in rust, using this library. Unfortunately the behaviour here seems unexpected.

```
extern crate image;

use std::path::Path;

fn main() {
  let img = image::open(&Path::new("input.png")).unwrap();
  let imgbuf = img.to_rgba();
  let pixel_size = 9;
  let blurred = img.
  	resize(imgbuf.width() / pixel_size, imgbuf.height() / pixel_size, image::FilterType::Nearest).
	resize_exact(imgbuf.width(), imgbuf.height(), image::FilterType::Nearest);

  blurred.to_rgba().save(&Path::new("output.png"));
}
```

Samples attached - a simple screenshot is my input

![input](https://cloud.githubusercontent.com/assets/77554/20230491/a15eca5c-a85c-11e6-97d0-df3d6708676f.png)

I get a weird border in the resulting image

![output](https://cloud.githubusercontent.com/assets/77554/20230513/b7ab7012-a85c-11e6-84f0-94fec0121bee.png)

What am I doing wrong? I try to simulate something similar to
`convert input.png -resize 10% -resize 1000% output_convert.png`

which results in 

![output_convert](https://cloud.githubusercontent.com/assets/77554/20230611/28771486-a85d-11e6-8bf1-1c51ed8bccf0.png)

**Comment by darklajid** [comment]
Great. The issue is hard to impossible to notice in FF for me, given the uploads. If you download the PNG files you'll notice (according to eog, pinta, krita etc..) that the image I'm complaining about, the one created using this library, has a transparent border on the right and bottom side. I'd expect this image to be totally opaque.

**Comment by stevebob** [comment]
Hi. Regarding the transparent border on the right and bottom side, I've noticed the same behaviour and just opened a PR to fix it (and some other artefacts): https://github.com/PistonDevelopers/image/pull/661

**Comment by Shnatsel** [comment]
The associated PR is merged, so I assume this can be closed?
