### ISSUE TITLE
Detach decoders/encoders into its own crate

### ISSUE THREAD

**Issue by kosinix** [image-rs/image#607]
Is it possible to place the decoders/encoders into their own separate crates? Similar to png, gif, and jpeg-decoder crates. This will make low level stuff with certain formats possible. For example, animated GIF can be created using the gif crate directly, since piston/image does not yet support it. This will also make piston/image more modular. Third party-crates can also use the encoders/decoders without the need to include the entire piston/image crate.

**Comment by HeroicKatora** [comment]
It was done for those requested. Others will/have followed. Closing this in particular.
