### ISSUE TITLE
Detach filters into their own crate (imageproc)

### ISSUE THREAD

**Issue by ideasman42** [image-rs/image#608]
Image loading is quite well defined for common formats but filters have a very broad scope which approaches filters for graphics and compositing applications, computer-vision, image analysis (see OpenCV).

Its such a large field that it would be better to be split into its own crate so users who only need to load and save images can just depend on the image IO part of this crate.

Since many common image filters have well known implementations, its possible developers will port filters from other software (OpenToonz or LightZone for eg).

Currently 3 of the 8 PR's relate to image manipulation ( #588 #587 #504 ),

These could be moved into: https://github.com/PistonDevelopers/imageproc

**Comment by pix64** [comment]
Shouldn't these be put under https://github.com/PistonDevelopers/imageproc?

**Comment by ideasman42** [comment]
Wasn't aware of this, updated issue.

**Comment by birktj** [comment]
This issue seems mostly resolved so I am closing it for now.
