### ISSUE TITLE
Efficient way to blank an ImageBuffer/DynamicImage?

### ISSUE THREAD

**Issue by RandomInsano** [image-rs/image#616]
It's surprisingly difficult to figure out how to blank an image (I've been at it for two hours). There are no examples save the Fractals example (I've repurposed that), and I *think* there's a constructor for an ImageBuffer somewhere that lets you initialize a buffer with a particular colour set.

Is there a reason why you can't blank out an existing ImageBuffer? I'd imagine it could be a pretty quick operation to set a pattern in memory that could live inside ImageBuffer and bubble up to all DynamicImage implementations.

**Comment by HeroicKatora** [comment]
This has been a while but let's answer it. One efficient way is to utilize a `flat::View` as the source buffer for `GenericImage::copy_from`:

```
use image::{GenericImage, Rgb, RgbImage};
use image::flat::{FlatSamples, SampleLayout};

let white_buffer = FlatSamples {
   samples: &[0xff],
   layout: SampleLayout {
       channels: 3,
       channel_stride: 0,
       width: 100,
       width_stride: 0,
       height: 100,
       height_stride: 0,
   },
   color_hint: None,
};


let bg = white_buffer.as_view::<Rgb<u8>>.unwrap();
let mut buffer = RgbImage::new(100, 100);
buffer.copy_from(&bg, 0, 0);
```

[play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=940463a4d14c695e05261033d23af296).

Agree that it is pretty hard to discover this pattern and not very ergonomic as well. So keeping it open.

**Comment by RandomInsano** [comment]
Looks good to me! I'm fine to close this one if you are. Thanks!

**Comment by HeroicKatora** [comment]
Somewhat incidentally I was working on a small helper for this in the last week :smiley:
