### ISSUE TITLE
Support for DDS?

### ISSUE THREAD

**Issue by StelarCF** [image-rs/image#621]
Currently it's not supported and is a fairly common format for storing textures.

**Comment by dobkeratops** [comment]
+1, hugely important for 3d

**Comment by benoitryder** [comment]
I've implemented partial support of DDS, based on the DXT decoder implementation. (Basically, it parses the DDS header and creates a DXT decoder using parameters from the DDS header.) Therefore, only DDS files using DXT1, DXT3 or DXT5 are supported.
Should I open a PR with that, even if it is a limited support?

**Comment by HeroicKatora** [comment]
Yes, there are a few other formats with only partial support and some success with incrementally improving them to full support.

**Comment by Kanabenki** [comment]
This has been closed but the crate currently doesn't support most DDS texture formats, should this be reopened?

**Comment by fintelia** [comment]
No, it would be better to create separate issues for specific formats / groups of formats. Though TBH the main bottleneck is someone coming along interested in implementing more formats so having the issues won't do a ton on their own
