### ISSUE TITLE
No header sanity checking in ICODecoder

### ISSUE THREAD

**Issue by nagisa** [image-rs/image#624]
Following base64-encoded ico makes the decoder cause a OOM condition:

```
AAABAAEAIP//////////EAAAFgAAACgAAABAAAAgEAAAAAEAAQAAAAAAAAAAAAEAAAEAAAAAAAAA
AAAAAAAAAAAB//////8A
```

This is what `file` says: MS Windows icon resource - 1 icon, 32x255, 255 colors, 65535 planes, 65535 bits/pixel

Both GIMP and eog handled the file fine by figuring out the file is invalid.

**Comment by birktj** [comment]
I am closing this as it should have been addressed in #632.
