### ISSUE TITLE
Serde support

### ISSUE THREAD

**Issue by nbigaouette-eai** [image-rs/image#643]
I have `struct` containing a `ImageBuffer<Rgb<u8>, Vec<u8>>` which needs to be serialized and deserialized using serde.

Could support for serde be added to this crate? Is that feasible?

**Comment by birktj** [comment]
I am going to close this for now. Generic de/serialization of imagebuffers doesn't really make sense, what would be the right way? Using `#[serde(deserialize_with = "path")]` and `#[serde(serialize_with = "path")]` makes more sense as the ones using the de/serialization can select the way best suited for them.

More discussion about this can be done in #741.
