### ISSUE TITLE
Issue with guessing format of WEBP images

### ISSUE THREAD

**Issue by joek13** [image-rs/image#660]
Presently, using `image::load_from_memory` will make an attempt to guess the image's format using magic numbers at the beginning of the image's bytes. WebP's magic bytes are defined here:

```
static MAGIC_BYTES: [(&'static [u8], ImageFormat); 11] = [
    //omitted other definitions
    (b"WEBP", ImageFormat::WEBP),
    //omitted other definitions

];
```
This would cause any byte sequence starting with the bytes for "WEBP" to be recognized as WebP images; however, WebP images do not actually begin with the ASCII bytes "WEBP", but instead, their file header looks like this:
```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|      'R'      |      'I'      |      'F'      |      'F'      |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           File Size                           |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|      'W'      |      'E'      |      'B'      |      'P'      |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
(taken from the [WebP Container Specification](https://developers.google.com/speed/webp/docs/riff_container#riff_file_format))
Because of this, WEBP images' bytes are not properly recognized by `load_from_memory`.

**Comment by mraof** [comment]
Could this be fixed, at least for now, by just changing it from "WEBP" to "RIFF"?

**Comment by joek13** [comment]
@mraof 
Perhaps, but the RIFF container is generic -- not specific to WebP. A file with a RIFF header could be any one of [these](https://en.wikipedia.org/wiki/Resource_Interchange_File_Format#Some_common_RIFF_file_types) formats.

**Comment by mraof** [comment]
That's true, but right now this crate only supports WebP anyways, and the other image formats that use RIFF seem pretty low priority
Regardless, detecting that it's a RIFF container seems like the first step for detecting if it's any of these formats to me
