### ISSUE TITLE
General support for 16bit color components

### ISSUE THREAD

**Issue by fungos** [image-rs/image#665]
One major feature missing from this crate is the general support for 16 bits color components.
Before going forward with new Encoder/Decoder I believe this should be solved. I would try to tackle this, but seems a bit more of design issue, so maybe someone more experienced with Rust would be needed.

Relates to #426, #559 and #560.

**Comment by rennis250** [comment]
What is this status on this? What is required to finish this?

**Comment by polarathene** [comment]
+1 I'd like to process 16-bit PNGs(specifically greyscale).

**Comment by BartMassey** [comment]
Yes. I would like to generate 16bit grayscale images.

**Comment by SolarLiner** [comment]
Any progress on this? I also would like to generate 16-bit PNG images.

**Comment by polarathene** [comment]
There appears to be in this issues history/timeline directly above your comment, is a commit from what is presumably a fork(and perhaps a PR) addressing it?:

> Support 16 bit per channel image buffers
> Add 16 bit buffers for all 16 bit types in ColorType. Include these as supported types in DynamicImage. These 16 bit images are currently only supported with u16 representation; changing this would require specialization and macroing of color conversions.
>
> Load 16 bit PNGs at full bit depth rather than squashing to 8 bit.

Found the [relevant PR here](https://github.com/image-rs/image/pull/1085). So once that's passed review cycle and been merged, just have to wait until the next release with it is made :)
