### ISSUE TITLE
Panic on GIF encoding

### ISSUE THREAD

**Issue by BenWiederhake** [image-rs/image#676]
The README say that [GIF encoding is supported](https://github.com/PistonDevelopers/image#21-supported-image-formats).  The README provides a simple example [how to write a file](https://github.com/PistonDevelopers/image#63-writing-raw-buffers).

However, combining these two fails [playground](https://play.rust-lang.org/?gist=b49af987cc891679b0f0403f09dba6ff&version=nightly):
```Rust
extern crate image;
use std::path::Path;
fn main() {
    let buffer: &[u8] = &[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120];
    match image::save_buffer(&Path::new("image.gif"), buffer, 2, 2, image::RGB(8)) {
        Ok(()) => { println!("All is good"); },
        Err(e) => { println!("Sad panda: {:?}", e); },
    };
}
```

Output:
```
Sad panda: Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("Unsupported image format image/\"gif\"") }) }
```

This problem also appears with the configurations:
- 320×240 Gray
- 320×240 RGB
- 3×3 Gray

The other GIF-related bugs seem to be unrelated.

**Comment by nwin** [comment]
Yes, seems like it was simply forgotten in`save_buffer`.

**Comment by HeroicKatora** [comment]
This now prints `All is good` since `0.22.4`.
