### ISSUE TITLE
JPEG/PNG Encode/Decode and Resize Performance

### ISSUE THREAD

**Issue by mirosval** [image-rs/image#688]
I'm exploring the idea of very fast manipulation with images in common formats (JPEG and PNG) I have looked around, but there are only two "fast" libraries for JPEG (libjpeg-turbo and libvips, both in C). 

Now, from what I could find, the "problem" with Rust achieving comparable performance to these libs is that it does not have good SIMD support to make current image encoders/decoders faster. My thinking is that by using something like OpenCL (Rust [OCL](https://github.com/cogciprocate/ocl)) it should be possible to side step the issue.

I have a very specific use case in mind, I want to be able to decode, resize, encode images as fast as possible on an AWS cluster.

I understand that pulling a dependency like OCL can be controversial, so I thought I'd ask if this is something remotely acceptable in this project. 

I would of course first have to set up some rigorous performance testing benchmark to compare this against the other existing libraries.

**Comment by bvssvni** [comment]
I think some people might find a fork of this library useful with OpenCL support. If it works out well, then perhaps it could be added under a feature flag.

Rust doesn't have SIMD support yet, but LLVM is capable of doing auto-vectorization in some cases. It would be interesting to see how this library performs compared to other libraries.

**Comment by Restioson** [comment]
Just a note that you *can* use simd in rust right now. The faster crate provides nice bindings: https://github.com/AdamNiederer/faster

**Comment by fintelia** [comment]
There's been many performance improvements to the JPEG and PNG codecs since this issue was created. Please create new issues (or PRs!) if there's specific optimizations you want to suggest
