### ISSUE TITLE
ImageBuffer should also derive Hash, PartialEq and Eq

### ISSUE THREAD

**Issue by yoanlcq** [image-rs/image#697]
Greetings,

Title says it all - I think this would be convenient for APIs that expose structs which happen to contain an `ImageBuffer` (as is the case for me).
Since it is a slight, non-breaking change, I didn't bother to do a PR - but it might also be an opportunity to dicuss this for other structs such as `Frame`.

**Comment by HeroicKatora** [comment]
This was fixed in #1248.
