### ISSUE TITLE
few questions ..

### ISSUE THREAD

**Issue by dobkeratops** [image-rs/image#702]
so the image library deals with RGB,RGBA predominantly , fair enough,

would it be possible to use generics/etc to generalise the number of channels 1,2,3,4, and even more, and just happen to have inbuilt accessor names for the RGB,RGBA cases. i.e. having one type with a query ('num_channels()') , i.e. you can view the data as being a 3D array that happens to be width x height x channels (x channel data type).  In some other recent experiments I was sort of wanting to settle on a **4D array** i.e.   ```TextureArraySlices x Width x Height x Channels``` and it just happens to be the case that 'TextureArraySlices' is usually 1 (that could also be volume-texture slices). 

The channel datatype (u8) by default could be further parameterised (EDIT: I see it's already a typeparamter, that's great https://docs.rs/image/0.18.0/image/struct.Rgb.html):  a wrapped u8 mapping 0-255 to 0.0-1.0, an offset signed version (-1.0 -> 1.0, 128=zero) which is sometimes used in image processing, 16bit fixed point, and of course chucking in floats and float16 for HDR.   something like this..

     struct Image<Component=UnsignedGrayscale8>{}  
     impl  ..  {  fn num_channels(&self)->u32, fn width(&self)->u32, fn height(&self)->u32, fn layers(&self)->u32 /*layers=array texture images/volume texture dimension etc*/;  fn size4d(&self)->(u32,u32,u32,u32) }

use cases: images with *selection masks* embedded, CG images with multiple channels embedded (*specular*, *normals* etc), [volume-textures](https://msdn.microsoft.com/en-us/library/windows/desktop/bb206344(v=vs.85).aspx), and using image functionality to deal with the intermediate data in AI-conv-net [feature-maps](https://devblogs.nvidia.com/parallelforall/deep-learning-nutshell-core-concepts/) etc.

[Array Textures](https://www.khronos.org/opengl/wiki/Array_Texture) do imply something different to 'arrays of textures', i.e. each image must be the same size.

I think it's easy enough for code expecting to deal with 3/4 channels predominantly to match on the channel count and pick a hard-coded path rather than have the channel count as a variable as in the general case, so I wouldn't worry about any efficiency loss

I realise that this picture (3d/4d array) might fall apart a bit if you want to take it in another direction, packed pixels (e.g. supporting 565, 1555, 4444 buffers through the same interfaces).  There's also weird formats in existence like [7e3](https://wikivisually.com/wiki/7e3) , [RGBE](https://en.wikipedia.org/wiki/RGBE_image_format) etc..

perhaps I'd be better off making another crate that looks how I describe and just pulls in the decoders/encoders from here (or it could have the structure I describe and provide accessors to the slices as 'images' ? ) .. I haven't looked into the internals here in detail but I'm guessing it needs the image interface for the encoders/decoders to work consistently.

I realise this crate has a core mission which is to handle jpgs/pngs etc and it does that, so maybe what I describe here is better off somewhere else... on the other hand I see some image-_processing_ functionality here.  Again might there be scope for a split?

     Image (simplest common interface)
       ImageFormats
       ImageProcessing

or if anyone else likes any of these ideas, could a rolling refactor be done, e.g. create a ```Image4dArray``` _trait_ that works as above, impl'd for the existing Image (always returning layers()==1, channels()==1/3/4 when impl'd for the existing image) .. the encoders could be moved over to it then it would generalise to multi-layer/multi-channel/volume images

**Comment by birktj** [comment]
I am going to close this for now as this hasn't seen any activity and I don't really understand what is asked/suggested. If somebody still is interested in this they should create a new issue with a clear proposal for what they are looking for.
