### ISSUE TITLE
emscipten/asmjs , jpg crashes? (multithreading?)

### ISSUE THREAD

**Issue by dobkeratops** [image-rs/image#703]
I haven't tried this myself yet but I hear that jpg decoding doesn't run under emscipten, and it is down to requiring threading (presumably it does some fancy multicore decoding, awesome) .. would there be an appetite to make threading optional (cfg(..)) .. I think asmjs/etc  is a hugely important use case (it's what got me back into rust in the past couple of weeks, the idea of settling on it as a client and server language))

**Comment by fintelia** [comment]
The rayon crate should fallback to a single-threaded version on WASM, so I believe this is resolved
