### ISSUE TITLE
Make rayon dependency optional

### ISSUE THREAD

**Issue by Diggsey** [image-rs/image#723]
Rayon is a default feature of `jpg_decoder` - this feature should be propagated to the `image` crate such that it can be used on platforms without threading support.

**Comment by dobkeratops** [comment]
(nice idea, i do seem to remember running into some friction somewhere)

**Comment by Diggsey** [comment]
(Implemented in #724)

**Comment by birktj** [comment]
Closing this since it has been fixed.
