### ISSUE TITLE
Problem choosing first issue

### ISSUE THREAD

**Issue by gasabr** [image-rs/image#726]
I would like to contribute to the crate, but can't pick the first issue for myself: tried to search by the `easy` tag and some issues look like implemented, but not merged #581 , for some of them it's not clear are they relevant for the project or not #455, for some, I can not understand what is going on with the implementation #451.

Please, help me to pick the question for the first contribution:)

**Comment by martinlindhe** [comment]
I think a good starting place is too filter open issues by label "easy":
https://github.com/image-rs/image/issues?q=is%3Aissue+is%3Aopen+label%3Aeasy

Also, we may become better at labeling easy tasks as such ;-)
