### ISSUE TITLE
Travis runs tests only with `nightly`

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image#765]
Shouldn't we run all tests for both compiler versions to have baseline in case of nightly-breakage?

https://github.com/PistonDevelopers/image/blob/7530f5fd5541752fb66e2ceb96552191fb3d591b/.travis.yml#L28

**Comment by mandeep** [comment]
Any update on this? Looks like tests pass on stable so I think having cargo test on all three compiler versions would be a good idea.

**Comment by HeroicKatora** [comment]
Was fixed with #1048
