### ISSUE TITLE
Support ARGB ColorType

### ISSUE THREAD

**Issue by prasannavl** [image-rs/image#820]
Currently, there's no support for ARGB32. Cairo/Skia supports this, and is also often the format that X is going to return it's visuals in (for instance from xcb_get_image/shm_get, or xlib XGetImage, etc. 

Would be extremely helpful to have support for it. 

PS: Having conversions functions would be a good starting point, so that they can alteast be imported in, at a one time cost.

**Comment by nox** [comment]
I also filed https://github.com/PistonDevelopers/image-png/issues/86.
