### ISSUE TITLE
Png encoder treats BGRA as RGBA

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image#826]
The current encoder will encode BGRA without returning an `Err` but will wrongfully treat it was RGBA instead. Relevant line of code:

https://github.com/PistonDevelopers/image/blob/3a61c016572e8642dffb06e65affd3216ffd8796/src/png.rs#L134

Expected behaviour: Trying to encode an image with that color type should return an error instead.

Behaviour is more confusing for `DynamicImage` as a special code path will ensure that the subpixels will be swapped into `rgba` order but the `ColorType` will be indicated as `ColorType::Bgra` to the encoder.

**Comment by BourgondAries** [comment]
Just hit this in my code, any reason this should return an error? Is it not allowed according to the PNG spec?

**Comment by HeroicKatora** [comment]
The format of png only indicates [one type of rgb](http://www.libpng.org/pub/png/spec/iso/index-object.html#6Colour-values) and can not support other color channel orders. There's actually three options here:

* Return an `Err` to indicate that one needs to manually correct the sample order first
* Correctly implement the code path to automatically reorder the samples.
* Implement the reordering within `png` so that one can reorder the sample on-the-fly

But currently, afaik it will silently treat the blue pixel as the red one etc. For a work-around, one can call [`to_rgba`](https://docs.rs/image/0.21.0/image/enum.DynamicImage.html#method.to_rgba) before storing the image although it creates a copy.

**Comment by BourgondAries** [comment]
How do other programs know if it's RGBA or BGRA? Is RGBA default by convention?

**Comment by HeroicKatora** [comment]
Any loaded `png` gets you an image with `rgba` type. The `png` format just strictly assigns the color channels to specific bytes and does not allow specifying the channel assignment arbitrarily. Thus any program processing `png` knows the semantic meaning of the encoded data.

Then difference between `rgba` and `bgra` is entirely the memory order of the *decoded* data, which is mostly independent of the image format. It is important for decoded images, since you generally want to interpret its data as a slice of color component values (called *samples*) which is exactly how `ImageBuffer` stores them (simply in a `Vec` by default). This is a linear layout, so you need to know if the 0th index represents the red channel of the first pixel, or if it represents the blue one. But for an image encoding/format typically abstracts over this and specifies instead one specific encoding (e.g. take the byte value for red, followed by the byte value for blue, ...) or specifies some mathematical encoding function taking the encoded channel values as inputs (e.g. [yuv420p](https://en.wikipedia.org/wiki/YUV)).

That's not quite all there is to it, because the channel values are themselves an encoding of actual physical color, where the encoding is called a color space. But mostly you are fine interpreting an encoded 8-bit rgb value within the `sRGB` color space because that's what most tech uses by default.

**Comment by hrydgard** [comment]
Also hit this. If you specify a color order that can not be recorded, image should either return an error or reorder the samples for you - silently saving in the wrong order is ridiculous!
