### ISSUE TITLE
Would it be possible to use rayon to add parallel iterators over the image pixels or add multithreading from scratch? 

### ISSUE THREAD

**Issue by arthmis** [image-rs/image#832]
Would adding multi-threading or parallel iterators to access pixels be feasible? Is it potentially planned for the future?

**Comment by jjhbw** [comment]
I wondered about this too. AFAIK, iterating over pixels in parallel currently requires ugly code (uglier than a Rayon iterator, at least).

**Comment by lazypassion** [comment]
Is it necessary to add multi-threading? I was thinking about how it would benefit the imageproc crate, at least on large images, but maybe it would be better handled by the GPU.

**Comment by zzwxh** [comment]
i created this https://github.com/zzwxh/parallel_image/blob/main/src/lib.rs

**Comment by fintelia** [comment]
Fixed in https://github.com/image-rs/image/pull/2058
