### ISSUE TITLE
Support for saving to memory needs better documention or consistent api

### ISSUE THREAD

**Issue by Timmmm** [image-rs/image#834]
Currently the only way to write a PNG image is to save it to a file. It would be nice if there was an API that took a `std::io::Write` (or `std::io::Write + std::io::Seek`) for cases when you want an in-memory image.

My use case is writing an SVG with an embedded image. I need to encode to PNG, then base64-encode the result and *then* write to disk.

**Comment by HeroicKatora** [comment]
This is possible with a [`DynamicImage`](https://docs.rs/image/0.20.1/image/enum.DynamicImage.html#method.write_to) or by using the [`png` encoder interface](https://docs.rs/image/0.20.1/image/png/struct.PNGEncoder.html) directly. `DynamicImage` is a public enum of different `ImageBuffer` variants. But the api could be more consistent.

**Comment by Timmmm** [comment]
Ah yeah that works - probably sufficient to mention those in the `ImageBuffer::save()` API docs for now.

**Comment by SaiintBrisson** [comment]
@HeroicKatora I think you may close this issue now.
