### ISSUE TITLE
Associated constants would make the API more idiomatic

### ISSUE THREAD

**Issue by ids1024** [image-rs/image#835]
Now that [this feature](https://rust-lang-nursery.github.io/edition-guide/rust-2018/trait-system/associated-constants.html) is available, it is a better option.

I'm looking specifically at the `Pixel` trait, but this probably applies in other places too.

Currently, the trait is like this:

```rust
pub trait Pixel: Copy + Clone {
    type Subpixel: Primitive;
    fn channel_count() -> u8;
    fn color_model() -> &'static str;
    fn color_type() -> ColorType;
    // etc.
}
```

With associated consts:

```rust
pub trait Pixel: Copy + Clone {
    type Subpixel: Primitive;
    const CHANNEL_COUNT: u8;
    const COLOR_MODEL: &'static str;
    const COLOR_TYPE: ColorType;
    // etc.
}
```

This would be a breaking API change. Keeping the methods, deprecated, as part of the trait definition (with an implementation returning the constant) would prevent breaking code using the trait, but not implementing it (I don't know how common it is in practice to implement traits like this outside the crate).

Practically speaking, this has the advantage of allowing the value to be used in constant contexts, which could be useful. Making the methods `const fn`s should do that too, but apparently `const fn`s can't be part of a trait definition, and are still an unstable feature.

I don't know if this is worth the potential API breakage, but it's at least something to keep in mind for any future API redesign.

**Comment by lazypassion** [comment]
I would like to do this. Is it fine that it's a breaking change? I think you wanted to maintain some semblance of compatibility with older versions of rustc.

**Comment by birktj** [comment]
I think since we need quite a lot of api breakage before 1.0, we should just go ahead and do it since it will lead to a nicer api. Associated constants have been stable since `rustc` 1.20 so that should not be a problem.
