### ISSUE TITLE
[Feature] Select compression algorithm for png encoding. 

### ISSUE THREAD

**Issue by JackMordaunt** [image-rs/image#849]
I had a look through the code (`image` and `image-png` crates) and it _seems_ that the png encoder is hard-coded to use [`deflate::Compression::Fast`](https://github.com/PistonDevelopers/image-png/blob/5f15a33e1b3865262d2be14dad59d05217a76e4d/src/encoder.rs#L130). 

This is frustrating since I'm comparing output between two identical programs, one in Go and one in Rust. The png encoding from Go (stdlib encoder) produces 300kb for an 8 bit RGBA image and from Rust (via this crate and therefore [image-png](https://github.com/pistondevelopers/image-png)) produces a 1MB image for the same input (bit depth, color channels and resolution are all identical). 

This leads me to believe the difference in  size is due to the compression algorithm used. 

While I understand the issue starts with [image-png](https://github.com/pistondevelopers/image-png)'s api, I would benefit from being able to specify the compression algorithm from this crate's api. 

So 2 things:
1. Am I missing something? Can this already be done? 
2. Is this within the scope of `image-png`/`image` crates? Is there a reason `deflate::Compression::Fast` is hard coded? 

I'm more than willing to have a crack at adding this functionality if deemed appropriate.

**Comment by JackMordaunt** [comment]
> Would it be sensible to move the issue over to `image-png`? 

Yep, that's sensible. I wasn't actually sure where to submit because the issue logically spans both crates!

**Comment by HeroicKatora** [comment]
cc @bvssvni

**Comment by JackMordaunt** [comment]
I have completed the [changes](https://github.com/JackMordaunt/image-png/commit/4d436e2038d92989b5eadde632b3938083be6566) and tested them locally.
Very few changes. All tests pass. I believe it's entirely backwards compatible. 
Should I submit PR to `image-png`?

**Comment by bvssvni** [comment]
@JackMordaunt sure!

**Comment by HeroicKatora** [comment]
Adding a new public struct field is unfortunately not entirely backwards compatible as someone could make use of destructuring. That shouldn't stop us in that case. But now that I see that the filter type is hard coded to be `Filter::Sub` instead of the (slightly) more advanced `Paeth` predictor, it might be that this setting as well affects compression quality. Can you add the `filter` parameter as well so this occurs in a single version?

https://github.com/PistonDevelopers/image-png/blob/4d436e2038d92989b5eadde632b3938083be6566/src/encoder.rs#L137

Overall solid work.

**Comment by JackMordaunt** [comment]
Done.

Just a heads up: to actually allow the public to set `FilterType` I exported the symbol via [`pub use filter::FilterType;`](https://github.com/PistonDevelopers/image-png/blob/2e51b1a85bc4b5a97a587826d77ea317dc956c4e/src/lib.rs#L63).
