### ISSUE TITLE
Incremental TIFF loading

### ISSUE THREAD

**Issue by birktj** [image-rs/image#858]
Currently `TIFFDecoder::Reader` is `Cursor<Vec<u8>>`. My use case is processing of huge images and would like too have incremental loading of images (one strip at a time). This is something I would love to contribute, but I just want to check that this is something would be appreciated. At first I would like to start out with tiff, but if successful then I would like to look into other formats.

**Comment by fintelia** [comment]
Yes! This is definitely a feature we'd like to have but haven't yet had anyone with the expertise/time to implement it.
