### ISSUE TITLE
Fuzzing with travis

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image#871]
We could have a cronjob execute the fuzzing targets in travis. Note that we can [differentiate a cronjob from other builds](https://docs.travis-ci.com/user/cron-jobs/#detecting-builds-triggered-by-cron) using an environment variable. There is one cronjob active per branch and trigger at most once a day. We would have to evaluate how to nicely terminate the fuzzer, how to submit failures (and when), and how to keep the corpus small enough possibly (semi-)automatically. Obviously, we should use randomized exploration since travis does not give us any long-term storage and even if that would be exhausted rather quickly.

**Comment by Shnatsel** [comment]
A bit of context on why this is needed: https://github.com/PistonDevelopers/image-png/issues/103

Google has recently open-sourced their infrastructure to run large-scale fuzzing, this might come in handy: https://github.com/google/clusterfuzz

**Comment by Shnatsel** [comment]
Google's oss-fuzz (free-of-charge per-commit fuzzing for high-profile open-source projects) officially supports Rust now: https://github.com/google/oss-fuzz

https://fuzzit.dev/ also has a free tier for open-source
