### ISSUE TITLE
Out-of-range panic in gif::Decoder::into_frames()

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#876]
The attached test samples trigger a panic in `gif::Decoder::into_frames()` 

[gif-oor.zip](https://github.com/PistonDevelopers/image/files/2921681/gif-oor.zip)

Code for reproducing the issue:
```rust
fn gif_decode(data: &[u8]) {
    if let Ok(decoder) = image::gif::Decoder::new(data) {
        let (width, height) = decoder.dimensions();
        if width.saturating_mul(height) > 2_000_000_000 {
            return;
        }

        let frames = decoder.into_frames();
        let _ = frames.collect_frames();
    }
}
```

This bug is similar to, but distinct from #816. The attached testcases still cause crashes on latest git master (as of commit 865d2fc7b5da81c99a9b7e1cddbb2ad4f8cd06dd) while the testcase from #816 does not.

Found with [AFL.rs](https://github.com/rust-fuzz/afl.rs)

**Comment by Shnatsel** [comment]
I've filed this issue here because the backtrace points to a function in `image`. Should I file it against the `gif` crate instead?

**Comment by HeroicKatora** [comment]
I believe this may be fixed now, can't reproduce this. I'm running `cargo fuzz` instead of `afl` since the latter still requires local workarounds to compile ( :disappointed: ) but that shouldn't change much? I think everything is fixed at the moment.

**Comment by Shnatsel** [comment]
Nice, I'll re-run AFL with my fuzzing seeds and see if it uncovers anything else.

AFL is much (10x) faster if you're only looking for panics because it doesn't require address sanitizer or any other expensive sanitizers to be enabled. `codegen-units=1` in Cargo.toml fixes the AFL issue, that workaround doesn't have to be local.

**Comment by HeroicKatora** [comment]
Still seems to require the link-args changing it to `gold`. I also found `cargo-fuzz` to have a better pipeline and UX? Some crashes reports `afl` I can't reproduce at all and running the binary directly gives no indication whatsoever to help me debug them or even figure out why they are reported in the first place.

**Comment by Shnatsel** [comment]
> Still seems to require changing the linker to gold

Nope, `codegen-units=1` alone does the trick.

If you're getting crashes from AFL you can't reproduce, you're probably hitting a memory limit - fuzzer treats this as a crash. Try specifying larger value for -m parameter for AFL.

`cargo-fuzz` definitely has better UX. Its backend, libfuzzer, can function without sanitizers too (sancov alone is enough), passing this argument set is simply not implemented in the cargo-fuzz wrapper.

**Comment by HeroicKatora** [comment]
> Nope, codegen-units=1 alone does the trick.

Well I did just test it, and I even tested actively updating to `0.4.4` without success.

**Comment by Shnatsel** [comment]
Oh! Make sure you're setting `RUSTFLAGS='--cfg=fuzzing'` env variable when trying to reproduce these bugs. I've just spent 15 minutes wondering why my test crashing under fuzzer doesn't crash standalone, and that was the trick. This flag disables checksum verification so that the randomly mutated input from fuzzer can actually reach interesting code instead of being rejected immediately due to checksum mismatch.

**Comment by Shnatsel** [comment]
I can no longer reproduce this issue as of ac93e755b51def00c93e7fadd33a5e5593afa1e2, closing. I'll leave afl overnight to look for other panics.

**Comment by Shnatsel** [comment]
No further issues other than #877 were found in 50 million executions as of commit ac93e755b51def00c93e7fadd33a5e5593afa1e2

Fuzzer was seeded with both of AFL GIF corpora and seeds from earlier runs on image-gif crate, minimized with afl-cmin prior to fuzzing.
