### ISSUE TITLE
Panic "Image index out of bounds" in ImageBuffer::get_pixel()

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#878]
The following GIF images trigger a panic in `ImageBuffer::get_pixel()` when decoded: [gif-oob.zip](https://github.com/PistonDevelopers/image/files/2921696/gif-oob.zip)

Code to reproduce the issue is exactly the same as in #876. Found with [AFL.rs](https://github.com/rust-fuzz/afl.rs), tested on git commit 865d2fc7b5da81c99a9b7e1cddbb2ad4f8cd06dd

**Comment by fintelia** [comment]
I think this may be resolved? I tried running the code below and didn't see any panics (I had to rename the files to ".gif" to make the open function work):
```rust
fn main() {
    println!("{:?}", image::open("17d85872e1bb51147e968648399c8e23fda23c63.gif")).err());
    println!("{:?}", image::open("2b6bf5f87834ff9c8962a0f0229404b4b8a7cae5.gif").err());
}
```

**Comment by Shnatsel** [comment]
The exact code to reproduce the issue is listed in #876, please try that.

**Comment by fintelia** [comment]
I still wasn't able to reproduce this issue. I *was* however able to reproduce issue #877 which uses the same code, I'll post my findings about that in a bit

**Comment by Shnatsel** [comment]
As soon as all the known panics in GIF decoder are fixed or found not reproducible, I'll re-run the fuzzer and it will probably find several more.

**Comment by HeroicKatora** [comment]
Can't reproduce this one as well, closing.
