### ISSUE TITLE
[Feature] Warp perspective

### ISSUE THREAD

**Issue by abagshaw** [image-rs/image#882]
It would be great if there was a method to support warping the perspective of an image:

Take in image on left with desired four vertices and output image on the right:

![perspective](https://user-images.githubusercontent.com/8594541/54481198-d2723780-47ee-11e9-8572-fc27d9232e03.jpg)

**Comment by birktj** [comment]
I would say this is pretty clearly out of scope for this library, if you are interested in this then I would recommend to try to open an issue in [imageproc](https://github.com/image-rs/imageproc). I am closing this for now.
