### ISSUE TITLE
In 24 hours (or more), the `image` repository will move to the new `image-rs` organization

### ISSUE THREAD

**Issue by bvssvni** [image-rs/image#891]
See https://github.com/PistonDevelopers/image/issues/881#issuecomment-480171960

The `image` repository will be transferred in 24 hours, unless there are any last objections with the plan.

**Comment by HeroicKatora** [comment]
Pull requests and issues should get moved with it, so #892 should complement this after the move.

**Comment by bvssvni** [comment]
Done.

Closing.
