### ISSUE TITLE
dimensions() return u64 or u32

### ISSUE THREAD

**Issue by elbaro** [image-rs/image#906]
image::open()?.dimensions() -> u32
PNGDecoder::new(r)?.dimensions() -> u64

What is the right type for image size? Can we use it consistently?

**Comment by fintelia** [comment]
I agree that this inconsistency is unfortunate. It isn't completely clear to me what the right answer to this is though. Many image formats are restricted to dimensions <=U32_MAX, but I don't think this universal. In practice I don't think image with sizes like of 1 x 2^33 or something are common. 

Right now, the library uses u64's when working with `ImageDecoder`[`Ext`] directly (which is designed to support\ images larger than fit into memory), but switches to u32 everywhere else.

**Comment by HeroicKatora** [comment]
The interface is now consistently `u32` for sizes on buffer types and decoders. See #789 for some discussion and details.
