### ISSUE TITLE
Default implementation of `GenericImage::copy_from` has UB

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image#908]
https://github.com/image-rs/image/blob/master/src/image.rs#L677-L696

When `other.width() + x` and `other.height() + y` overflow to some small number, the bounds check succeeds but some intermediate coordinates in the loop below are out-of-bounds. Since one requirement of `unsafe_get_pixel` is an in-bounds coordinate this can lead to UB.

This is fixed as part of https://github.com/image-rs/image/pull/887 (https://github.com/image-rs/image/pull/887/files#diff-8a39248ddebc3868f5459df8e457c0a8L689) but I'd still like to have it fixed in the `0.21` series as well.

@fintelia Can you give this a look? Also, would it be possible to have a version of #887 that does not break any interfaces but removes as many *uses* of them as possible?

**Comment by HeroicKatora** [comment]
Also, this intersects the concerns of #901

**Comment by fintelia** [comment]
@HeroicKatora I agree with your assessment. I've created #909 as you suggested.

**Comment by HeroicKatora** [comment]
This indeed fixes the UB. The introduced, unexpected `panic` on overflow due to the bad check will be discussed as part of the other issue on the interface of `copy_from` and is not of immediate importance here, I think.
