### ISSUE TITLE
Write with DPI

### ISSUE THREAD

**Issue by fenhl** [image-rs/image#911]
I need to write an image as PNG with a given DPI value. The Pillow library (Python) allows this using an optional `dpi=` parameter on `Image.save`, which isn't possible in Rust, but maybe separate `write_to_dpi` and `save_dpi` methods could be added.

**Comment by HeroicKatora** [comment]
`dpi` is metadata–about the relationship of a pixel to physical units on the display– that is not applicable to all images formats, some of which do not represent much more than an encoding of the pixel data. I don't think this is possible in general, but only in those specific formats which support it.

For `png` specifically, this is solved by adding a special chunk–with name `pHYs`. You could [use the `Write`](https://docs.rs/png/0.14.1/png/struct.Writer.html) to *prepend* the appropriate metadata which needs to appear before the image data, then copy the rest of the data from the output of `image`. More information on [the chunk type `pHYs`](https://www.w3.org/TR/PNG/#11pHYs).

**Comment by birktj** [comment]
@HeroicKatora I think some sort of general metadata api with graceful fallback would be nice for the long-term. We should at least add some support for writing metadata in  `image-png` that doesn't require the user to manually create the `pHYs` chunk.

**Comment by HeroicKatora** [comment]
@birktj Agreed, but the general metadata api will likely be long-term as you said, so I'm trying to indicate a work around. For `png` it would really be nice to have all standard chunk types represented in the library.

**Comment by birktj** [comment]
Agreed, I will have look at what I can do in order to add some more high-level encoding functions to `image-png`. @fenhl for now you should probably use the workaround by @HeroicKatora and hopefully we can add some more support for stuff like this to the png library soon.

**Comment by fintelia** [comment]
The `png` crate now [supports setting pixel dimensions](https://docs.rs/png/0.17.13/png/struct.Info.html#structfield.pixel_dims).
