### ISSUE TITLE
Encoders use `io::Error` instead of `ImageError`

### ISSUE THREAD

**Issue by birktj** [image-rs/image#921]
I just realized that encoders use `io::Error` as errors instead of `ImageError`, wouldn't it be better to use `ImageError` in order to signal more specific encoding errors like unsupported color formats, etc?

**Comment by HeroicKatora** [comment]
Yes, it would. The most prevalent misuse seems to be to also instantiate a `String` as the inner component of `io::Error`, as noted by [this user as well](https://github.com/image-rs/image/issues/896#issuecomment-482441435). One of the challenges would be to design a set of errors that is not too detailed, i.e. not necessarily specific to a single image type, but still informative enough to provide more than an effective `Box<Error + Any>`.

My thought was that it may be possible to use a more specific error type (e.g. `PngError` that could simply be an alias the crate's error type) for single `ImageDecoder` implementation with an impl `From<PngError> for ImageError`, which is used in the `impl` for the `ImageDecoder` trait. This would make it possible to have tightly integrated error types in every decoder and that should lead to us recoginizing shared needs and patterns more easily. Hopefully.

**Comment by birktj** [comment]
I was going to try your suggestion with `ImageError` variants like `PngError`, etc.. however it seems like the error handling in the en/decoder crates is already to messed up. For example the `png` crate uses two error enums, `png::DecoderError` and `png::EncoderError`, however the `EncoderError` only has two variants `IoError(io::Error)` and `Format(Cow<str>)`. And the `gif` crate doesn't even use a custom error type for encoding, just `io::Error` with stuff like this: 

```rust
io::Error::new(io::ErrorKind::InvalidInput, "Too many colors")
```

I think I am going to start by trying to create a better set of general errors for the `ImageError` enum, and then we can start looking into improving the en/decoder error types.
