### ISSUE TITLE
Not all encoders are supported by `save_buffer`

### ISSUE THREAD

**Issue by birktj** [image-rs/image#927]
It seems we have both a `gif` encoder and a `dxt` encoder, but none of them are implemented in `save_buffer`. I assume this is just an oversight, but it would be nice to fix.

See also #676

**Comment by Josh015** [comment]
Anyone working on this one? If not, I can try to knock it out really quick.

**Comment by Josh015** [comment]
Actually, wait. It looks like ```gif``` is already implemented in ```save_buffer_impl```. As for ```dxt```, I'm a little confused about that one. Is it supposed to mean ```dds```? If so, that'll require implementing an encoder for that file format first.

**Comment by fintelia** [comment]
No, we have a separate `dds` module for that format. `dxt` refers to raw block compressed image data with no metadata, and is used by the dds code. Honestly, it isn't really an image format itself and should probably not be treated as one in this crate...

**Comment by Josh015** [comment]
Yeah, that's why I was confused. Also, I'm now realizing the issue that was merged into this one seems to have a more detailed discussion. I think I'll leave this one alone for now.

**Comment by HeroicKatora** [comment]
This was fixed in #1391 I believe.
