### ISSUE TITLE
Drop local crc32 implementation in favor for crc32fast

### ISSUE THREAD

**Issue by martinlindhe** [image-rs/image#931]
Similar to https://github.com/image-rs/image-png/issues/127, the image crate also holds a local crc32 implementation in https://github.com/image-rs/image/blob/master/tests/reference_images.rs#L200

**Comment by martinlindhe** [comment]
As image crate only uses crc32 in tests, crc32fast was added to dev-dependencies

**Comment by fintelia** [comment]
Do you think that crc32 is the right hash for that use? If we're pulling in a library, perhaps we should just go with sha3 or something?

**Comment by martinlindhe** [comment]
@fintelia In this context I think crc32 works well.
We only use it to verify uncompressed image data matches a expected checksum, which is also encoded in the filenames.
I don't see how this could be misused, but I am not a security expert.

If we were to swap algorithm, we would need to update all filenames in tests/reference/
