### ISSUE TITLE
Color Spaces

### ISSUE THREAD

**Issue by lazypassion** [image-rs/image#958]
Does this library have any plans to support the different color spaces like HSL and HSV and conversions between them or would that be more appropriate in imageproc?

**Comment by HeroicKatora** [comment]
Nothing concrete, and especially no draft on how to actuall do it. But I wish it had because some components have implicit assumptions on `RGB` being `sRGB` etc.

**Comment by HeroicKatora** [comment]
Please contribute any ideas to the already open discussions:

* #855 on how to do `ColorType` correctly, and how to fit `Pixel` in it.
* #786 for related crate and nudging us to provide color space it in a layer above `Pixel`
* #665 which prompts the question of how to support 16-bit pixel but keep the complexity of color space handling low
* #599 remarking an instance of where the assumption made by parts of the lib are actually bogus
* #598 with another instance, this being `sRGB` assumption (note: not even that completely correct btw)
* #575 for general support of HSV color space
