### ISSUE TITLE
Generating Fractals README Example is Failing

### ISSUE THREAD

**Issue by luigishat** [image-rs/image#962]
The compiler fails running the "Generating Fractals" README Example.

The Error is on the line:
let image::Rgb(data)= *pixel;

The simple fix is to replace the "(data)" with "{data}" so the values pointed to (*pixel) are properly de-structured.

The resulting fixed example looks like this:

//! An example of generating julia fractals.
extern crate image;
extern crate num_complex;

fn main() {
    let imgx = 800;
    let imgy = 800;

    let scalex = 3.0 / imgx as f32;
    let scaley = 3.0 / imgy as f32;

    // Create a new ImgBuf with width: imgx and height: imgy
    let mut imgbuf = image::ImageBuffer::new(imgx, imgy);

    // Iterate over the coordinates and pixels of the image
    for (x, y, pixel) in imgbuf.enumerate_pixels_mut() {
        let r = (0.3 * x as f32) as u8;
        let b = (0.3 * y as f32) as u8;
        *pixel = image::Rgb([r, 0, b]);
    }

    // A redundant loop to demonstrate reading image data
    for x in 0..imgx {
        for y in 0..imgy {
            let cx = y as f32 * scalex - 1.5;
            let cy = x as f32 * scaley - 1.5;

            let c = num_complex::Complex::new(-0.4, 0.6);
            let mut z = num_complex::Complex::new(cx, cy);

            let mut i = 0;
            while i < 255 && z.norm() <= 2.0 {
                z = z * z + c;
                i += 1;
            }

            let pixel = imgbuf.get_pixel_mut(x, y);
            let image::Rgb{ data } = *pixel;
            *pixel = image::Rgb([data[0], i as u8, data[2]]);
        }
    }

    // Save the image as “fractal.png”, the format is deduced from the path
    imgbuf.save("fractal.png").unwrap();
}

**Comment by HeroicKatora** [comment]
The reason for this is that the example on `master` is ahead of `v0.21.1`, not the other way around. The next release will contain the updated struct as `Rgb(_)`. All examples in the `README` are ran within CI to ensure that they are accurate.
