### ISSUE TITLE
Use iterators and entry on ICO

### ISSUE THREAD

**Issue by cyberpunkbln** [image-rs/image#965]
Hello,
a little question. Give it an iterator for the ICO Format over the entrys in the ico-file and with width and height as an usable variable for an foreach?

Thx for help.

**Comment by HeroicKatora** [comment]
I have hostely no idea what is being asked here, maybe you can rephrase the question and provide some more context?

**Comment by cyberpunkbln** [comment]
When i load an ICO with `let mut img_png = image::open(&Path::new(&icoPath2.to_string())).ok().expect("Opening image failed");` i think it choose the latest entry in ico-list or the ico with the biggest size (i think the last entry).

Is it possible that i can fetch the list of ico entrys that i can make an

for icon as img_png_entries()
{
 fetch the entries and choose the one that i want
}

At the moment i trust in the mechanism from image but it gives icons that mix free the entry list or put the biggest size to entry 0 and not to the last entry or put different icons in one icon.

**Comment by martinlindhe** [comment]
ICO is a container format which usually holds more than one resolution image.

Not sure its possible today, ico decoder seems to auto select the "best entry" here https://github.com/image-rs/image/blob/master/src/ico/decoder.rs#L46

**Comment by martinlindhe** [comment]
#884 is similar issue but for encoding ico

**Comment by cyberpunkbln** [comment]
Ah okay, the mechanism "best entry" fits for me at the moment. The "last entry" can cause some bad results. I see that the feature are requested and think that it goes just like "Reading". Thx.

**Comment by cyberpunkbln** [comment]
@martinlindhe Exactly i'm used the ICO::Decoder on an ico with an 255er he cannot read this icon and when i have a reversed entry-list:).
