### ISSUE TITLE
Combine ImageBuffer from crate-ico?

### ISSUE THREAD

**Issue by cyberpunkbln** [image-rs/image#966]
Hello,

i have following problem. When i use your ICO::Decoder he has problems with icons that has no standard icon-entry and with icon-entrys that are reversed. A few of my readed icons has this issues. So i must use the crate-ico as an bridge.

Now i have the choice to extract the icon with crate-ico, save as an png and reuse this png in your crate and do my image-operations with your crate. But this are useless file operations.

I'm load the icon with crate-ico and use the ImageBuffer from crate-ico.

```
let file = std::fs::File::open(icoPath).unwrap();
let icon_dir = ico::IconDir::read(file).unwrap();
let image = icon_dir.entries()[iconIndex].decode().unwrap();
let rgba = image.rgba_data();
```

How i can use this buffer rgba with the buffer in your crate, like an buffer that comes back with image::open?

thx

ps: hopefully you increase your ICO::Decoder like the functionality in crate-ico.

**Comment by fintelia** [comment]
The `from_raw` and `to_raw` methods on ImageBuffer let you easily move between raw vectors and image buffers. You should just be able to do:

```rust
let img = RgbaImage::from_raw(image.width(), image.height(), rgba.to_vec());
```

And if you want to convert to a DynamicImage:
```rust
let d = DynamicImage::ImageRgba8(img);
```

**Comment by cyberpunkbln** [comment]
@fintelia Functioned Perfect.
