### ISSUE TITLE
Split specific formats into smaller crates

### ISSUE THREAD

**Issue by mooman219** [image-rs/image#991]
Like with `image-png`, it would be nice to see `jpeg` and `bmp` broken out into their own crates in a way that doesn't depend on the image crate.

**Comment by fintelia** [comment]
See also #793 to move some of the basic types/traits into their own crate so that all the format specific crates can be consistent and interoperable.

**Comment by icefoxen** [comment]
Started doing this with `bmp`, repo is here: https://github.com/icefoxen/image-bmp

Let me know if this looks like a good start and I can transfer the repo to the `image-rs` group and start making a PR to this crate to use it.
