### ISSUE TITLE
Load headerless bmps

### ISSUE THREAD

**Issue by xTachyon** [image-rs/image#992]
Hello. From what I can tell, there isn't a way to load directly a headerless bmp. Sorry if there is and I couldn't find it.

Now, I get that there might be some additional parameters I'd have to supply manually without the header, but it'd still be nice to be possible. 

Right now my options are to either create the header manually or use a crate like `png_encode_mini` to write a png to disk(that's what I do), and then read it from `image`.

Thank you for your answers.

**Comment by fintelia** [comment]
Where are you getting headerless bmps and how do you know the additional parameters if there is no header? And what is the end goal you are trying to achieve? If you already have a contigious array of pixels it might just be enough to call  [`ImageBuffer::from_raw`](https://docs.rs/image/0.22.0/image/struct.ImageBuffer.html#method.from_raw) or similar?
