### ISSUE TITLE
unsafe_get_pixel deprecation

### ISSUE THREAD

**Issue by theotherphil** [image-rs/image#999]
I've bumped imageproc's image dependency to 0.22.1 and run into the fact that unsafe_get_pixel on GenericImageView is now deprecated. 

From this PR it looks like the justification is that it's ok to force users' code to be slower, in exchange for enabling deny_unsafe: https://github.com/image-rs/image/pull/960

As a user of this crate, I strongly disagree! I'd like to remove the deprecation, with the addition of suitably strong wording in the function's documentation if you like. Users of GenericImageView can always choose to not use this function, and implementors can decide not to override the default, but in cases where you want to use it I don't think we should force users to pay for bounds checks they don't want.

**Comment by fintelia** [comment]
Do you have any code which actually demonstrates that a significant slowdown from the bounds check, and which couldn't be rewritten with safe code? In many cases the optimizer might be able to remove the bounds check, and in many others the branch predictor should reduce the overhead to almost zero (ie by speculatively executing the memory access in parallel to the check). And if you need the absolute highest performance, you probably shouldn't be accessing pixels one by one via a function at all and should instead operate on a whole slice of them at once.

**Comment by HeroicKatora** [comment]
> Do you have any code which actually demonstrates that a significant slowdown from the bounds check, and which couldn't be rewritten to be equally fast using only safe code? 

I have checked, the optimizer doesn't remove the bounds checks for about all of the pixel accesses [in region labelling](https://github.com/image-rs/imageproc/blob/master/src/region_labelling.rs#L121).

**Comment by theotherphil** [comment]
I've created a branch without any unsafe_get_pixel or unsafe_put_pixel: https://github.com/image-rs/imageproc/commit/298e35f56ba5857a49da4503f2628c0d4200ba34

The results are a bit noisy, but show some pretty large slowdowns on the functions which no longer use unsafe

<pre>
cargo benchcmp before.txt after.txt --regressions
 name                                                                       before.txt ns/iter  after.txt ns/iter  diff ns/iter   diff %  speedup 
 affine::tests::bench_affine_bilinear                                       712,935             776,682                  63,747    8.94%   x 0.92 
 affine::tests::bench_affine_nearest                                        354,964             389,015                  34,051    9.59%   x 0.91 
 affine::tests::bench_rotate_bilinear                                       357,103             379,842                  22,739    6.37%   x 0.94 
 affine::tests::bench_rotate_nearest                                        286,582             294,750                   8,168    2.85%   x 0.97 
 affine::tests::bench_translate                                             216,259             459,647                 243,388  112.54%   x 0.47 
 contrast::tests::bench_adaptive_threshold                                  460,014             486,652                  26,638    5.79%   x 0.95 
 contrast::tests::bench_equalize_histogram                                  475,945             499,944                  23,999    5.04%   x 0.95 
 contrast::tests::bench_match_histogram                                     108,254             113,348                   5,094    4.71%   x 0.96 
 corners::tests::bench_is_corner_fast12_12_noncontiguous                    20                  30                           10   50.00%   x 0.67 
 corners::tests::bench_is_corner_fast9_9_contiguous_lighter_pixels          17                  28                           11   64.71%   x 0.61 
 distance_transform::tests::bench_distance_transform_l1_10                  406                 703                         297   73.15%   x 0.58 
 distance_transform::tests::bench_distance_transform_l1_100                 31,060              61,483                   30,423   97.95%   x 0.51 
 distance_transform::tests::bench_distance_transform_l1_200                 117,712             245,657                 127,945  108.69%   x 0.48 
 distance_transform::tests::bench_distance_transform_linf_10                594                 974                         380   63.97%   x 0.61 
 distance_transform::tests::bench_distance_transform_linf_100               55,661              99,308                   43,647   78.42%   x 0.56 
 distance_transform::tests::bench_distance_transform_linf_200               223,757             413,622                 189,865   84.85%   x 0.54 
 distance_transform::tests::bench_euclidean_squared_distance_transform_10   2,510               2,841                       331   13.19%   x 0.88 
 distance_transform::tests::bench_euclidean_squared_distance_transform_100  169,526             219,907                  50,381   29.72%   x 0.77 
 distance_transform::tests::bench_euclidean_squared_distance_transform_200  698,388             872,621                 174,233   24.95%   x 0.80 
 drawing::conics::tests::bench_bench_hollow_ellipse_vertical                955                 965                          10    1.05%   x 0.99 
 drawing::line::tests::bench_draw_antialiased_line_segment_diagonal         4,518               4,637                       119    2.63%   x 0.97 
 drawing::line::tests::bench_draw_antialiased_line_segment_horizontal       4,585               4,634                        49    1.07%   x 0.99 
 drawing::line::tests::bench_draw_antialiased_line_segment_vertical         3,303               3,363                        60    1.82%   x 0.98 
 drawing::rect::tests::bench_draw_filled_rect_mut_rgb                       12,302              12,770                      468    3.80%   x 0.96 
 edges::tests::bench_canny                                                  2,976,283           4,127,404             1,151,121   38.68%   x 0.72 
 filter::median::tests::bench_median_filter_s100_r1                         122,884             158,921                  36,037   29.33%   x 0.77 
 filter::median::tests::bench_median_filter_s100_r4                         213,781             314,638                 100,857   47.18%   x 0.68 
 filter::median::tests::bench_median_filter_s100_r8                         347,973             517,414                 169,441   48.69%   x 0.67 
 filter::median::tests::bench_median_filter_s100_rx1_ry4                    121,278             149,922                  28,644   23.62%   x 0.81 
 filter::median::tests::bench_median_filter_s100_rx1_ry8                    127,916             152,173                  24,257   18.96%   x 0.84 
 filter::median::tests::bench_median_filter_s100_rx4_ry8                    213,885             291,973                  78,088   36.51%   x 0.73 
 filter::median::tests::bench_median_filter_s100_rx8_ry1                    336,862             483,218                 146,356   43.45%   x 0.70 
 filter::tests::bench_box_filter                                            2,100,587           2,589,922               489,335   23.30%   x 0.81 
 filter::tests::bench_filter3x3_i32_filter                                  1,570,518           2,622,092             1,051,574   66.96%   x 0.60 
 filter::tests::bench_gaussian_f32_stdev_1                                  355,136             409,195                  54,059   15.22%   x 0.87 
 filter::tests::bench_gaussian_f32_stdev_10                                 2,427,840           2,568,909               141,069    5.81%   x 0.95 
 filter::tests::bench_gaussian_f32_stdev_3                                  788,060             880,021                  91,961   11.67%   x 0.90 
 filter::tests::bench_horizontal_filter                                     2,310,023           2,859,315               549,292   23.78%   x 0.81 
 filter::tests::bench_separable_filter                                      1,635,813           1,878,586               242,773   14.84%   x 0.87 
 filter::tests::bench_vertical_filter                                       2,052,766           2,551,193               498,427   24.28%   x 0.80 
 gradients::tests::bench_sobel_gradients                                    3,486,039           5,799,191             2,313,152   66.35%   x 0.60 
 haar::tests::bench_evaluate_all_features_10x10                             69,796              92,717                   22,921   32.84%   x 0.75 
 hog::tests::bench_hog                                                      401,642             438,014                  36,372    9.06%   x 0.92 
 hough::tests::bench_detect_line_50_45                                      201,459             282,682                  81,223   40.32%   x 0.71 
 hough::tests::bench_detect_line_eps_135                                    214,125             302,513                  88,388   41.28%   x 0.71 
 hough::tests::bench_detect_line_neg10_120                                  202,167             290,233                  88,066   43.56%   x 0.70 
 hough::tests::bench_detect_lines                                           2,013,054           3,175,767             1,162,713   57.76%   x 0.63 
 integral_image::tests::bench_column_running_sum                            801                 1,051                       250   31.21%   x 0.76 
 integral_image::tests::bench_integral_image_rgb                            831,837             910,156                  78,319    9.42%   x 0.91 
 integral_image::tests::bench_row_running_sum                               442                 846                         404   91.40%   x 0.52 
 local_binary_patterns::tests::bench_local_binary_pattern                   2,454               3,589                     1,135   46.25%   x 0.68 
 morphology::tests::bench_dilate_l1_5                                       1,250,772           2,552,662             1,301,890  104.09%   x 0.49 
 morphology::tests::bench_dilate_linf_5                                     2,272,830           4,481,717             2,208,887   97.19%   x 0.51 
 noise::tests::bench_gaussian_noise_mut                                     111,312             118,479                   7,167    6.44%   x 0.94 
 noise::tests::bench_salt_and_pepper_noise_mut                              89,934              97,143                    7,209    8.02%   x 0.93 
 region_labelling::tests::bench_connected_components_eight_chessboard       849,444             1,114,493               265,049   31.20%   x 0.76 
 region_labelling::tests::bench_connected_components_four_chessboard        338,345             462,647                 124,302   36.74%   x 0.73 
 seam_carving::tests::bench_shrink_width_s100_r1                            178,346             269,368                  91,022   51.04%   x 0.66 
 seam_carving::tests::bench_shrink_width_s100_r4                            698,763             1,053,328               354,565   50.74%   x 0.66 
 seam_carving::tests::bench_shrink_width_s100_r8                            1,367,730           2,060,102               692,372   50.62%   x 0.66 
 stats::tests::bench_root_mean_squared_error_rgb                            14,438              14,489                       51    0.35%   x 1.00 
 suppress::tests::bench_local_maxima_dense                                  32,784              37,931                    5,147   15.70%   x 0.86 
 suppress::tests::bench_suppress_non_maximum_decreasing_gradient            881                 1,306                       425   48.24%   x 0.67 
 suppress::tests::bench_suppress_non_maximum_increasing_gradient            1,344               1,957                       613   45.61%   x 0.69 
 suppress::tests::bench_suppress_non_maximum_noise_1                        3,650               6,830                     3,180   87.12%   x 0.53 
 suppress::tests::bench_suppress_non_maximum_noise_3                        2,297               3,738                     1,441   62.73%   x 0.61 
 suppress::tests::bench_suppress_non_maximum_noise_7                        1,800               2,597                       797   44.28%   x 0.69 
 template_matching::tests::bench_match_template_s100_t16_sse                2,139,297           3,900,844             1,761,547   82.34%   x 0.55 
 template_matching::tests::bench_match_template_s100_t16_sse_norm           2,136,886           3,905,173             1,768,287   82.75%   x 0.55 
 template_matching::tests::bench_match_template_s100_t1_sse                 38,029              43,074                    5,045   13.27%   x 0.88 
 template_matching::tests::bench_match_template_s100_t1_sse_norm            38,022              42,962                    4,940   12.99%   x 0.89 
 template_matching::tests::bench_match_template_s100_t4_sse                 222,520             340,870                 118,350   53.19%   x 0.65 
 template_matching::tests::bench_match_template_s100_t4_sse_norm            226,328             338,796                 112,468   49.69%   x 0.67 
</pre>

**Comment by HeroicKatora** [comment]
>  affine::tests::bench_translate                                             216,259             459,647                 243,388  112.54%   x 0.47 

Ouch. It looks not too complicated: https://github.com/image-rs/imageproc/blob/ca6cfce9d3848a726c770acc02162ca51d597733/src/affine.rs#L285-L310 Something about the involved bounds arithmetic must really confuse llvm.

**Comment by HeroicKatora** [comment]
@fintelia Can we simply remove the deprecation of the methods? It doesn't seem likely that we remove them soon and there are no immediate soundness issues that really require their removal. Also, we should maybe add `imageproc` benchmarks to our release process at least it is a decent indicator for performance?

One more though on indexing: It is probably suboptimal that indexing into the image by `(x, y)` requires multiple multiplications and there is no way to sidestep this by precalculating the linear index of the pixel. Some experimentation required but a linear access interface would reduce the reliance on the compiler's internal value-range analyzer and hopefully lead to better bounds-check elision but we'd have to clear up how to fit this into the trait interface.

**Comment by fintelia** [comment]
I tried writing a [safe version of the translate function](https://github.com/fintelia/imageproc/commit/c011d6abb1063ea0cbb109df852f0f397819635b) to takes advantage of the fact that the input is an ImageBuffer (and thus the layout is known). It not only avoided incurring extra bounds checking overhead, it also ended up being about 10 _times_ faster than the version we have now.

**Comment by fintelia** [comment]
I'm OK with holding off on removing these methods, though I also feel that trying to use the GenericImage interface for performance sensitive code is counterproductive given how abstract it is. 

One semi-crazy idea would be to deprecate GenericImage entirely and switch focus to using FlatSamples. It already has the features we're interested in: support for linear index precomputation, users can opt out of bounds checks via unsafe methods on slices (meaning no unsafe in the crate!) and conveys layout information enabling potential optimizations.

**Comment by HeroicKatora** [comment]
@fintelia Hm, that's indeed interesting. Does that mean that many more methods could benefit from the explicit `ImageBuffer` assumption instead of being generic over `GenericImage`? Seems somewhat likely.

But to address the specific question at hand, how does your version perform if you *do use* `unsafe_get_pixel` and `unsafe_put_pixel`? The `copy_from_slice` invocations are performed using raw pointer ops internally so the effect may be more limited.

> One semi-crazy idea would be to deprecate GenericImage entirely and switch focus to using FlatSamples.

Don't know if that's a good idea. I'm worried about a good replacement for `DynamicImage` first and establish that does fit as a replacement overall, which may be much harder if we narrow the representation far from `GenericImage`. However, I do think that `impl GenericImage` is a suboptimal input type for *fast* image compuations. I just wish we had specialization because then all this would be a non-issue: There could be a generic version of image algorithms for `impl GenericImage` and a specialized, fast version for `ImageBuffer`, one for `FlatSamples` etc.

Also, `FlatSamples` does not give the same interface as a `GenericImage`, it first needs to get a transformed into a `ViewMut` which is only borrowed and never owned (that could be fixed) but more importantly is much harder to create–additional steps and failure since it has many more runtime inputs. It's also more fexible but that means that generic strides instead of associated consts from `Pixel` need to be involved in pixel `put` and `get`. So from a performance perspective, flat samples require additional indirection and more index calculation compared to `ImageBuffer`, and would unlikely be a very good

**Comment by HeroicKatora** [comment]
Actually, that may be a sensible conclusion: Hold off on deprecation until specialization lands?
